
export const RAW_DATA: Record<string, string[]> = {
  "Ở nhà": [
    "Tôi vừa 18 tuổi và không biết gì về tình dục, cho đến 1 ngày nhìn thấy Dì và Chú ( tôi mồ côi được gia đình người bạn của mẹ nhận nuôi, họ có 2 người con gái) đang làm gì đó trong phòng của họ, cu của tôi đột nhiên căng tức và cương cứng, phải làm sao đây.",
    "Chị gái vô tình ngã vào lòng bạn khi trượt chân trên sàn nhà vừa lau.",
    "Em gái nuôi nhờ bạn xoa bóp vai vì mỏi cổ sau giờ học căng thẳng.",
    "Bạn và mẹ kế cùng lúc mở cửa phòng tắm, thấy bà chỉ quấn độc chiếc khăn mỏng.",
    "Bạn và em gái cùng nằm xem phim, đôi chân nàng vô tình gác lên đùi bạn.",
    "Vô tình thấy chị gái đang soi gương thử bộ bikini mới mua cho chuyến du lịch.",
    "Chị gái bị tuột dây áo lót khi đang nấu ăn, bạn phải giúp nàng cài lại trong sự lúng túng.",
    "Em gái nuôi (18 tuổi) bị chuột rút trong lúc tắm, bạn phải lao vào bế nàng ra trong tình trạng khỏa thân.",
    "Em gái lén lấy ảnh của bạn để dưới gối, mỗi đêm đều mang ra ngắm nhìn dâm mị.",
    "Chị gái nuôi lén vào phòng bạn lúc nửa đêm, quỳ xuống bú cu bạn với đôi mắt dâm mị.",
    "Nàng em gái lén lấy quần lót của bạn để thủ dâm, bạn bắt quả tang và ép nàng phải dùng miệng mút quy đầu nóng hổi bù đắp.",
    "Bị mẹ kế bắt quả tang đang ngửi đồ lót của bà, bà không mắng mà ép bạn phải nện bà để thỏa mãn cơn vã xác thịt hồi xuân.",
    "Tiếng rên rỉ kìm nén của chị gái từ phòng bên kích thích bạn lẻn vào chăn và bắt đầu hành trình phá nát sự đoan trang của nàng.",
    "Bạn bắt gặp em gái đang dùng dương vật giả, nàng khóc lóc van xin bạn 'giữ bí mật' bằng cách cho bạn nện lồn trinh.",
    "Trong lúc xem phim, cô em gái lén luồn tay vào háng bạn sờ soạn cây cu đang cứng ngắc, đôi mắt nàng dại đi vì dục vọng tội lỗi.",
    "Nàng em gái ngây thơ bị bạn lừa chơi trò 'khám sức khỏe', đôi bàn tay bạn thọc sâu vào hang động khít khao làm nàng phun nước.",
    "Chị gái lén nhìn trộm bạn thủ dâm qua khe cửa, đôi vú nàng ép chặt vào cánh gỗ, dâm thủy chảy ròng ròng xuống bắp đùi.",
    "Trong lúc cả nhà ngủ say, em gái nuôi lén lẻn vào giường bạn, đôi môi nhỏ nhắn mút chặt lấy cây cu gân guốc của bạn trong bóng tối.",
    "Bắt quả tang mẹ kế đang tự sướng bằng cà rốt trong bếp, bạn lấy cây cu nóng hổi của mình thay thế và nện bà đến mức trợn mắt vì sướng.",
    "Cửa phòng em gái không chốt, bạn vô tình thấy nàng đang khỏa thân soi gương, đôi tay đang mân mê núm vú hồng nhạt vì tò mò giới tính.",
    "[HỆ THỐNG]: Cảnh báo: Chỉ số nứng của mẹ kế đang ở mức cực hạn. Hãy thực hiện hành động giải tỏa để nhận 500 điểm kinh nghiệm.",
    "[HỆ THỐNG]: Nhiệm vụ: Khiến mẹ kế chủ động hôn bạn. Phần thưởng: 100 điểm mị lực.",
    "[HỆ THỐNG]: Cảnh báo: Độ hảo cảm của em gái đang tăng vọt. Mở khóa kỹ năng 'Giao tiếp bằng mắt'.",
    "[HỆ THỐNG]: Thông báo: Hãy hoàn thành chuỗi nhiệm vụ 'Gia đình hạnh phúc'. Nhận danh hiệu 'Chủ nhân ngôi nhà'.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp áo lót ren của chị gái một cách dễ dàng.",
  ],
  "Tự do": [
    "Hệ Thống gánh con.",
    "Tôi làm nghề chăm sóc phụ nữ mọi lứa tuổi và gieo giống thuê.",
    "Tôi bán gói dịch vụ sung sướng cho phái nữ.",
    "Chàng shipper may mắn và cô chủ nhà nứng lồn.",
    "Chàng shipper may mắn và cô chủ nhà thả rông cặp vú to.",
    "Chàng tài xế xe công nghệ may mắn và cô khách đi xe nứng lồn.",
    "Gặp được cô nhân viên Cửa hàng tiện lợi dâm đãng thích tư vấn bán bao cao su.",
    "Cứu mĩ nhân ở Bể bơi công cộng.",
    "Làm quen với cô gái khi đi xem phim kinh dị ở rạp chiếu phim, cô gái nhát gan thích xem phim kinh dị.",
    "làm quen với cô tiếp viên xinh đẹp trên Máy bay.",
    "Tôi bắt được cô gái ăn cắp đồ ở cửa hàng và trừng phạt cô ta",
    "Cứu cô gái bị chuốc rượu say.",
    "Cứu cô gái bị chuốc thuốc.",
    "Cứu mĩ nhân ở Bãi biển/Resort.",
    "Lên giường với gái lạ sau khi say.",
    "Cứu mĩ nhân khỏi tay bọn lưu manh.",
    "Làm gia sư cho cô gái dâm có mẹ trẻ đẹp.",
    "Cứu cô gái nghèo ở Quán Bar/Vũ trường.",
    "Bắt gặp cô gái trẻ chỉ mặc 1 chiếc áo 2 dây đang thủ dâm ở công viên.",
    "Thuê phải cô gia sư trẻ mà dâm đãng.",
    "Đi ăn cùng nhóm bạn thì nhặt được chiếc điều khiển máy rung của cô bạn đánh rơi.",
    "Tôi mở nhà hàng và bắt nữ nhân viên không mặc quần lót.",
    "[HỆ THỐNG]: Hệ thống Cày điểm hảo cảm mĩ nữ.",
    "[HỆ THỐNG]: Hệ thống Điểm danh.",
    "[HỆ THỐNG]: Hệ thống Mỗi tuần có 1 nghề nghiệp mới.",
    "[HỆ THỐNG]: Hệ thống Có 999999 tỷ tiền liếm cẩu, tiêu tiền cho gái để được hoàn trả gấp nhiều lần.",
    "[HỆ THỐNG]: Hệ thống Thần hào.",
  ],
  "Ở nhà thuê": [
    "Vô tình thấy cô bé sinh viên năm nhất đang loay hoay sửa bóng đèn trong phòng.",
    "Cô giáo thực tập phòng đối diện nhờ bạn bê hộ chồng giáo án nặng trịch.",
    "Chiếc khăn tắm của cô nàng streamer bị tuột khi nàng đang mở cửa nhận đồ ship.",
    "Cô bé sinh viên bị kẹt khóa cửa phòng, phải sang phòng bạn ngồi nhờ trong bộ đồ ngủ ngắn.",
    "Dãy trọ cũ kỹ với những bức tường mỏng manh không ngăn được những tiếng động nhạy cảm.",
    "Giúp cô chủ trọ sửa vòi nước, nàng cố tình tì bộ ngực đồ sộ vào lưng bạn, hơi ấm xác thịt lan tỏa khiến cây cu bạn cứng ngắc như thép.",
    "Mưa bão mất điện, cô bé sinh viên phòng bên sợ hãi chạy sang phòng bạn trú ẩn, hai cơ thể quấn chặt lấy nhau giữa bóng tối.",
    "Bé sinh viên năm nhất bị bạn lừa vào phòng, đôi bàn tay bạn thô bạo nhào nặn đôi vú mơn mởn làm nàng khóc lóc trong khoái lạc.",
    "Nữ sinh viên nghèo chấp nhận trả tiền phòng bằng xác thịt, nàng quỳ xuống banh rộng lồn hồng cho bạn tha hồ cày cấy.",
    "Bạn nắc nàng sinh viên ngay trong phòng tắm chung, tiếng rên rỉ bị lấp đầy bởi tiếng nước chảy nhưng vẫn đầy dâm đãng và kích thích.",
    "Chị gái phòng đối diện say rượu gõ nhầm cửa, nàng lao vào ôm hôn bạn, đôi tay tham lam sờ soạng cây cu đang cứng ngắc.",
    "Cô nàng streamer phòng bên mặc áo hai dây không nội y sang nhờ sửa máy tính, núm vú sưng cứng cứ thế cọ vào tay bạn.",
    "Nữ sinh viên tầng trên lén lẻn vào phòng bạn lúc đêm khuya, quỳ xuống bú cu bạn với đôi mắt dâm mị cầu xin được lấp đầy.",
    "Bị bà chủ nhà bắt quả tang đang ngửi đồ lót của nàng, nàng không mắng mà ép bạn phải nện nàng để trả nợ tiền phòng.",
    "Cô nàng streamer phòng bên lén lẻn vào giường bạn, cầu xin bạn nện thật mạnh để tăng cảm hứng livestream dâm dục.",
    "Nhìn trộm nữ sinh phòng bên tự sướng qua lỗ thủng vách tường, nước lồn nàng chảy lênh láng ướt đẫm cả drap giường.",
    "Vô tình va chạm với cô giáo thực tập ở cầu thang, đôi môi nóng hổi của nàng chạm vào môi bạn làm bùng nổ dục vọng.",
    "Bạn nắc cô sinh viên nghèo để trừ tiền trọ, lồn nàng co thắt chặt như muốn nuốt chửng cây cu gân guốc của bạn.",
    "Phòng bên cạnh đang hành lạc, bạn đục lỗ tường và chứng kiến cảnh tượng nhầy nhụa, dương vật bạn cương cứng thách thức.",
    "Tiếng rên rỉ của cặp đôi phòng bên cạnh kích thích bạn và cô bạn trọ cùng lao vào nhau làm tình điên cuồng xuyên đêm.",
    "Cô chủ trọ diện váy ngủ mỏng tang sang thu tiền phòng, nàng cố tình tì bộ ngực đồ sộ vào tay bạn gợi ý 'thanh toán bằng cách khác'.",
    "Bắt quả tang nữ sinh phòng đối diện đang nhìn lén bạn thủ dâm qua khe cửa, bạn lôi nàng vào phòng và bắt nàng phải bú cu cho mình.",
    "Nữ sinh phòng bên chủ động sang gõ cửa lúc nửa đêm chỉ để xin được bạn 'an ủi' thể xác sau khi chia tay bạn trai, hai người quất nhau cả đêm.",
    "[HỆ THỐNG]: Thông báo: Độ thiện cảm của bà chủ nhà đã đạt mức 'Ái Mộ'. Mở khóa nhiệm vụ 'Thanh toán tiền trọ bằng xác thịt'.",
    "[HỆ THỐNG]: Cảnh báo: Nhu cầu xác thịt của chủ thể quá thấp. Bắt buộc thực hiện nhiệm vụ 'Gieo giống' để tránh hình phạt thiến.",
    "[HỆ THỐNG]: Thông báo: Bạn đã thu thập đủ 'Dâm Dịch' của 5 mỹ nhân hàng xóm. Kích hoạt kỹ năng 'Dương Vật Cấp Thần'.",
    "[HỆ THỐNG]: Cảnh báo: Mục tiêu 'Nữ sinh phòng 302' đang trong trạng thái phát tình cực độ. Hãy đến cứu trợ bằng dương vật ngay.",
    "Dị năng 'Dịch Chuyển' giúp bạn lẻn vào giường của bất kỳ mỹ nhân nào trong dãy trọ mỗi đêm mà không để lại bất kỳ dấu vết nào.",
    "Sở hữu dị năng 'Tăng Trưởng Kích Thước', dương vật bạn trở nên vĩ đại khiến mọi cô gái trong nhà thuê đều phải lạy lục van xin.",
    "Dị năng 'Đọc Suy Nghĩ' giúp bạn biết rõ khao khát bị nam giới cưỡng hiếp thầm kín của cô hàng xóm lạnh lùng nhất ngay lúc này."
  ],
  "Ở ghép": [
    "Sống cùng 5 cô gái lạ trong ngôi nhà thuê ở ghép.",
    "Cô bạn cùng phòng nhờ bạn kéo hộ khóa kéo sau lưng chiếc váy dạ hội bó sát.",
    "Vô tình thấy bạn cùng phòng đang quấn khăn tắm bước ra từ phòng vệ sinh.",
    "Cô bạn cùng phòng nhờ bạn sấy tóc hộ, mùi hương dầu gội làm bạn ngây ngất.",
    "Vô tình chạm vào bầu ngực của bạn cùng phòng khi cả hai cùng chen chúc trong bếp.",
    "Bạn và cô bạn cùng phòng cùng nằm trên giường xem phim, không gian trở nên chật hẹp.",
    "Bạn cùng phòng bị đổ cà phê lên váy, phải cởi ra ngay trước mặt bạn để đi giặt.",
    "Bạn cùng phòng bị kẹt trong phòng tắm vì cửa bị hỏng, bạn phải phá cửa vào cứu.",
    "Cô bạn cùng phòng bị trượt chân ngã vào người bạn, cả hai cùng ngã xuống giường.",
    "Cô bạn cùng phòng lén lấy áo sơ mi của bạn mặc để cảm nhận mùi hương của bạn.",
    "Bạn cùng phòng bị kẹt trong phòng tắm vì cửa hỏng, bạn phải phá cửa vào và thấy nàng đang khỏa thân.",
    "Đang ngủ thì cô bạn cùng phòng mộng du leo lên giường ôm chặt lấy bạn như một con gấu bông.",
    "Cả hai cùng uống say sau buổi tiệc, cô bạn cùng phòng chủ động tấn công đôi môi của bạn nồng cháy.",
    "Trò chơi 'thật hay thách' khiến cô bạn cùng phòng phải cởi bỏ toàn bộ nội y ngay trước mắt bạn.",    "[HỆ THỐNG]: Nhiệm vụ: Khiến bạn cùng phòng chủ động ôm bạn từ phía sau. Phần thưởng: 50 điểm tình cảm.",
    "[HỆ THỐNG]: Cảnh báo: Bạn cùng phòng đang cảm thấy cô đơn. Hãy thực hiện hành động an ủi.",
    "[HỆ THỐNG]: Thông báo: Bạn đã đạt mức độ thân thiết 'Tri Kỷ' với bạn cùng phòng.",
    "Dị năng 'Đọc Suy Nghĩ' giúp bạn biết rõ những khao khát thầm kín của bạn cùng phòng.",

  ],
  "Chung cư": [
    "Tôi kí hợp đồng để trở thành quản lý của chung cư toàn nữ sống. Hợp đồng yêu cầu tôi phải làm tình với từng đối tượng được đưa ra",
    "Bạn lén nhìn qua ống nhòm thấy cô gái tòa nhà đối diện đang khỏa thân tắm nắng.",
    "[HỆ THỐNG]: Nhiệm vụ: Trở thành 'Người tình bí mật' của 3 quý bà trong chung cư. Phần thưởng: Thẻ cư dân VIP.",
    "Dị năng 'Thấu Thị Lượng Tử' giúp bạn nhìn xuyên qua mọi bức tường trong chung cư.",
    "Dị năng 'Dịch Chuyển Tức Thời' giúp bạn lẻn vào bất kỳ căn hộ nào chỉ trong chớp mắt.",
  ],
  "Trường cấp 3": [
    "Tôi trở thành hiệu trưởng và thi hành chính sách mới dành riêng cho các nữ sinh.",
    "Chuyến đi cắm trại cấp 3 đầy vú và lồn xinh tươi.",
    "Bắt gặp cô giáo xinh đẹp đang tắm sau khi bơi, tôi chụp ảnh lại và bị cô phát hiện, cô bắt cởi quần ra cho cô chụp ảnh cu.",
    "Quy tắc mới, các học sinh phải cởi bỏ váy, quần, quần lót rồi mới được vào lớp.",
    "Lớp học dạy và thực hành làm tình an toàn.",
    "[HỆ THỐNG]: Nhiệm vụ: Trở thành 'Nam thần học đường' trong mắt toàn bộ nữ sinh. Phần thưởng: Kỹ năng 'Thuyết phục'.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp đồng phục của mọi nữ sinh để chiêm ngưỡng vùng kín.",
  ],
  "Đại học": [
    "Chinh phục các mĩ nhân ở đại học.",
    "[HỆ THỐNG]: Cảnh báo: Hoa khôi của trường đang bị một đám nam sinh quấy rối. Hãy đến cứu mỹ nhân.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa quyền truy cập vào hồ sơ cá nhân của mọi sinh viên nữ.",
    "Dị năng 'Đọc Suy Nghĩ' giúp bạn biết rõ những khao khát xác thịt thầm kín của bất kỳ nữ sinh nào.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp quần áo của mọi mỹ nhân trong trường đại học.",
    "Dị năng 'Thao Túng Cảm Xúc' khiến bất kỳ cô gái nào nhìn thấy bạn cũng đều cảm thấy hưng phấn."
  ],
  "Học viện nữ sinh": [
    "Tôi được chọn làm mẫu khỏa thân cho các nữ sinh vẽ.",
    "Lớp học về nam giới của trường nữ sinh.",
    "Bạn bước vào phòng nghệ thuật và thấy một nữ sinh đang khỏa thân làm mẫu cho lớp vẽ.",
    "[HỆ THỐNG]: Nhiệm vụ: Trở thành 'Chủ nhân' thực sự của toàn bộ nữ sinh trong học viện. Phần thưởng: Quyền năng tối thượng.",
    "[HỆ THỐNG]: Cảnh báo: Một nhóm nữ sinh đang có ý định 'thử thách' bản lĩnh đàn ông của bạn.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp đồng phục kín đáo của mọi mỹ nhân học viện.",
    "Dị năng 'Tăng Trưởng Kích Thước' khiến dương vật bạn trở nên vĩ đại, phá nát mọi ranh giới đạo đức."
  ],
  "Bệnh viện": [
    "Bệnh viện chuyên chữa bệnh cho nam giới bằng tình dục, các nữ bác sĩ và nữ y tá chỉ làm mọi thứ để giúp đỡ bệnh nhân, hoàn toàn không hề dâm đãng.",
    "Bệnh viện chuyên chữa bệnh về sinh lí, tình dục cho nam giới, các nữ bác sĩ và nữ y tá chỉ làm mọi thứ để giúp đỡ bệnh nhân, hoàn toàn không hề dâm đãng.",
    "Bệnh viện dâm đãng, mọi người đụ nhau ở mọi nơi, mọi lúc.",
  ],
  "Phòng làm việc": [
    "Nàng thư ký điên cuồng yêu tổng giám đốc là tôi.",
    "Cô nàng thực tập sinh lén rủ bạn vào phòng kho để 'tâm sự' riêng tư sau giờ làm.",
    "[HỆ THỐNG]: Nhiệm vụ: Khiến nữ giám đốc chủ động mời bạn đi ăn tối. Phần thưởng: 200 điểm mị lực.",
    "[HỆ THỐNG]: Cảnh báo: Nàng thư ký đang có ý định 'quyến rũ' bạn để thăng tiến.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp áo sơ mi của mọi nữ đồng nghiệp.",
    "Dị năng 'Đọc Suy Nghĩ' giúp bạn biết rõ những dục vọng thầm kín của sếp nữ dành cho bạn.",
  ],
  "Phòng gym": [
    "Mỹ nhân yoga lén rủ bạn vào phòng tập vắng vẻ để 'tâm sự' riêng tư sau giờ tập.",
    "[HỆ THỐNG]: Cảnh báo: Nữ huấn luyện viên đang có ý định 'thử thách' thể lực của bạn.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp quần tập spandex của mọi mỹ nhân.",
    "Dị năng 'Cường Hóa Vật Lý' khiến dương vật bạn trở nên cứng ngắc như kim cương.",
  ],
  "Công Ty giải trí": [
    "Công việc tìm kiếm tài năng mới.",
    "1 ngày làm việc của Giám đốc quản lí tài năng.",
    "[HỆ THỐNG]: Cảnh báo: Nàng idol đang có ý định 'quyến rũ' bạn để được ra mắt sớm.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp váy dạ hội của mọi nữ minh tinh.",
    "Dị năng 'Đọc Suy Nghĩ' giúp bạn biết rõ những dục vọng thầm kín của nàng ca sĩ dành cho bạn.",
  ],
  "Trường quay AV": [
    "Buổi chụp ảnh nóng cuồng nhiệt.",
    "Buổi tuyển chọn nữ diễn viên AV mới.",
    "Nàng diễn viên chính lén rủ bạn vào phòng nghỉ vắng vẻ để 'tâm sự' riêng tư.",
    "[HỆ THỐNG]: Cảnh báo: Nàng diễn viên tân binh đang có ý định 'quyến rũ' bạn để được đóng chính.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp đồ lót gợi cảm của mọi nữ diễn viên.",
    "Dị năng 'Tăng Trưởng Kích Thước' khiến dương vật bạn trở nên vĩ đại, phá nát mọi ranh giới.",
  ],
  "Biệt thự": [
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp váy lụa của mọi phu nhân hào môn.",
    "Dị năng 'Tăng Trưởng Kích Thước' khiến dương vật bạn trở nên vĩ đại, phá nát mọi ranh giới."
  ],
  "Penhouse": [
    "Dị năng 'Thấu Thị Lượng Tử' giúp bạn nhìn xuyên qua lớp váy lụa của mọi mỹ nhân Penthouse.",
    "Dị năng 'Tăng Trưởng Kích Thước' khiến dương vật bạn trở nên vĩ đại, phá nát mọi ranh giới."
  ],
  "Trên chuyến xe đường dài": [
    "Ngồi cạnh cô gái đang nứng trên chuyến xe đường dài.",
    "Ngồi cạnh cô gái trên chuyến xe, cả 2 phát hiện cặp đôi phía sau đang lén lút làm tình.",
    "Ngồi cạnh chị gái xinh đẹp trên chuyến xe.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp quần áo của mọi nữ hành khách trên xe.",
    "Dị năng 'Đọc Suy Nghĩ' giúp bạn biết rõ những dục vọng thầm kín của cô nàng sinh viên.",
  ],
  "Trên tàu điện": [
    "Vô tình chạm tay vào nữ hành khách khi cả hai cùng nắm lấy tay vịn trên tàu.",
    "Nữ nhân viên tàu lén rủ bạn vào khoang nghỉ vắng vẻ để 'tâm sự' riêng tư sau ca làm.",
    "[HỆ THỐNG]: Cảnh báo: Nữ nhân viên tàu đang có ý định 'quyến rũ' bạn để được giúp đỡ.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp quần áo của mọi nữ hành khách trên tàu.",
    "Dị năng 'Đọc Suy Nghĩ' giúp bạn biết rõ những dục vọng thầm kín của cô nàng công sở.",
  ],
  "Hệ Thống Làm Giàu Đô Thị": [
    "Bạn nhận được 'Hệ thống Thần Hào', mỗi giây trôi qua tài khoản của bạn lại tăng thêm một số tiền khổng lồ.",
    "Hệ thống yêu cầu bạn phải tiêu hết 100 tỷ trong vòng một tuần để nhận được phần thưởng là một tập đoàn đa quốc gia.",
    "Bạn dùng số tiền vô hạn từ hệ thống để mua lại toàn bộ khu phố nơi những mỹ nhân đang sinh sống, trở thành chủ nhân của họ.",
    "Hệ thống 'Liếm Cẩu' giúp bạn nhận được gấp 10 lần số tiền đã chi cho các mỹ nhân, khiến bạn trở thành tỷ phú chỉ sau một đêm.",
    "[HỆ THỐNG]: Thông báo: Số dư tài khoản của bạn đã vượt mức 1000 tỷ. Kích hoạt kỹ năng 'Tiền Đè Chết Người'.",
  ],
  "Dị Năng Đổi Đời Đô Thị": [
    "Dị năng 'Thấu Thị' giúp bạn nhìn thấu mọi biểu đồ chứng khoán và kết quả xổ số, mang lại sự giàu sang tột đỉnh.",
    "Bạn dùng dị năng 'Điều khiển tâm trí' để khiến các đại gia bất động sản phải dâng hiến toàn bộ tài sản cho mình.",
    "Dị năng 'Dịch chuyển' giúp bạn lấy đi những kho báu bị lãng quên dưới lòng đất, đổi đời chỉ trong chớp mắt.",
    "Bạn dùng sức mạnh của mình để thâu tóm mọi nguồn lực kinh tế, biến những mỹ nhân kiêu ngạo nhất thành nô lệ của đồng tiền.",
    "[HỆ THỐNG]: Cảnh báo: Bạn đang sở hữu quá nhiều tài sản. Hãy dùng tiền để mở rộng hậu cung ngay.",
  ],
  "Phim Ngắn Trung Quốc (Short Dramas)": [
    "Bạn là 'Chiến Thần' lừng danh vừa giải ngũ, trở về quê nhà và phát hiện vợ mình đang bị đám thiếu gia địa phương quấy rối, bạn quyết định dùng sức mạnh để 'trừng phạt' chúng và chiếm hữu các mỹ nữ đi cùng.",
    "Bạn là một 'Tổng Tài' lạnh lùng bị gia đình ép cưới một cô gái nghèo, nhưng đêm tân hôn bạn phát hiện nàng thực chất là một tuyệt thế mỹ nhân với cơ thể dâm mị.",
    "Bạn đóng giả làm một anh chàng shipper nghèo để thử lòng vị hôn thê kiêu ngạo, nhưng lại tình cờ cứu được nữ chủ tịch tập đoàn đối thủ và được nàng 'đền ơn' bằng thể xác.",
    "Bạn là một 'Rể Quý' bị nhà vợ khinh rẻ, cho đến khi thân phận tỷ phú của bạn bị bại lộ, khiến mẹ vợ và em vợ phải quỳ xuống cầu xin sự tha thứ bằng cách phục vụ tình dục.",
    "Bạn trọng sinh trở lại thời điểm trước khi bị bạn gái phản bội, dùng kiến thức tương lai để làm giàu và biến cô bạn gái cũ cùng đám bạn của cô ta thành nô lệ tình dục.",
    "Bối cảnh 'Hợp Đồng Hôn Nhân' nơi bạn và nữ giám đốc xinh đẹp phải đóng giả vợ chồng, nhưng những quy tắc trong hợp đồng dần biến thành những cuộc mây mưa nóng bỏng.",
    "Bạn bị ép cưới một cô gái xấu xí để gán nợ, nhưng đêm tân hôn phát hiện nàng là một mỹ nhân tuyệt sắc đang giả dạng để trốn tránh kẻ thù.",
    "Vợ cũ khinh thường bạn nghèo nên ly hôn, sau đó nàng phát hiện bạn là người thừa kế duy nhất của tập đoàn nghìn tỷ và quỳ xuống cầu xin quay lại.",
    "Bạn đi xem mắt nhầm phòng và kết hôn chớp nhoáng với một cô gái xa lạ, không ngờ nàng lại là nữ chủ tịch tập đoàn nơi bạn đang làm việc.",
    "Bạn đóng giả làm một vệ sĩ nghèo để bảo vệ tiểu thư tập đoàn, nhưng thực chất bạn là 'Vua Sát Thủ' lừng danh thế giới ngầm.",
    "Bạn là một đầu bếp thiên tài ẩn danh, làm việc tại một quán ăn nhỏ, nhưng thực chất bạn là 'Vua Đầu Bếp' thế giới, người mà các nữ chủ tịch tập đoàn thực phẩm luôn khao khát mời về.",
    "Bạn bị mất trí nhớ và được một cô gái nghèo cứu giúp, sau khi hồi phục trí nhớ, bạn phát hiện mình là người đứng đầu gia tộc giàu nhất nước và quyết định đền đáp cô gái đó bằng cả gia sản và thể xác.",
    "Bối cảnh 'Chị Gái Thế Thân' nơi bạn bị ép cưới cô em gái đanh đá nhưng thực chất người bạn yêu là cô chị gái hiền lành, bạn quyết định dùng quyền lực để chiếm hữu cả hai.",
    "Bạn là một giáo viên bình thường tại trường quý tộc, nhưng thực chất là 'Giáo Quan' của lực lượng đặc nhiệm, người khiến các tiểu thư ngỗ nghịch phải phục tùng tuyệt đối.",
    "Bạn trọng sinh về quá khứ, quyết định cưới mẹ của kẻ thù truyền kiếp để trở thành cha dượng của hắn, dùng thân phận mới để hành hạ và chiếm hữu những gì hắn yêu quý nhất.",
    "Bạn là một shipper bình thường nhưng sở hữu 'Hệ Thống Vạn Giới Giao Hàng', mỗi khi giao hàng đến các thế giới khác nhau, bạn nhận được những bảo vật và mỹ nhân từ nơi đó.",
    "Bạn là một đặc công giải ngũ xuyên không về hiện đại làm bảo vệ tại một trường nữ sinh quý tộc, dùng kỹ năng chiến đấu để bảo vệ và thu phục các hoa khôi kiêu kỳ.",
    "Bạn sở hữu 'Hệ Thống Livestream Vạn Giới', những người xem livestream của bạn là các vị thần tiên, họ tặng bạn những phần quà là kỹ năng tán gái và thuốc kích dục thần cấp.",
    "Bạn trọng sinh thành một tên liếm cẩu (simp) vừa bị nữ thần từ chối, nhưng lần này bạn có 'Hệ Thống Nghịch Chuyển', mỗi khi bạn phớt lờ hoặc làm nhục nữ thần, bạn sẽ nhận được tiền và mị lực.",
    "Bạn sở hữu 'Hệ Thống Vạn Giới Mua Sắm', có thể dùng tiền để mua những món đồ công nghệ tương lai hoặc thuốc thần từ các thế giới khác để vả mặt đám thiếu gia.",
    "Bạn là một bác sĩ thực tập vô tình nhận được 'Hệ Thống Thần Y Vạn Giới', có thể nhìn thấu mọi căn bệnh và cách chữa trị chỉ bằng một cái nhìn, khiến các nữ chủ tịch phải quỳ lạy van xin.",
    "Bạn trọng sinh trở lại ngày bị đuổi khỏi gia tộc, lần này bạn sở hữu 'Hệ Thống Đầu Tư Thần Cấp', biết trước mọi biến động thị trường và thâu tóm toàn bộ kinh tế thành phố.",
    "Bạn là một nhân viên giao hàng bình thường, tình cờ nhận được 'Hệ Thống Quay Thưởng Hằng Ngày', mỗi lần quay trúng bạn sẽ nhận được một thân phận mới: từ tỷ phú, thần y đến vua đầu bếp, khiến các mỹ nhân phải kinh ngạc.",
    "Bạn trọng sinh về năm 20 tuổi, lúc gia đình chưa phá sản, dùng kiến thức tương lai để cứu vãn tập đoàn và biến những kẻ từng khinh rẻ mình thành nô lệ, đặc biệt là cô tiểu thư kiêu ngạo đã hủy hôn.",
    "Bạn sở hữu 'Hệ Thống Thần Hào Ẩn Danh', mỗi khi bạn bị người khác khinh bỉ vì nghèo khó, hệ thống sẽ tự động nạp vào tài khoản của bạn số tiền gấp 1000 lần tài sản của kẻ đó.",
    "Bạn trọng sinh về thời học sinh với 'Hệ Thống Học Thần', mỗi khi bạn đạt điểm cao hoặc giải được bài toán khó, bạn sẽ nhận được điểm mị lực và sự chú ý của các nữ thần học đường.",
    "Bạn sở hữu 'Hệ Thống Mô Phỏng Cuộc Đời', có thể thử nghiệm hàng ngàn lựa chọn khác nhau trước khi quyết định trong thực tế, giúp bạn luôn đi trước các đối thủ một bước và chiếm trọn trái tim mỹ nhân.",
    "Bạn xuyên không vào một cuốn tiểu thuyết đô thị làm nhân vật phản diện giàu có nhưng đoản mệnh, sở hữu 'Hệ Thống Nghịch Chuyển Vận Mệnh', nhiệm vụ của bạn là cướp đi hào quang và dàn hậu cung của nam chính.",
    "[HỆ THỐNG]: Nhiệm vụ: Thực hiện màn 'Vả Mặt' (Face-slapping) đám thiếu gia hống hách và thu phục nữ chính. Phần thưởng: 1000 tỷ đồng.",
    "[HỆ THỐNG]: Thông báo: Thân phận 'Long Chủ' của bạn đã được kích hoạt. Mọi mỹ nhân trong thành phố đều phải quỳ phục.",
  ],
  "Nữ Chủ Đô Thị (Low NSFW/Lesbian)": [
    "Bạn là một nữ tổng tài kiêu sa, sở hữu 'Hệ Thống Nữ Vương', nhiệm vụ của bạn là chinh phục trái tim của những nàng thư ký và đối thủ xinh đẹp nhất.",
    "Trong một trường đại học danh giá, bạn là hoa khôi lạnh lùng, dùng mị lực thiên bẩm để khiến các nữ sinh khác phải thầm thương trộm nhớ.",
    "Bạn là một nữ thám tử tư tài năng, tình cờ bắt gặp nàng tiểu thư nhà giàu đang gặp rắc rối, cả hai cùng nhau trải qua những giây phút mạo hiểm và thân mật.",
    "Dị năng 'Mị lực nữ giới' khiến mọi phụ nữ trong thành phố đều cảm thấy bị thu hút bởi bạn, sẵn sàng dâng hiến tình cảm và thể xác cho bạn.",
    "Tại một buổi tiệc thượng lưu, bạn và nàng đối thủ kinh doanh bị kẹt trong thang máy, không khí nóng bỏng khiến cả hai không thể kìm lòng mà trao nhau nụ hôn nồng cháy.",
    "Bạn sở hữu một hệ thống 'Nữ Chủ Harem', giúp bạn thu phục những mỹ nhân đô thị mạnh mẽ và quyến rũ nhất vào hậu cung của mình.",
    "Là một nữ bác sĩ xinh đẹp, bạn dùng sự tận tâm và kỹ năng của mình để chăm sóc và chiếm hữu trái tim của những nàng bệnh nhân xinh đẹp.",
    "Bạn là một nữ huấn luyện viên thể hình, chuyên hướng dẫn cho các quý bà và tiểu thư, dùng sự cọ xát cơ thể để khơi dậy dục vọng thầm kín của họ.",
    "Trong một thế giới đô thị hiện đại, bạn là nữ vương của thế giới ngầm, sở hữu dàn mỹ nữ vệ sĩ trung thành và sẵn sàng phục vụ mọi nhu cầu của bạn.",
    "Hệ thống 'Nữ Chủ Chinh Phục' giao nhiệm vụ cho bạn phải thu phục trái tim của 5 nàng hoa khôi ở các trường đại học khác nhau.",
  ],
  "Hành Trình Tự Do Đô Thị (Gender Neutral - SFW)": [
    "Bạn là một nhiếp ảnh gia đường phố, đi khắp thành phố để ghi lại những khoảnh khắc đời thường đầy ý nghĩa và vẻ đẹp ẩn giấu của con người.",
    "Trong một thành phố nhộn nhịp, bạn sở hữu một tiệm sách cũ nhỏ, nơi đón tiếp những tâm hồn đồng điệu và chia sẻ những câu chuyện về cuộc sống.",
    "Bạn là một kiến trúc sư trẻ, đang nỗ lực thiết kế những công trình xanh để mang lại không gian sống tốt đẹp hơn cho cộng đồng.",
    "Bạn là một nghệ sĩ graffiti, dùng những bức tranh tường đầy màu sắc để truyền tải thông điệp về hy vọng và sự tự do cho cư dân thành phố.",
    "Bạn sở hữu một quán cà phê thú cưng, nơi mọi người có thể tìm thấy sự bình yên và niềm vui bên những người bạn nhỏ đáng yêu.",
  ],
};

export const IDENTITIES: string[] = Object.entries(RAW_DATA).flatMap(([context, scenarios]) => 
  scenarios.map(s => `Bối cảnh: ${context} - ${s}`)
);

export const SPECIALIZED_DATA: Record<string, { label: string, action: string }[]> = {};
