
export const RAW_DATA: Record<string, string[]> = {
  "Hệ thống": [
    "Hệ Thống gánh con.",

  ],
  "Trạm Không Gian": [
    "Bạn là kỹ sư bảo trì trên trạm ISS-2099, vô tình bắt gặp nữ chỉ huy đang tự sướng trong môi trường không trọng lực, những giọt dâm thủy lơ lửng như những viên pha lê.",
    "Hệ thống AI của trạm bị nhiễm virus 'Eros', nó khóa chặt bạn và nữ bác sĩ tâm lý trong phòng khử trùng và bắt đầu bơm khí kích dục.",
    "Nữ người máy sinh học (Android) thế hệ mới nhất đang yêu cầu bạn 'kiểm tra phần cứng' vùng kín để đảm bảo khả năng mô phỏng cảm xúc con người.",
    "Trong lúc sửa chữa tấm pin mặt trời, bạn và nữ phi hành gia bị kẹt bên ngoài không gian, bộ đồ bảo hộ của cả hai vô tình kết nối cổng truyền cảm giác.",
    "[HỆ THỐNG]: Nhiệm vụ: Thiết lập kết nối thần kinh với Nữ Hoàng Cyborg. Phần thưởng: Quyền truy cập mạng lưới toàn cầu.",
  ],
  "Thành Phố Cyberpunk": [
    "Dưới ánh đèn neon nhấp nháy của Neo-Saigon, bạn cứu một nữ hacker khỏi sự truy đuổi của tập đoàn Arasaka, nàng đền đáp bằng một đêm 'nâng cấp phần mềm' nóng bỏng.",
    "Bạn sở hữu một con chip 'Dâm Dục' bất hợp pháp, có thể khiến bất kỳ ai trong tầm mắt rơi vào trạng thái phát tình ngay lập tức.",
    "Nữ cảnh sát đặc nhiệm bắt quả tang bạn đang buôn lậu nội tạng nhân tạo, nàng ép bạn phải dùng 'cây gậy' thịt của mình để hối lộ.",
    "Trong quán bar 'Electric Love', bạn gặp một cô gái có đôi mắt điện tử đầy mê hoặc, nàng muốn thử nghiệm cảm giác làm tình với một con người thuần khiết.",
    "[HỆ THỐNG]: Cảnh báo: Mức độ hưng phấn của nữ sát thủ đang đạt đỉnh. Hãy sử dụng kỹ năng 'Quá Tải Cảm Xúc'.",
  ],
  "Hành Tinh Lạ": [
    "Tàu vũ trụ của bạn rơi xuống hành tinh Amazonia, nơi chỉ có những nữ chiến binh cao lớn và dâm đãng, họ coi bạn là 'hạt giống' quý hiếm.",
    "Bạn bị bộ tộc người ngoài hành tinh bắt giữ, nữ tư tế tối cao muốn dùng tinh dịch của bạn để hiến tế cho thần linh của họ.",
    "Loài thực vật kỳ lạ trên hành tinh này tiết ra phấn hoa khiến bạn và nữ đồng nghiệp mất kiểm soát, lao vào nhau như những con thú hoang.",
    "Nữ hoàng của hành tinh băng giá muốn bạn sưởi ấm cơ thể nàng bằng hơi ấm từ những cuộc mây mưa bất tận.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa danh hiệu 'Kẻ Chinh Phục Tinh Hệ'.",
  ],
  "Hệ Thống Làm Giàu Tương Lai": [
    "Bạn sở hữu 'Hệ Thống Khai Thác Tài Nguyên Vũ Trụ', có thể dùng robot để đào vàng và kim cương từ các tiểu hành tinh.",
    "Hệ thống tặng bạn một 'Tập Đoàn Công Nghệ Toàn Cầu', giúp bạn nắm giữ mọi bí mật và tài sản của nhân loại.",
    "Bạn dùng số tiền vô hạn để mua lại các trạm không gian và hành tinh mới, biến các nữ chỉ huy thành người phục vụ cho mình.",
    "Hệ thống 'Giao Dịch Thiên Hà' giúp bạn nhận được phản hồi tiền tệ gấp 100 lần khi đầu tư vào các dự án của mỹ nhân.",
    "[HỆ THỐNG]: Thông báo: Bạn đã trở thành tỷ phú liên hành tinh. Kích hoạt kỹ năng 'Thao Túng Thị Trường Vũ Trụ'.",
  ],
  "Dị Năng Đổi Đời Cyberpunk": [
    "Dị năng 'Hack tài khoản vạn giới' giúp bạn sở hữu nguồn tài chính vô tận, khiến mọi nữ hacker phải quỳ lạy xin được hợp tác.",
    "Bạn dùng dị năng 'Thao túng dữ liệu' để khiến các tập đoàn lớn phải dâng hiến toàn bộ ngân khố và nữ giám đốc cho mình.",
    "Dị năng 'Tạo ra vật chất nano' giúp bạn có mọi thứ mình muốn, từ phi thuyền đến những món quà công nghệ đắt giá.",
    "Bạn dùng sức mạnh của mình để thâu tóm mọi nguồn lực năng lượng trong thế giới tương lai, biến những nữ minh tinh thành nô lệ.",
    "[HỆ THỐNG]: Cảnh báo: Sự giàu sang của bạn đang bị các nữ thám tử dòm ngó. Hãy dùng tiền để mua chuộc họ ngay.",
  ],
  "Hậu Tận Thế (Fallout Style)": [
    "Bạn là một cư dân bước ra từ Vault 69, nơi chỉ có bạn là nam nhân duy nhất giữa hàng trăm phụ nữ khao khát duy trì nòi giống.",
    "Nữ thủ lĩnh của băng cướp Raider bắt được bạn, nàng muốn dùng bạn làm 'nô lệ tình dục' để giải tỏa sau những trận chiến đẫm máu vùng Wasteland.",
    "Bạn tìm thấy một nữ Android bị hỏng trong đống đổ nát, sau khi sửa chữa, nàng thề sẽ phục vụ mọi nhu cầu của 'chủ nhân' cứu mạng.",
    "Trong một thị trấn đổ nát, bạn và một nữ bác sĩ cùng trú ẩn khỏi cơn mưa phóng xạ, hơi ấm cơ thể là thứ duy nhất giúp cả hai sống sót.",
    "[HỆ THỐNG]: Thông báo: Bạn nhận được kỹ năng 'Kháng Phóng Xạ'. Phần thưởng: Tăng cường sinh lực bền bỉ.",
  ],
  "Đại Dịch Zombie (The Walking Dead Style)": [
    "Bạn và một nhóm nữ sinh bị kẹt trong một trung tâm thương mại đầy rẫy thây ma, sự sợ hãi tột cùng khiến bản năng nguyên thủy bùng phát.",
    "Nữ cảnh sát kiên cường bị thương khi bảo vệ bạn, trong căn hầm tối, nàng yêu cầu bạn giúp nàng 'quên đi cái chết' bằng những khoảnh khắc nồng cháy.",
    "Bạn sở hữu một loại kháng thể đặc biệt trong tinh dịch, khiến các nữ chiến binh phải tranh giành để được 'tiêm chủng' trực tiếp từ bạn.",
    "Trong trại tị nạn khắc nghiệt, bạn dùng thức ăn và sự bảo vệ để đổi lấy sự phục tùng của những người vợ của các thủ lĩnh đã khuất.",
    "[HỆ THỐNG]: Nhiệm vụ: Xây dựng hậu cung trong thời tận thế. Phần thưởng: Kỹ năng 'Thống Trị Kẻ Sống Sót'.",
  ],
  "Đảo Kinh Hoàng (Dead Island Style)": [
    "Kỳ nghỉ dưỡng trên hòn đảo thiên đường biến thành ác mộng, bạn và cô nàng DJ nóng bỏng cùng cố gắng thoát khỏi khách sạn đầy xác sống.",
    "Nữ vệ sĩ của một tỷ phú bị kẹt lại trên bãi biển, nàng thề sẽ dâng hiến tất cả nếu bạn giúp nàng tìm đường về đất liền.",
    "Bạn tìm thấy một loại 'thuốc tăng lực' kỳ lạ trên đảo, nó không chỉ giúp bạn mạnh mẽ hơn mà còn khiến ham muốn của bạn trở nên điên cuồng.",
    "Dưới ánh trăng nhiệt đới, bạn và một nữ du khách xinh đẹp cùng tận hưởng những giây phút cuối cùng trước khi lũ zombie phá cửa xông vào.",
    "[HỆ THỐNG]: Cảnh báo: Adrenaline đang tăng cao. Kích hoạt chế độ 'Cuồng Nộ Dục Vọng'.",
  ],
  "Tương Lai Cyberpunk 2077": [
    "Bạn là một lính đánh thuê tại Night City, nhận nhiệm vụ bảo vệ một nữ ca sĩ ảo (Braindance star) và bị nàng lôi kéo vào thế giới ảo đầy trụy lạc.",
    "Nữ giám đốc điều hành của tập đoàn Militech muốn 'thuê' bạn làm vệ sĩ riêng kiêm bạn tình để thỏa mãn những sở thích quái đản của nàng.",
    "Bạn sở hữu một con chip chứa nhân cách của một 'huyền thoại' dâm đãng, hắn ta liên tục thì thầm vào tai bạn những cách để chinh phục phụ nữ.",
    "Trong một căn hộ cao cấp nhìn ra toàn cảnh thành phố neon, bạn và một nữ Netrunner cùng đắm chìm trong sự kết hợp giữa xác thịt và dữ liệu số.",
    "[HỆ THỐNG]: Thông báo: Bạn đã trở thành 'Huyền Thoại Night City'. Kỹ năng mới: 'Hack Thần Kinh Kích Dục'.",
  ],
  "Vũ Trụ Warhammer 40k": [
    "Bạn là một chiến binh Imperial Guard may mắn sống sót, bị lạc vào một hành tinh nơi các Sister of Battle đang thanh tẩy quân thù.",
    "Nữ Inquisitor nghi ngờ bạn bị nhiễm hỗn mang (Chaos), nàng quyết định 'thẩm vấn' bạn bằng những phương pháp tra tấn thể xác đầy khoái lạc.",
    "Một nữ Eldar xinh đẹp bị thương và rơi vào tay bạn, nàng thề sẽ phục vụ bạn nếu bạn giúp nàng thoát khỏi sự săn đuổi của lũ quỷ Slaanesh.",
    "Trong hầm ngầm của một Hive City u tối, bạn và một nữ công nhân cùng tìm thấy niềm an ủi duy nhất giữa cuộc chiến vô tận của thiên niên kỷ thứ 41.",
    "[HỆ THỐNG]: Lời thề: Vì Hoàng Đế! Nhiệm vụ: Thanh tẩy dục vọng bằng sự chinh phục.",
  ],
  "Thế Giới NieR:Automata": [
    "Bạn là một con người hiếm hoi còn sót lại, được hai nữ Android 2B và A2 bảo vệ và chăm sóc như một báu vật vô giá của nhân loại.",
    "Nữ Android 2B bắt đầu nảy sinh những cảm xúc 'lỗi' khi ở gần bạn, nàng muốn khám phá ý nghĩa của việc làm tình mà con người từng thực hiện.",
    "Bạn tìm thấy một trạm quan sát bỏ hoang của con người, nơi chứa đầy những tài liệu về văn hóa phồn thực, và bạn quyết định 'dạy' lại cho các Android.",
    "Trong thế giới hoang tàn của máy móc, bạn và nữ Android Commander cùng thảo luận về tương lai của giống loài thông qua việc kết hợp sinh học.",
    "[HỆ THỐNG]: Thông báo: Kích hoạt giao thức 'Duy Trì Nhân Loại'. Mục tiêu: Tái tạo cảm xúc thông qua xác thịt.",
  ],
  "Thế Giới Khủng Long (Jurassic World)": [
    "Bạn là một huấn luyện viên khủng long mới tại công viên Jurassic World, làm việc trực tiếp dưới quyền của Claire Dearing để thuần hóa loài Indominus Rex.",
    "Hệ thống an ninh của đảo Isla Nublar bị sụp đổ, bạn và nữ giám đốc Claire cùng bị kẹt trong rừng rậm giữa vòng vây của lũ khủng long ăn thịt.",
    "Bạn sở hữu một loại pheromone đặc biệt có thể điều khiển các loài bò sát cổ đại, khiến chúng phục tùng và bảo vệ bạn như một vị vua.",
    "Nữ nhà khoa học di truyền học đang thực hiện những thí nghiệm bí mật để lai tạo DNA người và khủng long, nàng chọn bạn làm 'vật mẫu' nam duy nhất.",
    "[HỆ THỐNG]: Thông báo: Bạn đã trở thành 'Chúa Tể Khủng Long'. Kỹ năng mới: 'Giao Tiếp Thần Kinh Với Siêu Thú'.",
  ],
  "Đấu Trường Ảo (Ready Player One)": [
    "Bạn là một Gunter nghèo khổ sống tại khu nhà Stack, vô tình tìm thấy chiếc chìa khóa đầu tiên trong cuộc săn tìm trứng phục sinh của Halliday.",
    "Trong thế giới ảo OASIS, bạn gặp gỡ nữ game thủ nổi tiếng Art3mis và cùng nàng lập đội để chống lại tập đoàn IOI gian ác.",
    "Bạn sở hữu một vật phẩm cực hiếm có khả năng 'hiện thực hóa' những cảm giác trong game ra ngoài đời thực, khiến mọi nữ game thủ đều khao khát.",
    "Nữ sát thủ của IOI được phái đến để ám sát bạn ngoài đời thực, nhưng nàng lại bị sự thông minh và bản lĩnh của bạn chinh phục.",
    "[HỆ THỐNG]: Chúc mừng! Bạn đã tìm thấy Trứng Phục Sinh. Quyền năng: 'Chủ Nhân Của OASIS'.",
  ],
  "Đấu Trường Công Lý (E-Sports)": [
    "Bạn là một thiên tài Liên Minh Huyền Thoại (LoL) vừa gia nhập đội tuyển chuyên nghiệp, mục tiêu là chinh phục chức vô địch thế giới và trái tim của các nữ game thủ.",
    "Nữ quản lý xinh đẹp của đội tuyển luôn theo sát bạn trong các buổi tập luyện, nàng hứa sẽ 'thưởng nóng' nếu bạn giúp đội giành chiến thắng trong trận chung kết.",
    "Trong một buổi stream muộn, bạn và nữ streamer nổi tiếng cùng leo rank, sự ăn ý trong game dẫn đến những cuộc trò chuyện đầy ẩn ý và kích thích.",
    "Nữ bình luận viên (Caster) quyến rũ của giải đấu luôn dành cho bạn những lời khen có cánh, nàng muốn phỏng vấn riêng bạn tại phòng khách sạn sau trận đấu.",
    "Bạn sở hữu 'Hệ Thống Game Thủ Toàn Năng', giúp bạn có phản xạ siêu phàm và khả năng 'đọc vị' mọi đối thủ, kể cả những khao khát thầm kín của họ.",
    "[HỆ THỐNG]: Nhiệm vụ: Giành chức vô địch thế giới. Phần thưởng: Mở khóa 'Hậu Cung E-Sports'.",
  ],
  "Nữ Đế Tinh Hà": [
    "Bạn là một phi công tự do vô tình cứu được Nữ Hoàng Đế của Đế Chế Tinh Hà khi tàu của nàng bị tấn công bởi phiến quân.",
    "Nữ Đế nổi tiếng với sự uy nghiêm và quyền lực tuyệt đối, nhưng khi ở trong khoang cứu sinh chật hẹp, nàng lại bị sự nam tính của bạn khuất phục.",
    "Bạn dùng công nghệ 'Kết Nối Thần Kinh' để thâm nhập vào tâm trí của Nữ Đế, khám phá ra những khao khát dục vọng thầm kín nhất của nàng.",
    "Nữ Đế muốn bạn làm 'vật mẫu' để tái tạo nòi giống hoàng gia mang gen chiến binh mạnh mẽ nhất, nàng sẵn sàng dâng hiến cơ thể cho bạn.",
    "Dị năng 'Thao Túng Dữ Liệu' giúp bạn nắm giữ mọi bí mật của đế chế, biến Nữ Đế thành một con rối dâm đãng trong tay mình.",
    "[HỆ THỐNG]: Nhiệm vụ: Trở thành 'Nhiếp Chính Vương' của vũ trụ. Phần thưởng: Hậu cung gồm toàn bộ nữ quan đại thần.",
  ],
  "Nữ Đô Đốc Không Gian": [
    "Bạn là một kỹ sư trên hạm đội liên minh, làm việc dưới quyền Nữ Đô Đốc lạnh lùng và quyết đoán.",
    "Trong một nhiệm vụ thám hiểm hành tinh lạ, bạn và Nữ Đô Đốc bị kẹt trong một hang động, hơi ấm cơ thể là thứ duy nhất giúp cả hai sống sót.",
    "Nữ Đô Đốc bị nhiễm một loại virus sinh học khiến ham muốn tăng cao, nàng yêu cầu bạn giúp nàng 'giải độc' ngay lập tức.",
    "Bạn sở hữu 'Hệ Thống Chỉ Huy Tối Cao', giúp bạn nhìn thấu mọi chiến thuật và cả những điểm nhạy cảm trên cơ thể vị Nữ Đô Đốc kiêu hãnh.",
    "Dưới ánh sao mờ ảo của khoang lái, bạn và Nữ Đô Đốc cùng đắm chìm trong sự kết hợp giữa xác thịt và công nghệ tương lai.",
    "[HỆ THỐNG]: Thông báo: Bạn đã thu phục được 'Nữ Thần Chiến Hạm'. Kỹ năng mới: 'Hack Cảm Xúc'.",
  ],
  "Nữ Binh Giả Nam": [
    "Bạn là tân binh trong một đơn vị đặc nhiệm tinh nhuệ, phát hiện ra người bạn cùng phòng tài năng nhất thực chất là một cô gái giả nam.",
    "Nàng giả nam để tham gia quân đội và tìm kiếm người cha mất tích, bạn dùng bí mật này để ép nàng phải 'phục vụ' mình mỗi đêm trong doanh trại.",
    "Trong một buổi huấn luyện cường độ cao, bộ đồ bảo hộ của nàng bị hỏng, để lộ cơ thể phụ nữ săn chắc và quyến rũ khiến bạn phát cuồng.",
    "Nữ binh giả nam bị trúng đạn và cần được sơ cứu khẩn cấp, khi cởi áo nàng ra, bạn đã không thể cưỡng lại vẻ đẹp ngọc ngà đó.",
    "Dị năng 'Quét Sinh Học' giúp bạn thản nhiên ngắm nhìn vùng kín của nàng ẩn sau lớp quân phục dày cộm.",
    "[HỆ THỐNG]: Nhiệm vụ: Bảo vệ bí mật của Nữ Binh và biến nàng thành người phụ nữ của riêng bạn.",
  ],
  "Chiến Tranh Thế Giới Thứ 3 (WWIII)": [
    "Bạn là một người sống sót trong hầm trú ẩn hạt nhân hiện đại nhất, nơi nam giới cực kỳ khan hiếm sau cuộc chiến hạt nhân toàn cầu.",
    "Bạn là phi công lái Mecha chiến đấu thế hệ mới, cùng nữ đồng đội xinh đẹp thực hiện nhiệm vụ cảm tử để ngăn chặn một vụ phóng tên lửa hạt nhân.",
    "Trong đống đổ nát của một thành phố bị tàn phá bởi WWIII, bạn cứu được một nữ sĩ quan địch và quyết định dùng nàng để duy trì nòi giống cho thế giới mới.",
    "Bạn sở hữu 'Hệ Thống Tái Thiết Thế Giới', giúp bạn xây dựng một đế chế mới từ tro tàn của cuộc chiến và thu thập các nữ lãnh đạo tài giỏi nhất.",
    "Nữ hacker thiên tài của phe kháng chiến đang cố gắng xâm nhập vào hệ thống phòng thủ của bạn, nhưng nàng lại bị sự thông minh và bản lĩnh của bạn khuất phục.",
    "[HỆ THỐNG]: Nhiệm vụ: Chấm dứt chiến tranh và trở thành 'Chúa Tể Thế Giới Mới'. Phần thưởng: Hậu cung gồm các nữ tướng quân vạn tộc.",
  ],
  "Thôn Phệ Tinh Không": [
    "Bạn là La Phong, vừa thức tỉnh tinh thần niệm sư sau khi chứng kiến quái thú tấn công căn cứ thị, bắt đầu hành trình chinh phục tinh không.",
    "Bạn là một võ giả tự do vô tình tìm thấy di tích của Vẫn Mặc Tinh, AI Babata yêu cầu bạn phải 'kết nối' với các nữ chiến binh để thu thập năng lượng phục hồi.",
    "Trong trại huấn luyện tinh anh, bạn và nữ sư tỷ Triệu Nhược cùng tham gia thử thách tại khu hoang dã, sự nguy hiểm khiến cả hai xích lại gần nhau.",
    "Nữ hoàng đế của một đế quốc vũ trụ muốn bạn làm phò mã, nàng sẵn sàng dùng cả thiên hà làm sính lễ nếu bạn chinh phục được nàng.",
    "Bạn sở hữu 'Hệ Thống Thôn Phệ', có thể nuốt chửng sức mạnh của đối thủ và biến các nữ cường giả thành nô lệ linh hồn của mình.",
    "[HỆ THỐNG]: Thông báo: Bạn đã đạt cấp độ 'Hành Tinh Cấp'. Kích hoạt kỹ năng 'Thống Trị Không Gian'.",
  ],
  "Nữ Chủ Khoa Huyễn (Low NSFW/Lesbian)": [
    "Bạn là một nữ phi hành gia dũng cảm, sở hữu 'Hệ Thống Nữ Thần Không Gian', nhiệm vụ của bạn là chinh phục trái tim của các nữ đồng nghiệp và người ngoài hành tinh xinh đẹp.",
    "Trong một thành phố Cyberpunk, bạn là nữ hacker siêu hạng, dùng kỹ năng và mị lực để khiến các nữ robot AI và nữ sát thủ phải phục tùng.",
    "Dị năng 'Thao túng công nghệ' giúp bạn dễ dàng chiếm hữu trái tim và thể xác của bất kỳ người phụ nữ nào trong thế giới tương lai.",
    "Bạn là một nữ bác sĩ di truyền học, chuyên nghiên cứu về sự tiến hóa của phụ nữ, dùng sự chăm sóc tận tình để khơi dậy tình cảm nơi các nữ bệnh nhân.",
    "Trong một trạm vũ trụ cô độc, bạn và nàng đối thủ truyền kiếp bị kẹt trong một khoang thoát hiểm, không khí nóng bỏng khiến cả hai nảy sinh tình cảm sâu đậm.",
    "Bạn sở hữu hệ thống 'Nữ Chủ Harem', giúp bạn thu thập những mỹ nhân khoa học viễn tưởng mạnh nhất thiên hà.",
    "Dị năng 'Mị lực nữ giới' khiến mọi phụ nữ trong thế giới tương lai đều cảm thấy bị thu hút bởi bạn, sẵn sàng dâng hiến tất cả cho bạn.",
    "Bạn là một nữ điệp viên liên thiên hà, dùng sắc đẹp và kỹ năng để thâm nhập vào các tổ chức và chiếm hữu các nữ lãnh đạo.",
    "Trong một không gian song song, bạn là nữ vương của một hành tinh chỉ có phụ nữ, đang nỗ lực bảo vệ thần dân khỏi các cuộc xâm lăng của robot.",
    "Hệ thống 'Nữ Chủ Chinh Phục' giao nhiệm vụ cho bạn phải thu phục trái tim của 3 nữ phi công xuất sắc nhất liên minh.",
  ],
  "Hành Trình Tự Do Khoa Huyễn (Gender Neutral - SFW)": [
    "Bạn là một người lữ hành không gian, đi khắp các hệ sao để khám phá vẻ đẹp của vũ trụ và văn hóa của các nền văn minh ngoài trái đất.",
    "Trong một thế giới tương lai, bạn là một người thợ sửa chữa những thiết bị công nghệ cổ đại, mang lại niềm vui cho mọi người từ những điều nhỏ nhặt.",
    "Bạn sở hữu một trạm dừng chân nhỏ trên một tiểu hành tinh, nơi đón tiếp những phi hành gia mệt mỏi và lắng nghe những câu chuyện về các hành tinh xa lạ.",
    "Bạn là một người bảo vệ môi trường sinh thái trên các hành tinh mới, dùng kiến thức của mình để bảo tồn sự cân bằng của tự nhiên.",
    "Bạn là một nhà nghiên cứu về nguồn gốc của sự sống trong vũ trụ, đi khắp thiên hà để tìm kiếm sự thật và hướng tới một tương lai tốt đẹp hơn cho nhân loại.",
  ],
};

export const IDENTITIES: string[] = Object.entries(RAW_DATA).flatMap(([context, scenarios]) => 
  scenarios.map(s => `Bối cảnh: ${context} - ${s}`)
);

export const SPECIALIZED_DATA: Record<string, { label: string, action: string }[]> = {};
