
export const RAW_DATA: Record<string, string[]> = {
  "Linh khí khôi phục": [
    "Tình cờ va chạm với nữ đồng nghiệp trong thang máy, linh khí cộng hưởng làm cả hai cảm thấy hưng phấn lạ thường.",
    "Trong lúc xếp hàng mua cơm, bạn vô tình chạm vào tay nữ sinh, linh lực truyền qua làm nàng đỏ mặt thẹn thùng.",
    "Vô tình nhặt được cuốn sổ tay của nữ giáo sư, bên trong ghi chép những phương pháp tu luyện dâm mị.",
    "Gặp lại bạn cũ ở quán cafe, linh khí khôi phục làm nàng trở nên xinh đẹp và quyến rũ hơn bao giờ hết.",
    "Trong thư viện, bạn vô tình nhìn thấy nữ thủ thư đang lén lút đọc một cuốn bí kíp song tu cổ đại.",
    "Đi dạo trong công viên, bạn tình cờ bắt gặp một nữ tu sĩ đang hấp thụ linh khí buổi sớm trong tư thế gợi cảm.",
    "Vô tình nghe được cuộc trò chuyện bí mật của hai nữ sinh về việc tìm kiếm đối tượng song tu mạnh mẽ.",
    "Trận pháp bảo vệ bị hỏng đưa bạn rơi thẳng vào giường ngủ của nữ tông chủ khi nàng đang khỏa thân.",
    "Thế giới hiện đại nơi linh khí đột ngột quay trở lại, các tòa nhà chọc trời đan xen tháp tu tiên.",
    "Sự phân hóa giàu nghèo dựa trên linh căn, kẻ mạnh có quyền chiếm hữu hàng trăm mỹ nhân làm hậu cung.",
    "Các trường học siêu năng lực mọc lên, nơi nữ sinh cạnh tranh để được các đại năng sủng ái.",
    "Linh khí khôi phục kéo theo yêu nữ dâm đãng từ dị giới, luôn tìm cách mê hoặc đàn ông loài người.",
    "Xã hội nơi đạo đức cũ sụp đổ, nhường chỗ cho luật rừng và săn lùng mỹ nhân mang linh thể hiếm.",
    "Hệ thống pháp luật mới ưu tiên những kẻ có tu vi cao, cho phép họ sở hữu nhiều nô lệ tình dục.",
    "Bối cảnh đô thị hiện đại đầy rẫy những cấm địa linh khí, nơi ẩn chứa những mỹ nhân bị phong ấn.",
    "[HỆ THỐNG]: Nhiệm vụ: Thu thập âm nguyên từ 5 nữ tu cấp cao. Phần thưởng: Kỹ năng 'Vô Hạn Linh Tinh'.",
    "[HỆ THỐNG]: Thông báo: Nồng độ linh khí trong tinh trùng của bạn đạt mức SSS, giúp cải tạo phụ nữ.",
    "[HỆ THỐNG]: Cảnh báo: Nhu cầu song tu của chủ thể ở mức báo động, đề xuất tìm đối tượng xả năng lượng.",
    "Sở hữu dị năng 'Linh Nhãn', bạn nhìn thấu mọi điểm nhạy cảm và dòng chảy dục vọng trên cơ thể phụ nữ.",
  ],
  "Nam Nữ hoán đổi vai trò": [
    "Thế giới nơi phụ nữ và đàn ông hoán đổi vai trò cho nhau, phụ nữ trở thành phái mạnh và gánh vác tránh nhiệm trụ cột, đàn ông trở thành phái yếu và nhận sự bảo vệ của phụ nữ.",
    "Vô tình đi nhầm vào văn phòng của nữ chủ tịch, nàng thản nhiên yêu cầu bạn cởi đồ để nàng 'kiểm tra sức khỏe'.",
    "Ngồi cạnh một nữ sinh trên tàu điện, nàng vô tình chạm vào đùi bạn và không có ý định rời tay đi.",
    "Thế giới nơi phụ nữ nắm mọi quyền lực chính trị và kinh tế, còn đàn ông chỉ là những món đồ trang trí.",
    "Quy tắc xã hội mới: Phụ nữ phải chủ động theo đuổi và chu cấp cho đàn ông, nhưng bạn chọn cách ngược lại.",
    "Bối cảnh đô thị hiện đại đầy rẫy định kiến giới tính bị đảo ngược hoàn toàn so với lịch sử loài người.",
    "Bối cảnh xã hội nơi việc đàn ông có nhiều vợ là điều hiển nhiên và được pháp luật bảo vệ nghiêm ngặt.",
    "Dị năng 'Cường Hóa Dương Vật' giúp bạn có thể nện liên tục hàng chục mỹ nhân mà không biết mệt mỏi.",
    "Với dị năng 'Thấu Thị', bạn nhìn thấu mọi âm mưu và cả những bộ nội y gợi cảm nhất của các nữ lãnh đạo."
  ],
  "Siêu năng lực gia": [
    "Tình cờ gặp lại đối thủ cũ, nàng giờ đây đã bị tước bỏ năng lực và trở thành nô lệ tình dục của bạn.",
    "Trong lúc làm nhiệm vụ, bạn và nữ cộng sự vô tình bị kẹt trong một không gian hẹp, hơi thở cả hai hòa quyện.",
    "Vô tình nhìn thấy nữ đội trưởng đang lén lút sử dụng siêu năng lực để tự sướng dâm đãng trong phòng riêng.",
    "Trong buổi tiệc của giới siêu năng lực, bạn tình cờ được nữ minh tinh dị nhân chú ý và lôi kéo vào phòng trống.",
    "Bạn vô tình chạm vào điểm yếu năng lượng của nữ siêu anh hùng, làm nàng tê liệt vùng kín và phun nước.",
    "Thành phố tương lai nơi siêu năng lực là thước đo địa vị xã hội, nữ dị nhân luôn tìm kẻ mạnh để dựa dẫm.",
    "Bối cảnh đô thị hiện đại với tòa tháp chọc trời là nơi trú ngụ của gia tộc siêu năng lực đầy quyền lực.",
    "Các học viện siêu năng lực nơi nữ sinh phải học cách phục vụ những kẻ thức tỉnh mạnh mẽ nhất để tồn tại.",
    "Thế giới sau đại nạn, nơi siêu năng lực gia nắm quyền sinh sát và chiếm hữu mọi mỹ nhân làm tài sản riêng.",
    "Sự phân hóa giữa người thường và dị nhân, tạo nên một xã hội đầy rẫy bất công và dục vọng siêu nhiên.",
    "Các cuộc thi đấu siêu năng lực nơi phần thưởng cho kẻ thắng cuộc là những mỹ nhân tuyệt sắc nhất thế giới.",
    "Thành phố bị chia cắt bởi các băng đảng siêu năng lực, nơi phụ nữ là món hàng trao đổi giá trị nhất.",
    "Hệ thống pháp luật siêu năng lực ưu tiên kẻ mạnh, cho phép họ sở hữu hậu cung gồm toàn nữ siêu anh hùng.",
    "Một xã hội đầy rẫy những nguy hiểm từ quái vật siêu năng lực, nơi phụ nữ cần đàn ông mạnh mẽ bảo vệ.",
    "[HỆ THỐNG]: Nhiệm vụ: Hấp thụ năng lượng từ 3 mỹ nhân cấp SSS qua đường tình dục. Phần thưởng: Siêu năng lực 'Vạn Năng'.",
    "[HỆ THỐNG]: Thông báo: Dương vật của bạn đã được cường hóa siêu năng lực, có thể xuyên thủng mọi lớp phòng vệ.",
    "[HỆ THỐNG]: Cảnh báo: Năng lượng siêu năng trong cơ thể đang quá tải, cần xả ra qua việc gieo giống ngay.",
    "Sở hữu dị năng 'Thấu Thị Lượng Tử', bạn nhìn xuyên qua mọi lớp vật chất để ngắm nhìn cơ thể khỏa thân mỹ nhân.",
    "Với dị năng 'Cường Hóa Giác Quan', bạn cảm nhận được mọi điểm G và sự rung động nhỏ nhất trên cơ thể phụ nữ."
  ],
  "Kẻ thức tỉnh Dị năng": [
    "Trong lúc đang đi dạo, bạn tình cờ thức tỉnh dị năng 'Thấu Thị' và nhìn thấy nội y của mọi mỹ nhân trên phố.",
    "Ngồi cạnh một mỹ nhân trên xe bus, bạn tình cờ thức tỉnh dị năng 'Cảm Biến' và biết nàng đang nứng tột độ.",
    "Trong lúc đang tắm, bạn tình cờ thức tỉnh dị năng 'Dịch Chuyển' và rơi thẳng vào phòng tắm của nữ hàng xóm.",
    "Trong thư viện, bạn tình cờ thức tỉnh dị năng 'Đọc Tâm' và biết được những suy nghĩ dâm dục của nữ thủ thư.",
    "Trong buổi lễ thức tỉnh, năng lực bùng nổ làm quần áo của tất cả phụ nữ trong hội trường bị xé nát.",
    "Sự cố thức tỉnh dị năng không gian đưa bạn rơi thẳng vào bồn tắm của nữ hiệu trưởng khi nàng khỏa thân.",
    "Sự cố thức tỉnh dị năng 'Thấu Thị' làm bạn nhìn thấy toàn bộ nội tạng và khe lồn dâm mị của mỹ nhân.",
    "Thế giới hiện đại nơi con người bắt đầu thức tỉnh năng lực kỳ lạ, thay đổi hoàn toàn cấu trúc xã hội.",
    "Sự xuất hiện của học viện dành riêng cho kẻ thức tỉnh, nơi diễn ra cạnh tranh khốc liệt về quyền lực và tình dục.",
    "Sự xuất hiện của các tổ chức săn lùng kẻ thức tỉnh hiếm, nơi nữ dị nhân là món hàng đắt giá nhất.",
    "Sự phân hóa giữa kẻ thức tỉnh mạnh và yếu, tạo nên một trật tự xã hội dựa trên sức mạnh và xác thịt.",
    "Một xã hội đầy rẫy những bí mật về nguồn gốc của dị năng, nơi phụ nữ là chìa khóa để mở khóa sức mạnh.",
    "[HỆ THỐNG]: Nhiệm vụ: Thức tỉnh thành công dị năng 'Dâm Nhãn'. Phần thưởng: Khả năng nhìn thấy điểm G.",
    "[HỆ THỐNG]: Cảnh báo: Dị năng của bạn đang bị ảnh hưởng bởi dục vọng, cần giao phối để ổn định.",
    "Dị năng 'Cường Hóa Sinh Lý' giúp dương vật của bạn trở nên cứng như thép và rung động ở tần số cực cao.",
    "Với dị năng 'Thấu Thị', bạn nhìn xuyên qua mọi lớp quần áo để chiêm ngưỡng vẻ đẹp dâm mị của nữ dị nhân."
  ],
  "Kẻ sở hữu Hệ thống": [
    "Hệ Thống gánh con.",
    "Sự tồn tại của cửa hàng hệ thống, nơi bạn có thể mua mọi thứ.",
    "Bối cảnh đô thị nơi hệ thống điều khiển mọi hoạt động con người, từ công việc đến hoan lạc.",
    "Sự cạnh tranh giữa những kẻ sở hữu hệ thống, nơi kẻ thắng chiếm hữu toàn bộ tài sản và phụ nữ phe thua.",
    "Xã hội nơi nhiệm vụ từ hệ thống trở thành luật lệ tối cao.",
    "Thế giới nơi việc thăng cấp hệ thống phụ thuộc hoàn toàn vào số lượng mỹ nhân bạn chinh phục được.",
    "Sự phân hóa giữa những kẻ sở hữu hệ thống mạnh và yếu, tạo nên trật tự xã hội dựa trên nhiệm vụ.",
    "Bối cảnh xã hội nơi việc sở hữu một hệ thống cao cấp là biểu tượng của quyền lực và dục vọng tuyệt đối.",
    "Một xã hội đầy rẫy những bí mật về nguồn gốc hệ thống, nơi phụ nữ là chìa khóa để mở khóa chức năng ẩn.",
    "[HỆ THỐNG]: Cảnh báo: Nhu cầu xác thịt của chủ thể quá thấp, bắt buộc thực hiện nhiệm vụ 'Gieo Giống'.",
    "Sở hữu dị năng 'Hệ Thống Quét', bạn biết chính xác mức độ nứng và điểm G của bất kỳ phụ nữ nào.",
    "Dị năng 'Kho Vật Phẩm' giúp bạn luôn có sẵn những công cụ kích dục thần cấp để thu phục mỹ nhân.",
    "Với dị năng 'Giao Diện Hệ Thống', bạn có thể điều khiển khoái lạc phụ nữ như đang chơi một trò chơi."
  ],
  "Trò chơi của thần linh": [
    "Tình cờ được chọn tham gia trò chơi của thần linh khi đang ở cạnh nữ thần bảo hộ.",
    "Trong mê cung trò chơi, bạn tình cờ nhặt được vật phẩm kích dục thần thánh và dùng nó lên nữ sứ giả.",
    "Vô tình đi nhầm vào khu vực cấm của trò chơi, chứng kiến cảnh các nữ thần đang khỏa thân đùa giỡn.",
    "Ngồi cạnh một nữ thần sa ngã trong phòng chờ trò chơi, nàng vô tình chạm vào dương vật của bạn.",
    "Tình cờ gặp lại đối thủ cũ trong trò chơi, nàng giờ đây đã trở thành phần thưởng tình dục cho bạn.",
    "Trong lúc thực hiện thử thách, bạn và nữ cộng sự vô tình bị kẹt trong bẫy tình ái của thần linh.",
    "Trong buổi tiệc của các vị thần, bạn tình cờ được nữ thần ánh sáng chú ý và lôi kéo vào phòng trống.",
    "Đi dạo trong thế giới trò chơi, bạn tình cờ bắt gặp nữ thần chiến tranh đang khỏa thân tắm suối thần.",
    "Sự cố không gian trò chơi đưa bạn rơi thẳng vào suối tắm của các vị nữ thần khi họ khỏa thân.",
    "Bạn vô tình kích hoạt bẫy tình ái trong trò chơi, khiến bạn và nữ sứ giả phải nện nhau nhầy nhụa.",
    "Sự cố thần lực làm dương vật bạn phát sáng rực rỡ, thu hút mọi nữ thần xung quanh lao vào bú mút.",
    "Một thế giới nơi các vị thần tổ chức trò chơi sinh tử, và con người chỉ là những quân cờ.",
    "Sự tồn tại của đấu trường thần thánh, nơi kẻ thắng cuộc nhận được mọi thứ, kể cả nữ thần tuyệt sắc.",
    "Quy tắc trò chơi: Mọi hành động đều tính điểm, và điểm cao nhất thuộc về kẻ chiếm hữu nhiều mỹ nhân nhất.",
    "Một xã hội nơi thần linh và con người đan xen, tạo ra những cuộc tình đầy dục vọng và quyền năng.",
    "Thành phố bị bao phủ bởi hào quang thần thánh, nơi mỗi góc phố đều có thể là một bàn cờ của các vị thần.",
    "Thế giới nơi việc tham gia trò chơi thần linh là cách duy nhất để đàn ông đạt được quyền lực và mỹ nhân.",
    "Sự phân hóa giữa những kẻ được thần linh sủng ái và kẻ bị ruồng bỏ, tạo nên trật tự xã hội khắc nghiệt.",
    "Một xã hội đầy rẫy những bí mật về nguồn gốc trò chơi, nơi phụ nữ là chìa khóa để mở khóa quyền năng thần thánh.",
    "[HỆ THỐNG]: Thông báo: Bạn đã trở thành 'Đại Diện Của Hoan Lạc', mọi phần thưởng đều liên quan đến hậu cung.",
    "[HỆ THỐNG]: Cảnh báo: Thần lực trong cơ thể bị ảnh hưởng bởi dâm khí, cần giao phối để thanh lọc.",
    "Với dị năng 'Thần Nhãn', bạn nhìn thấu mọi điểm yếu và cả những bộ nội y thần thánh của mỹ nhân."
  ],
  "Đô thị tu tiên": [
    "Tình cờ va chạm với nữ tiên tử hạ giới trong biệt thự, tiên khí cộng hưởng làm nàng rên rỉ.",
    "Trong quán bar tu tiên, bạn tình cờ được một nữ tông chủ mời rượu và đề nghị song tu hằng đêm.",
    "Ngồi cạnh một nữ tu sĩ trên phi hành khí, nàng vô tình chạm vào dương vật tràn đầy tiên khí của bạn.",
    "Tình cờ gặp lại sư tỷ cũ, nàng giờ đây đã trở thành nô lệ tình dục của bạn để đổi lấy đan dược.",
    "Thành phố hiện đại nơi các gia tộc tu tiên ẩn mình trong tòa nhà chọc trời, nắm giữ quyền lực tối thượng.",
    "Bối cảnh đô thị nơi tu tiên và công nghệ đan xen, tạo ra pháp khí và dị năng đầy dục vọng.",
    "Quy tắc tu tiên đô thị: Kẻ mạnh có quyền chiếm hữu mọi tài nguyên, bao gồm mỹ nhân linh thể hiếm.",
    "Xã hội đầy rẫy nguy hiểm từ tà tu, luôn tìm cách bắt cóc nữ tu sĩ để làm lô đỉnh song tu.",
    "Bối cảnh đô thị hiện đại nơi tu tiên giả sử dụng ứng dụng di động để tìm kiếm đối tượng song tu.",
    "Thế giới nơi việc tu luyện song tu được coi là phương thức nhanh nhất để đạt được trường sinh bất lão.",
    "Sự phân hóa giữa tu tiên giả chính đạo và tà đạo, tạo nên một xã hội đầy rẫy âm mưu và xác thịt.",
    "Bối cảnh xã hội nơi việc sở hữu một tiên tử làm lô đỉnh là biểu tượng của địa vị và sức mạnh tối cao.",
    "Một xã hội đầy rẫy những bí mật về tiên giới, nơi phụ nữ là chìa khóa để mở cổng trời.",
    "[HỆ THỐNG]: Nhiệm vụ: Thu thập 'Chân Âm' từ 7 vị tiên tử hạ giới đẹp nhất. Phần thưởng: Công pháp 'Thái Dương'.",
    "[HỆ THỐNG]: Thông báo: Bạn đã đạt đến cảnh giới 'Dương Cực', dương vật của bạn giờ là pháp khí cấp thần.",
    "[HỆ THỐNG]: Cảnh báo: Linh khí trong cơ thể đang quá tải, cần thực hiện hành vi song tu để cân bằng.",
    "Sở hữu dị năng 'Song Tu Hệ Thống', bạn thăng cấp tu vi cực nhanh sau mỗi lần giao hoan với mỹ nhân.",
    "Dị năng 'Thấu Thị Tiên Nhãn' giúp bạn nhìn xuyên qua mọi lớp pháp y mỏng manh của các nữ tu sĩ.",
    "Với dị năng 'Cảm Biến Linh Mạch', bạn biết chính xác điểm G và cách khiến nữ tiên tử đạt cực khoái."
  ],
  "Thế giới Mỹ Nữ vô sinh": [
    "Một thế giới tương lai nơi phụ nữ mất khả năng sinh sản, khiến nhân loại đứng trước nguy cơ diệt vong.",
    "Dị năng 'Thấu Thị Tử Cung' giúp bạn biết chính xác thời điểm rụng trứng và khả năng thụ thai của mọi phụ nữ.",
    "Với dị năng 'Cường Hóa Tinh Trùng', tinh dịch của bạn có sức sống mãnh liệt, có thể chữa lành mọi bệnh tật."
  ],
  "Thế giới khan hiếm đàn ông": [
    "Ngồi cạnh một nữ chủ tịch trên máy bay, nàng vô tình chạm vào dương vật hiếm có của bạn và không rời tay.",
    "Tình cờ gặp lại nữ thần tượng, nàng cầu xin bạn ban cho một giọt tinh trùng để nàng có thể giữ vững vị thế.",
    "Một thế giới tương lai nơi tỷ lệ nam nữ bị chênh lệch nghiêm trọng, đàn ông trở thành tài nguyên quý hiếm.",
    "Quy tắc xã hội mới: Đàn ông có quyền sở hữu vô số phụ nữ, và phụ nữ phải cạnh tranh để được để mắt tới.",
    "Một xã hội đầy rẫy những bí mật về sự biến mất của đàn ông, nơi bạn là chìa khóa để cứu lấy nòi giống.",
    "[HỆ THỐNG]: Thông báo: Sức bền của bạn tăng lên mức vô hạn, bạn có thể nện liên tục 1000 mỹ nhân mỗi ngày.",
    "[HỆ THỐNG]: Nhiệm vụ: Chiếm hữu hoàn toàn 10 mỹ nhân cấp S hàng đầu. Phần thưởng: Kỹ năng 'Vua Của Phụ Nữ'.",
    "Dị năng 'Cường Hóa Sinh Lý' giúp bạn duy trì phong độ đỉnh cao dù phải nện hàng chục mỹ nhân cùng lúc.",
    "Với dị năng 'Thấu Thị', bạn nhìn thấu mọi khao khát dâm đãng ẩn sau vẻ ngoài lạnh lùng của các nữ lãnh đạo."
  ],
  "Thế giới với những quy tắc mới": [
    "Thế giới với các quy tắc mới (sau khi bước qua cánh cửa chính sẽ mở ra những quy tắc 18+) như: ở ngoài đường phố thì mọi việc vẫn bình thường, không có gì lạ; trên tàu điện thì người phía sau phải giữ ngực người phía trước; đến công ty thì mọi người phải cởi sạch phần dưới để giữ phép lịch sự; khi nam nhân viên nứng thì nhân viên nữ phải giúp nam nhân viên xuất tinh; trong phòng họp thì sếp nữ phải ngồi lên người cấp dưới và cấp dưới chạm vào lồn của sếp nữ; tại cửa hàng tiện lợi, nhân viên nữ sẽ khỏa thân và khoác hờ chiếc áo của cửa hàng; cửa hàng tiện lợi có sự kiện chỉ dành cho khách hàng nam 'nếu khách hàng nam trúng giải sẽ được gửi 1 món quà nhỏ' với hình thức đăng ký tham gia là đụ nữ nhân viên và xuất trong'; trong nhà hàng, nhân viên phục vụ chỉ mặc độc 1 chiếc áo sơ mi mỏng, các khách hàng cũng phải cởi hết đồ ra và thay bằng chiếc áo giống phục vụ; nếu nhân viên phục vụ làm đổ lên người khách thì phải dùng miệng liếm sạch người của khách.",
    "Một xã hội đầy rẫy những bí mật về nguồn gốc của các quy tắc mới, nơi phụ nữ là chìa khóa để thay đổi thế giới.",
    "Dị năng 'Cường Hóa Sinh Lý' giúp bạn thực thi các quy tắc tình dục khắc nghiệt nhất mà không biết mệt mỏi.",
    "Với dị năng 'Thấu Thị', bạn nhìn thấu mọi khao khát phá vỡ quy tắc ẩn sau vẻ ngoài phục tùng của mỹ nhân."
  ],
  "Phòng Tập Gym Bí Mật": [
    "Phòng tập gym bí mật, bất kì ai tham gia cũng phải kí vào hợp đồng bảo mật, tại đây khác hàng sẽ tham gia những bài tập liên quan tới tình dục, có thể là bài tập đụ với PT xinh đẹp.",
    "Ngồi cạnh một nữ gymer trên máy tập, nàng vô tình chạm vào dương vật to lớn của bạn và đỏ mặt.",
    "Tình cờ gặp lại nữ thần phòng gym, nàng đề nghị bạn làm huấn luyện viên cá nhân 'đặc biệt' cho nàng.",
    "Đi dạo trong khu vực hồ bơi phòng gym, bạn tình cờ bắt gặp nữ huấn luyện viên đang khỏa thân tắm.",
    "Vô tình nghe được bí mật của nhóm nữ gymer về việc họ khao khát được bạn 'huấn luyện' trên giường.",
    "Sự tồn tại của các khóa học 'Gym Dâm Đãng', nơi phụ nữ được dạy cách phục vụ đàn ông qua các bài tập.",
    "[HỆ THỐNG]: Nhiệm vụ: Huấn luyện 'đặc biệt' cho 5 nữ hội viên VIP. Phần thưởng: Kỹ năng 'Cường Hóa Thể Xác'.",
    "Sở hữu dị năng 'Cường Hóa Sinh Lý', bạn có cơ thể hoàn hảo và dương vật to lớn khiến mọi phụ nữ đều thèm khát.",
    "Với dị năng 'Thấu Thị', bạn nhìn thấu mọi khao khát dâm đãng ẩn sau những bộ đồ tập bó sát của mỹ nhân."
  ],
  "Học Viện Siêu Cấp": [
    "Bạn là một học sinh cá biệt tại Học Viện Siêu Cấp, mang tham vọng chinh phục toàn bộ các nữ giáo viên và nữ sinh ưu tú nhất.",
    "Học viện này là nơi tập trung những thiên tài thức tỉnh, nơi quyền lực và sắc đẹp luôn đi đôi với những cuộc cạnh tranh khốc liệt.",
    "Mục tiêu của bạn là thu phục nữ hiệu trưởng lạnh lùng, người nắm giữ vẻ đẹp quyền quý và bí mật về nguồn gốc của siêu năng lực.",
    "Trong những hành lang hiện đại, bạn đang âm thầm xây dựng một đế chế tình dục nơi các nữ sinh đều phải phục tùng bạn.",
    "Bạn thề sẽ khiến hội trưởng hội học sinh kiêu ngạo phải quỳ xuống bú cu mình ngay trong phòng họp hội học sinh.",
    "Mỗi buổi kiểm tra năng lực đều là cơ hội để bạn tiếp cận và mơn trớn những cơ thể tuyệt mỹ đang khao khát sự thăng tiến.",
    "Học viện này sẽ sớm trở thành một trang trại gieo giống bí mật, nơi bạn là vị vua duy nhất được hưởng thụ vạn mỹ nhân.",
    "Trong lúc tập luyện tại phòng gym học viện, bạn vô tình bắt gặp nữ giáo viên thể dục đang khỏa thân tắm rửa sau giờ dạy.",
    "Tình cờ nghe thấy tiếng rên rỉ phát ra từ thư viện vắng người, nơi nữ thủ thư đang lén lút tự giải tỏa cơn nứng đêm khuya.",
    "Đang đi trên hành lang, bạn va phải một nữ sinh ưu tú, đôi vú căng tròn của nàng ép chặt vào người bạn đầy kích thích.",
    "Trong buổi lễ khai giảng, bạn tình cờ bắt gặp ánh mắt thèm khát của một nữ giáo sư đang nhìn chằm chằm vào háng bạn.",
    "Bạn và nữ hội trưởng bị nhốt trong một mật thất mờ ảo, ép hai người phải làm tình liên tục để phá giải trận pháp bảo vệ.",
    "[HỆ THỐNG]: Nhiệm vụ: Chinh phục hoàn toàn 3 'Hoa Khôi Học Viện' trong vòng 15 ngày. Phần thưởng: Kỹ năng 'Thôi Miên Ánh Mắt'.",
    "[HỆ THỐNG]: Chúc mừng! Bạn đã thu thập đủ 10 'Dấu Ấn Học Viện'. Phần thưởng: Thần khí 'Dương Vật Học Đường'.",
    "Sở hữu dị năng 'Thấu Thị', bạn thản nhiên ngắm nhìn vùng kín của các mỹ nhân qua lớp đồng phục học sinh ngay giữa lớp học.",
  ],
  "Hệ Thống Làm Giàu Siêu Cấp": [
    "Hệ thống 'Thần Hào Siêu Năng' giúp bạn nhận được tiền mỗi khi đánh bại một dị nhân hoặc thu phục một mỹ nhân.",
    "Bạn dùng số tiền vô hạn để xây dựng một căn cứ siêu năng lực hiện đại nhất thế giới, nơi tập trung hàng ngàn mỹ nhân.",
    "Hệ thống 'Đấu Giá Vạn Giới' cho phép bạn dùng tiền để mua những dị năng mạnh nhất, biến bạn thành kẻ thống trị.",
    "Bạn dùng tài chính khổng lồ để thâu tóm các tổ chức siêu anh hùng, biến họ thành những người phục vụ cho dục vọng của mình.",
    "[HỆ THỐNG]: Thông báo: Bạn đã trở thành người giàu nhất thế giới siêu năng lực. Kích hoạt 'Quyền Năng Kim Tiền'.",
  ],
  "Dị Năng Đổi Đời Dị Nhân": [
    "Dị năng 'Biến đá thành vàng' giúp bạn sở hữu nguồn tài nguyên vô tận, khiến mọi mỹ nhân phải quỳ lạy xin được che chở.",
    "Bạn dùng dị năng 'Thao túng xác suất' để luôn thắng trong mọi cuộc cá cược và đầu tư, đổi đời chỉ sau một đêm.",
    "Dị năng 'Tạo ra vật chất' giúp bạn có mọi thứ mình muốn, từ siêu xe đến những món quà đắt giá để lấy lòng mỹ nhân.",
    "Bạn dùng sức mạnh của mình để thay đổi trật tự thế giới, nơi kẻ giàu có và mạnh mẽ nhất là bạn có quyền chiếm hữu tất cả.",
    "[HỆ THỐNG]: Cảnh báo: Sự giàu có của bạn đang thu hút sự chú ý của các nữ sát thủ. Hãy thu phục họ ngay.",
  ],
  "Nữ Đội Trưởng Siêu Năng": [
    "Bạn là một thành viên mới trong tổ chức bảo vệ hòa bình thế giới, làm việc dưới quyền Nữ Đội Trưởng lạnh lùng và nghiêm khắc.",
    "Nữ Đội Trưởng sở hữu siêu năng lực 'Băng Giá', nhưng khi ở gần bạn, nàng lại bị sự nam tính của bạn làm tan chảy hoàn toàn.",
    "Trong một nhiệm vụ thâm nhập, bạn và Nữ Đội Trưởng bị trúng bẫy kích dục của kẻ thù, khiến nàng phải cầu xin bạn giúp đỡ để giải tỏa cơn nứng.",
    "Bạn sở hữu 'Hệ Thống Phân Tích Siêu Năng', giúp bạn nhìn thấu mọi điểm yếu và cả những khao khát thầm kín của vị Nữ Đội Trưởng kiêu hãnh.",
    "Dị năng 'Thôi Miên' giúp bạn biến Nữ Đội Trưởng thành một dâm phụ trung thành chỉ biết phục vụ bạn trong phòng làm việc.",
    "[HỆ THỐNG]: Nhiệm vụ: Chinh phục trái tim và thể xác của Nữ Đội Trưởng. Phần thưởng: Quyền kiểm soát toàn bộ tổ chức.",
  ],
  "Nữ Sát Thủ Giả Nam": [
    "Bạn là một thám tử tư đang điều tra một vụ án mạng, phát hiện ra vị 'nam' sát thủ lừng danh thực chất là một mỹ nhân đang cải nam trang.",
    "Nàng giả nam để thâm nhập vào thế giới ngầm và thực hiện các phi vụ ám sát, bạn dùng bí mật này để ép nàng phải 'hầu hạ' mình mỗi đêm.",
    "Trong một cuộc rượt đuổi, bạn đã bắt được Nữ Sát Thủ và lột bỏ lớp ngụy trang của nàng, để lộ cơ thể quyến rũ khiến bạn không thể kìm lòng.",
    "Nữ Sát Thủ bị trúng thuốc phát tình từ kẻ thù, nàng chỉ có thể được giải thoát nếu được một nam nhân mạnh mẽ như bạn chiếm hữu tử cung.",
    "Dị năng 'Thấu Thị' giúp bạn thản nhiên ngắm nhìn vẻ đẹp ngọc ngà của nàng ẩn sau lớp y phục nam nhân thô kệch.",
    "[HỆ THỐNG]: Nhiệm vụ: Thu phục Nữ Sát Thủ và biến nàng thành 'công cụ' tình dục trung thành nhất của bạn.",
  ],
  "Phim Ngắn Đô Thị Siêu Cấp (Short Dramas)": [
    "Bạn là 'Chiến Thần' lừng danh, chỉ cần một cuộc điện thoại là 10 vạn binh sĩ kéo đến, bạn trở về để bảo vệ người vợ bị sỉ nhục và trừng phạt đám hào môn bằng sức mạnh tuyệt đối.",
    "Bạn là 'Thần Y' vừa xuống núi, mang theo hôn ước với 9 vị đại mỹ nhân, dùng kỹ năng châm cứu thần thánh để chữa bệnh và chiếm hữu thể xác của họ.",
    "Bạn là 'Long Chủ' của tổ chức bí mật toàn cầu, đóng giả làm một kẻ vô dụng bị nhà vợ khinh rẻ, cho đến khi thân phận thật sự của bạn làm rung chuyển cả thế giới.",
    "Bạn là một 'Tu Tiên Giả' trọng sinh vào thân xác một tên rác rưởi ở đô thị, dùng tiên pháp để vả mặt đám thiếu gia và thu phục các nữ vương, nữ chủ tịch kiêu ngạo.",
    "Bối cảnh 'Hệ Thống Thần Hào' nơi bạn có vô hạn tiền bạc, dùng tiền để đè bẹp mọi đối thủ và xây dựng một hậu cung gồm toàn những mỹ nhân nổi tiếng nhất.",
    "Bạn sở hữu 'Dị Năng Thôi Miên', dùng nó để biến những nữ cảnh sát, nữ luật sư lạnh lùng thành những nô lệ tình dục trung thành nhất của mình.",
    "Bạn đóng giả làm một nhân viên bảo vệ quèn tại tập đoàn, nhưng khi kẻ thù tấn công, bạn bộc phát sức mạnh 'Thần Cấp' khiến nữ chủ tịch phải quỳ lạy van xin sự bảo hộ.",
    "Bạn cứu được một cô gái nghèo bị đám lưu manh bắt nạt, không ngờ nàng lại là con gái duy nhất của tỷ phú giàu nhất thế giới đang đi trải nghiệm cuộc sống.",
    "Bạn là đứa con bị bỏ rơi của gia tộc, trở về để trả thù và bắt đầu bằng việc chinh phục người mẹ kế trẻ đẹp, quyền lực của cha mình.",
    "Bạn là một bác sĩ tâm thần được thuê để chăm sóc nữ tổng tài bị mù, dùng sự chăm sóc tận tình và 'dương vật' để chữa trị cả tâm hồn lẫn thể xác cho nàng.",
    "Bạn sở hữu 'Hệ Thống Vả Mặt', mỗi khi bạn làm nhục một kẻ hống hách, bạn sẽ nhận được phần thưởng là kỹ năng hoặc mỹ nhân cực phẩm.",
    "Bạn là một 'Ngự Thú Sư' trong đô thị, có thể điều khiển các loài thú dữ và dùng chúng để bảo vệ các nữ minh tinh khỏi những âm mưu đen tối.",
    "Bạn có khả năng 'Dừng Lại Thời Gian', dùng nó để trừng phạt những kẻ ác và thản nhiên thưởng thức vẻ đẹp của các mỹ nhân trong trạng thái tĩnh lặng.",
    "Bạn là 'Quỷ Y' có thể giao tiếp với linh hồn, dùng sức mạnh tâm linh để chữa trị những căn bệnh lạ cho các thiên kim tiểu thư và khiến họ mang ơn bằng cả đời mình.",
    "[HỆ THỐNG]: Nhiệm vụ: Kích hoạt trạng thái 'Vô Địch Đô Thị' và thu thập đủ 12 'Kim Thoa' (mỹ nhân cực phẩm).",
    "[HỆ THỐNG]: Thông báo: Uy áp của bạn đã đạt mức 'Chúa Tể'. Mọi phụ nữ nhìn thấy bạn đều sẽ tự động phát tình.",
  ],
  "Hệ Thống Đô Thị Nghịch Thiên": [
    "Bạn sở hữu 'Hệ Thống Lựa Chọn', mỗi khi đứng trước một tình huống, hệ thống sẽ đưa ra các lựa chọn với phần thưởng là tiền bạc, kỹ năng hoặc mỹ nhân.",
    "Bạn sở hữu 'Hệ Thống Đầu Tư Mỹ Nhân', mỗi khi bạn chi tiền cho một cô gái có tiềm năng, bạn sẽ nhận được phản hồi tài sản gấp 1000 lần.",
    "Bạn sở hữu 'Hệ Thống Điểm Danh', mỗi ngày điểm danh tại một địa điểm khác nhau (văn phòng, biệt thự, trường học) sẽ nhận được những phần thưởng cực phẩm.",
    "Bạn sở hữu 'Hệ Thống Nhiệm Vụ Thần Hào', hoàn thành các nhiệm vụ như 'mua siêu xe', 'cứu mỹ nhân' để nhận được điểm thuộc tính và quyền năng vô hạn.",
    "Bạn sở hữu 'Hệ Thống Phản Diện Nghịch Thiên', nhiệm vụ của bạn là phải đối đầu và cướp đi mọi thứ của các 'con cưng của trời' (protagonists), bao gồm cả những vị hôn thê tuyệt sắc của họ.",
    "Bạn là một Thần Y từ thời cổ đại xuyên không về đô thị hiện đại, dùng kỹ năng châm cứu và linh dược để chữa những căn bệnh nan y cho các đại gia và thu phục các thiên kim tiểu thư.",
    "Bạn sở hữu 'Hệ Thống Vạn Giới Hồng Bao', thỉnh thoảng sẽ nhận được những bao lì xì chứa kỹ năng, tiền bạc hoặc thẻ 'chiếm hữu mỹ nhân' từ các vị thần tiên.",
    "Bạn sở hữu 'Hệ Thống Thuê Mỹ Nhân', bạn có thể dùng tiền để thuê bất kỳ mỹ nhân nào (từ minh tinh đến nữ vương) làm người hầu hoặc bạn gái trong một khoảng thời gian nhất định.",
    "Bạn sở hữu 'Hệ Thống Cướp Đoạt Cơ Duyên', bạn có thể nhìn thấy 'khí vận' của người khác và cướp đi những cơ hội ngàn năm có một cùng những mỹ nhân thuộc về họ.",
    "Bạn sở hữu 'Hệ Thống Phản Diện Nghịch Thiên', mỗi khi bạn làm thay đổi cốt truyện của 'nhân vật chính' (protagonist), bạn sẽ nhận được điểm phản diện để đổi lấy sức mạnh và mỹ nhân.",
    "Bạn là một sát thủ trọng sinh vào thân xác một thiếu gia rác rưởi, sở hữu 'Hệ Thống Sát Thần', mỗi khi giết một kẻ thù, bạn sẽ nhận được thuộc tính và kỹ năng của hắn.",
    "Bạn sở hữu 'Hệ Thống Vạn Giới Triệu Hồi', có thể triệu hồi các nữ chiến binh mạnh mẽ từ các thế giới khác để làm vệ sĩ và người hầu hạ riêng cho mình.",
    "Bạn sở hữu 'Hệ Thống Cửa Hàng Vạn Giới', có thể bán những món đồ bình thường của hiện đại sang các thế giới tiên hiệp để đổi lấy linh đan và mỹ nhân tiên tử làm người hầu.",
    "Bạn là một 'Tu Tiên Giả' từ tiên giới trọng sinh về đô thị, sở hữu 'Hệ Thống Thu Thập Linh Thể', nhiệm vụ của bạn là tìm kiếm và 'khai phá' những mỹ nhân mang linh thể hiếm để khôi phục tu vi.",
    "Bạn sở hữu 'Hệ Thống Phản Diện Đỉnh Cấp', mỗi khi bạn cướp đi 'hào quang' và mỹ nhân của các 'nhân vật chính' (protagonists) trong đô thị, bạn sẽ nhận được phần thưởng là sức mạnh thần cấp.",
    "Bạn sở hữu 'Hệ Thống Tiến Hóa Toàn Cầu', có thể nhìn thấy con đường tiến hóa của mọi vật, từ thú cưng đến các mỹ nhân xung quanh, giúp họ thức tỉnh sức mạnh và trở thành thuộc hạ trung thành của bạn.",
    "Bạn là một 'Thương Nhân Vạn Giới' trọng sinh về đô thị, sở hữu 'Hệ Thống Giao Dịch Không Gian', dùng công nghệ tương lai để đổi lấy các bí kíp tu luyện cổ xưa và các nữ tu sĩ xinh đẹp từ tiên giới.",
    "Bạn trọng sinh vào một thế giới nơi mọi người đều thức tỉnh siêu năng lực, sở hữu 'Hệ Thống Kiểm Soát Thời Không', có thể ngưng đọng thời gian để làm những việc 'mờ ám' với các nữ siêu anh hùng kiêu ngạo.",
    "[HỆ THỐNG]: Thông báo: Cấp độ 'Thần Hào' của bạn đã đạt mức tối đa. Bạn chính là chủ nhân của thế giới này.",
  ],
  "Nữ Chủ Siêu Năng (Low NSFW/Lesbian)": [
    "Bạn là một nữ siêu anh hùng mạnh mẽ, sở hữu 'Hệ Thống Nữ Thần', nhiệm vụ của bạn là thu phục các nữ ác nhân và đồng đội xinh đẹp vào hậu cung của mình.",
    "Trong một thế giới siêu năng lực, bạn là nữ hoàng của bóng tối, dùng mị lực và sức mạnh để khiến các nữ chiến binh ánh sáng phải quỳ phục.",
    "Dị năng 'Thao túng tâm trí' giúp bạn dễ dàng chiếm hữu trái tim và thể xác của bất kỳ người phụ nữ nào bạn muốn.",
    "Bạn là một nữ bác sĩ siêu năng lực, chuyên chữa trị cho các nữ anh hùng bị thương, dùng sự chăm sóc tận tình để khơi dậy tình cảm nơi họ.",
    "Trong một trận chiến ác liệt, bạn và nàng đối thủ truyền kiếp bị trúng một loại khí gas kỳ lạ, khiến cả hai nảy sinh dục vọng mãnh liệt với nhau.",
    "Bạn sở hữu hệ thống 'Nữ Chủ Harem', giúp bạn thu thập những mỹ nhân siêu năng lực mạnh nhất thế giới.",
    "Dị năng 'Mị lực nữ giới' khiến mọi phụ nữ có siêu năng lực đều cảm thấy bị thu hút bởi bạn, sẵn sàng dâng hiến tất cả cho bạn.",
    "Bạn là một nữ điệp viên siêu hạng, dùng sắc đẹp và kỹ năng để thâm nhập vào các tổ chức nữ quyền và chiếm hữu các nữ lãnh đạo.",
    "Trong một không gian song song, bạn là nữ vương của một hành tinh chỉ có phụ nữ, đang nỗ lực bảo vệ thần dân khỏi các thế lực ngoại bang.",
    "Hệ thống 'Nữ Chủ Chinh Phục' giao nhiệm vụ cho bạn phải thu phục 3 nữ siêu anh hùng cấp S hàng đầu.",
  ],
  "Hành Trình Tự Do Siêu Năng (Gender Neutral - SFW)": [
    "Bạn là một người thức tỉnh siêu năng lực 'Giao tiếp với vạn vật', dùng khả năng này để giúp đỡ con người và thiên nhiên chung sống hòa bình.",
    "Trong một thành phố siêu năng lực, bạn là một người thợ sửa chữa những món đồ siêu nhiên, mang lại niềm vui cho mọi người từ những điều nhỏ nhặt.",
    "Bạn sở hữu siêu năng lực 'Kiến tạo giấc mơ', dùng nó để giúp những người gặp khó khăn tìm thấy hy vọng và động lực trong cuộc sống.",
    "Bạn là một người bảo vệ trật tự siêu năng lực, luôn xuất hiện đúng lúc để ngăn chặn những thảm họa và bảo vệ sự bình yên cho cư dân.",
    "Bạn là một nhà nghiên cứu về nguồn gốc của siêu năng lực, đi khắp thế giới để tìm kiếm sự thật và hướng tới một tương lai tốt đẹp hơn cho nhân loại.",
  ],
};

export const IDENTITIES: string[] = Object.entries(RAW_DATA).flatMap(([context, scenarios]) => 
  scenarios.map(s => `Bối cảnh: ${context} - ${s}`)
);

export const SPECIALIZED_DATA: Record<string, { label: string, action: string }[]> = {};
