
export const RAW_DATA: Record<string, string[]> = {
  "Tôi có Hệ thống": [
    "Hệ Thống gánh con.",
    "Hệ thống thông báo: Nhiệm vụ chính tuyến - Chinh phục Nữ thần Ánh sáng, phần thưởng: Kỹ năng 'Hào quang Quyến rũ'.",
    "Bạn dùng điểm tích lũy đổi lấy 'Dược phẩm Kích dục', khiến mỹ nhân đối diện không thể kiềm chế bản thân.",
    "Hệ thống hiển thị độ thiện cảm của công chúa là 100%, nàng sẵn sàng dâng hiến tất cả cho bạn.",
    "Kỹ năng 'Thấu thị' cho phép bạn nhìn thấu mọi lớp y phục của các nữ pháp sư trong học viện.",
    "Hệ thống thông báo: Bạn đã mở khóa tư thế 'Giao hợp Thần thánh', tăng mạnh khoái cảm cho cả hai.",
    "Hệ thống tự động tìm kiếm những mỹ nhân có thể chất đặc biệt để bạn đi chinh phục.",
    "Dùng 'Dịch chuyển Tức thời' để lẻn vào phòng tắm của nữ vương và chiếm hữu nàng bất ngờ.",
    "Hệ thống hiển thị: Nữ pháp sư đang thèm khát tinh chất của bạn để đột phá cảnh giới ma pháp.",
    "Dùng kỹ năng 'Cường hóa Sinh lý' để nện liên tục nhiều mỹ nhân mà không hề biết mệt mỏi.",
    "Sử dụng 'Gương phản chiếu Dục vọng' để khiến mỹ nhân nhìn thấy những hình ảnh dâm loạn với bạn.",
    "Bạn là người duy nhất sở hữu hệ thống, và mọi mỹ nhân trong thế giới này đều là của bạn."
  ],
  "Tôi thức tỉnh Dị năng": [
    "Dùng dị năng 'Thấu thị' để chiêm ngưỡng trọn vẹn cơ thể dâm mỹ của nữ thánh nữ dưới lớp áo.",
    "Thức tỉnh năng lực 'Cường hóa Sinh lý', bạn có thể nện liên tục nhiều mỹ nhân suốt đêm dài.",
    "Năng lực 'Dịch chuyển Không gian' giúp bạn lẻn vào phòng ngủ của công chúa mỗi đêm dễ dàng.",
    "Thức tỉnh dị năng 'Nhìn xuyên Tương lai', bạn biết chính xác lúc nào mỹ nhân đang thèm khát nhất.",
    "Năng lực 'Hấp thụ Linh lực qua Giao hợp' giúp bạn càng nện nhiều mỹ nhân thì càng mạnh mẽ.",
    "Năng lực 'Kết nối Linh hồn' khiến mỹ nhân hoàn toàn lệ thuộc vào bạn sau khi được bạn nện.",
    "Thức tỉnh dị năng 'Hồi phục Thần tốc', bạn luôn sẵn sàng cho những cuộc chinh chiến xác thịt.",
    "Dùng dị năng 'Thao túng Giấc mơ' để gieo rắc những hình ảnh dâm dục về bạn vào tâm trí mỹ nhân."
  ],
  "Tôi có Siêu năng lực": [
    "Sở hữu siêu năng lực 'Sức mạnh Vô hạn', bạn thản nhiên nhấc bổng nữ hiệp sĩ và chiếm hữu nàng.",
    "Siêu năng lực 'Dịch chuyển' cho phép bạn lẻn vào phòng ngủ của bất kỳ mỹ nhân nào bạn muốn.",
    "Siêu năng lực 'Nhìn xuyên Vật thể' giúp bạn chiêm ngưỡng vùng kín của mọi nữ siêu anh hùng.",
    "Sở hữu 'Khả năng Hồi phục SSS', bạn không bao giờ biết mệt mỏi dù nện liên tục nhiều mỹ nhân.",
    "Sở hữu 'Mắt thần', bạn có thể tìm thấy mọi mỹ nhân đang lẩn trốn để bắt về làm nô lệ.",
    "Sở hữu 'Quyền năng Sáng thế', bạn tạo ra thế giới riêng chỉ toàn mỹ nhân phục vụ dục vọng bạn.",
  ],
  "Tôi là Thành viên Hoàng Gia": [
    "Dùng quyền lực hoàng gia để biến nữ hiệp sĩ kiêu ngạo thành nô lệ tình dục của riêng bạn.",
    "Lẻn vào phòng tắm của hoàng hậu mỗi đêm, dùng dương vật vĩ đại để khiến nàng phải rên rỉ.",
    "Dùng dị năng 'Thấu thị' hoàng gia để chiêm ngưỡng cơ thể dâm mỹ của mọi nữ hầu trong cung điện.",
    "Thiết lập một hậu cung gồm toàn những mỹ nhân tuyệt sắc nhất, nơi bạn là vị vua của sắc dục.",
    "Yêu cầu công chúa nước láng giềng phải dâng hiến trinh tiết để đổi lấy sự bảo hộ từ vương quốc.",
    "Tổ chức những buổi yến tiệc dâm loạn trong mật thất, nơi các quý tộc và mỹ nhân cùng hoan lạc.",
    "Là người thừa kế ngai vàng, bạn có quyền gieo giống cho bất kỳ nữ nhân nào trong vương quốc.",
    "Lẻn vào phòng ngủ của các phi tần mỗi đêm, dùng kỹ năng tuyệt đỉnh để khiến họ lệ thuộc bạn.",
    "Thiết lập luật lệ: Mọi mỹ nhân quý tộc khi trưởng thành đều phải qua đêm với hoàng tử trước.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn vùng kín của mọi mỹ nhân dạ hội.",
    "Khiến nữ vương của vương quốc đối địch phải làm nô lệ tình dục sau khi bị bạn đánh bại.",
    "Dùng 'Cường hóa Sinh lý' hoàng gia để có thể phục vụ toàn bộ hậu cung mà không biết mệt mỏi.",
  ],
  "Thời kỳ Chiến Tranh": [
    "Trên chiến trường, bạn thản nhiên chiếm hữu nữ tướng quân địch làm chiến lợi phẩm trong lều.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp giáp của các nữ binh sĩ, chiêm ngưỡng vùng kín.",
    "Trong buổi tiệc mừng chiến thắng, bạn thản nhiên chiếm hữu nữ anh hùng ngay trước mặt binh sĩ.",
    "Biến doanh trại nữ thành một hậu cung dâm loạn, nơi bạn là vị chúa tể duy nhất gieo giống.",
    "Dùng quyền lực quân sự để ép buộc các tiểu thư vùng chiếm đóng phải dâng hiến thân xác cho bạn.",
    "Lẻn vào lều của nữ tướng địch mỗi đêm, dùng dương vật vĩ đại để biến nàng thành nội gián.",
    "Thiết lập luật lệ: Mọi nữ binh sĩ bại trận đều phải qua tay bạn kiểm tra vùng kín nhục nhã.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y của các nữ sĩ quan đồng minh.",
  ],
  "Tôi là Mạo hiểm giả": [
    "Là mạo hiểm giả cấp S, bạn yêu cầu nữ tiếp tân xinh đẹp phải quỳ xuống phục vụ ngay tại quầy.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp giáp da của các nữ đồng đội, chiêm ngưỡng vùng kín.",
    "Biến nữ pháp sư trong tổ đội thành nô lệ tình dục trung thành phục vụ nhu cầu của bạn mỗi đêm.",
    "Ép buộc nữ kiếm sĩ kiêu ngạo phải dâng hiến trinh tiết để được gia nhập tổ đội của bạn.",
    "Dùng 'Thao túng Cảm xúc' để biến sự lạnh lùng của nữ thợ săn thành sự thèm khát bạn tột độ.",
    "Trong hầm ngục tối tăm, bạn thản nhiên chiếm hữu nữ linh mục ngay trước mặt đám quái vật.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ mạo hiểm giả.",
    "Biến lều trại của tổ đội thành mật thất hoan lạc, nơi bạn và các mỹ nhân nện nắc điên cuồng.",
    "Dùng danh tiếng để ép buộc các nữ mạo hiểm giả tân thủ phải qua đêm với bạn để được chỉ dẫn.",
    "Khiến nữ đội trưởng của tổ đội đối địch phải mang thai giọt máu của bạn sau khi bị đánh bại.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ nhân viên hội quán thành những con điếm dâm đãng.",
    "Lẻn vào phòng tắm của các nữ mạo hiểm giả mỗi đêm, dùng dương vật vĩ đại để chinh phục họ.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục nhiều mỹ nhân mạo hiểm giả mà không mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ đồng đội khi nhận thưởng đều phải dâng hiến dâm thủy cho bạn.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn vùng kín của mọi nữ mạo hiểm giả.",
    "Khiến nữ anh hùng mạnh nhất hội phải làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Hầm ngục' khiến mọi mỹ nhân trong tổ đội đều cảm thấy nứng và thèm khát.",
    "Trở thành 'Chúa tể Mạo hiểm Dâm uy', mọi mỹ nhân nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ pháp sư và chiếm hữu nàng.",
    "Khiến nữ kiếm sĩ huyền thoại phải quỳ xuống phục vụ bạn trên thanh kiếm báu đã bị chinh phục."
  ],
  "Tôi được Nữ Thần chọn": [
    "Là người được chọn, bạn yêu cầu nữ thánh nữ phải cởi sạch đồ và phục vụ ngay trong điện thờ.",
    "Dùng thánh lực tối cao để biến nữ tế ti kiêu ngạo thành nô lệ tình dục phục vụ xác thịt bạn.",
    "Lẻn vào phòng tắm của nữ thần mỗi đêm, dùng dương vật vĩ đại để khiến nàng phải rên rỉ.",
    "Trong buổi lễ thánh, bạn thản nhiên sờ soạng vùng kín của các nữ tu sĩ ngay trước tượng thần.",
    "Dùng dị năng 'Thấu thị' thần thánh để chiêm ngưỡng cơ thể dâm mỹ của mọi mỹ nhân thánh điện.",
    "Thiết lập một hậu cung gồm toàn những thánh nữ tuyệt sắc nhất, nơi bạn là chúa tể sắc dục.",
    "Yêu cầu nữ thiên sứ phải dâng hiến trinh tiết để đổi lấy sự ban phước thần thánh từ bạn.",
    "Dùng 'Thao túng Cảm xúc' để biến sự thánh khiết của nữ giáo hoàng thành sự thèm khát bạn.",
    "Tổ chức những buổi lễ tế dâm loạn trong mật thất, nơi các nữ tu và bạn cùng hoan lạc.",
    "Là người mang dòng máu thần, bạn có quyền gieo giống cho bất kỳ nữ nhân nào trong giáo hội.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên chiếm hữu các nữ tế ti ngay giữa buổi lễ.",
    "Khiến nữ thánh nữ cao quý nhất phải quỳ xuống phục vụ dương vật của bạn trên sàn điện thờ.",
    "Dùng quyền năng để ép buộc nữ thiên sứ mạnh nhất phải mang thai giọt máu của bạn để củng cố đức tin.",
    "Lẻn vào phòng ngủ của các nữ tu mỗi đêm, dùng kỹ năng tuyệt đỉnh để khiến họ lệ thuộc bạn.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ tế ti thành những con điếm phục vụ bạn.",
    "Thiết lập luật lệ: Mọi nữ tu khi trưởng thành đều phải qua đêm với người được chọn để tẩy trần.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn vùng kín của mọi mỹ nhân thánh điện.",
    "Khiến nữ thần của vương quốc đối địch phải làm nô lệ tình dục sau khi bị bạn đánh bại.",
    "Dùng 'Cường hóa Sinh lý' thần thánh để có thể phục vụ toàn bộ dàn thánh nữ mà không mệt mỏi.",
    "Trở thành 'Chúa tể Thánh khiết Dâm uy', mọi mỹ nhân thánh điện đều khao khát được bạn nện."
  ],
  "Tôi là người Chuyển sinh đến Dị giới": [
    "Chuyển sinh đến dị giới, bạn dùng kiến thức hiện đại để quyến rũ và chiếm hữu công chúa.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp giáp của các nữ chiến binh tộc Elf xinh đẹp.",
    "Biến nữ pháp sư mạnh nhất vương quốc thành nô lệ tình dục trung thành phục vụ nhu cầu của bạn.",
    "Ép buộc nữ hoàng của vương quốc mới phải dâng hiến trinh tiết để đổi lấy công nghệ từ bạn.",
    "Dùng 'Thao túng Cảm xúc' để biến sự nghi ngờ của các mỹ nhân thành sự thèm khát bạn tột độ.",
    "Trong lâu đài hoàng gia, bạn thản nhiên chiếm hữu nữ thánh nữ ngay trước mặt đức vua.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ quan dị giới.",
    "Biến dinh thự được ban tặng thành hậu cung dâm loạn, nơi bạn là vị chúa tể duy nhất gieo giống.",
    "Dùng quyền lực chuyển sinh để ép buộc các nữ mạo hiểm giả phải qua đêm với bạn mỗi ngày.",
    "Khiến nữ tướng quân của đế quốc phải mang thai giọt máu của bạn để củng cố địa vị tối cao.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ hầu thành những con điếm phục vụ dương vật bạn.",
    "Lẻn vào phòng tắm của các mỹ nhân dị giới mỗi đêm, dùng dương vật vĩ đại để chinh phục họ.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục nhiều mỹ nhân dị giới mà không biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi mỹ nhân dị giới khi gặp người chuyển sinh đều phải dâng hiến thể xác.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn vùng kín của mọi mỹ nhân đối diện.",
    "Khiến nữ thần bảo hộ thế giới mới phải làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Dị giới' khiến mọi phụ nữ xung quanh đều cảm thấy nứng và thèm khát.",
    "Trở thành 'Chúa tể Chuyển sinh Dâm uy', mọi mỹ nhân nhìn thấy bạn đều muốn được dâng hiến.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ hoàng và chiếm hữu nàng bất ngờ.",
    "Khiến nữ kiếm sĩ huyền thoại của dị giới phải quỳ xuống phục vụ bạn trên thanh kiếm báu."
  ],
  "Tôi là Quý tộc trẻ": [
    "Chuyển sinh thành thiếu gia quý tộc, cha mẹ đều mất do tai nạn, tôi thừa kế toàn dinh thự tài sản kết xù.",
    "Dùng quyền lực gia tộc để biến tiểu thư nhà đối địch thành nô lệ tình dục trung thành của bạn.",
    "Lẻn vào phòng tắm của mẹ kế mỗi đêm, dùng dương vật vĩ đại để khiến bà phải rên rỉ sung sướng.",
    "Trong buổi dạ tiệc thượng lưu, bạn thản nhiên sờ soạng vùng kín của các quý phu nhân quý tộc.",
    "Dùng dị năng 'Thấu thị' quý tộc để chiêm ngưỡng cơ thể dâm mỹ của mọi nữ nô trong dinh thự.",
    "Thiết lập một hậu cung gồm toàn những tiểu thư quý tộc tuyệt sắc nhất phục vụ dục vọng bạn.",
    "Yêu cầu nữ gia sư nghiêm khắc phải dâng hiến trinh tiết để đổi lấy sự im lặng về bí mật nàng.",
    "Dùng 'Thao túng Cảm xúc' để biến sự khinh miệt của nữ phản diện thành sự thèm khát bạn tột độ.",
    "Tổ chức những buổi tiệc dâm loạn trong mật thất, nơi các quý tộc trẻ cùng hoan lạc suốt đêm.",
    "Là người thừa kế duy nhất, bạn có quyền gieo giống cho bất kỳ nữ hầu nào trong gia tộc.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên chiếm hữu các nữ quan ngay giữa buổi lễ.",
    "Khiến nữ hiệp sĩ bảo vệ gia tộc phải quỳ xuống phục vụ bạn ngay trên sàn phòng tập võ.",
    "Dùng quyền lực để ép buộc nữ tướng quân biên thùy phải mang thai giọt máu của bạn củng cố liên minh.",
    "Lẻn vào phòng ngủ của các em gái nuôi mỗi đêm, dùng kỹ năng tuyệt đỉnh để khiến họ lệ thuộc.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ hầu thành những con điếm phục vụ dương vật bạn.",
    "Thiết lập luật lệ: Mọi cô gái xinh đẹp trong lãnh địa khi dậy thì đều phải qua tay thiếu gia.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn vùng kín của mọi mỹ nhân dạ hội.",
    "Khiến phu nhân của lãnh chúa láng giềng phải làm nô lệ tình dục nhục nhã sau khi bị bạn nắm thóp.",
    "Dùng 'Cường hóa Sinh lý' quý tộc để có thể phục vụ toàn bộ dàn mỹ nhân mà không biết mệt mỏi.",
    "Trở thành 'Chúa tể Dâm uy' giới quý tộc, mọi mỹ nhân thấy bạn đều khao khát được bạn nện."
  ],
  "Anh hùng cứu thế": [
    "Là anh hùng cứu thế, bạn yêu cầu nữ hoàng phải quỳ xuống phục vụ ngay trên ngai vàng uy nghiêm.",
    "Dùng thánh kiếm để chinh phục và biến nữ ma vương xinh đẹp thành nô lệ tình dục trung thành.",
    "Lẻn vào phòng tắm của nữ thần bảo hộ mỗi đêm, dùng dương vật vĩ đại để khiến nàng rên rỉ.",
    "Trong buổi lễ vinh danh, bạn thản nhiên chiếm hữu nữ công chúa ngay trước mặt toàn thể thần dân.",
    "Dùng dị năng 'Thấu thị' anh hùng để chiêm ngưỡng cơ thể dâm mỹ của các nữ đồng đội xinh đẹp.",
    "Thiết lập một hậu cung gồm toàn những mỹ nhân mạnh nhất thế giới, nơi bạn là chúa tể sắc dục.",
    "Yêu cầu nữ thánh nữ phải dâng hiến trinh tiết để đổi lấy sự cứu rỗi cho vương quốc của nàng.",
    "Dùng 'Thao túng Cảm xúc' để biến sự tôn sùng của các mỹ nhân thành sự thèm khát bạn tột độ.",
    "Tổ chức những buổi tiệc hoan lạc trong lâu đài anh hùng, nơi bạn và các mỹ nhân nện nắc suốt đêm.",
    "Là cứu tinh nhân loại, bạn có quyền gieo giống cho bất kỳ nữ nhân nào trên khắp thế giới.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên chiếm hữu các nữ quan ngay giữa buổi họp khẩn.",
    "Khiến nữ tướng quân mạnh nhất đế quốc phải quỳ xuống phục vụ bạn trên bộ giáp trụ sáng loáng.",
    "Dùng quyền năng để ép buộc nữ thần chiến tranh phải mang thai giọt máu của bạn củng cố sức mạnh.",
    "Lẻn vào phòng ngủ của các nữ tu sĩ mỗi đêm, dùng kỹ năng tuyệt đỉnh để khiến họ lệ thuộc bạn.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ hầu cung điện thành những con điếm phục vụ bạn.",
    "Thiết lập luật lệ: Mọi phụ nữ xinh đẹp trong vương quốc đều phải dâng hiến dâm thủy cho anh hùng.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn vùng kín của mọi mỹ nhân vương quốc.",
    "Khiến nữ ma vương thế giới ngầm phải làm nô lệ tình dục nhục nhã sau khi bị bạn đánh bại.",
    "Dùng 'Cường hóa Sinh lý' anh hùng để có thể phục vụ toàn bộ hậu cung mà không biết mệt mỏi.",
    "Trở thành 'Chúa tể Anh hùng Dâm uy', mọi mỹ nhân được cứu rỗi đều khao khát được bạn nện."
  ],
  "Tôi muốn lập Nhóm": [
    "Là chủ nhân hậu cung, bạn yêu cầu nữ kiếm sĩ tộc Elf phải quỳ xuống phục vụ ngay giữa buổi yến tiệc.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp y phục của mọi mỹ nhân trong nhóm, chiêm ngưỡng vùng kín.",
    "Biến nữ vương quỷ kiêu ngạo thành nô lệ tình dục trung thành, chuyên phục vụ nhu cầu xác thịt của bạn.",
    "Ép buộc công chúa tộc người phải dâng hiến trinh tiết để được ghi tên vào danh sách hậu cung của bạn.",
    "Dùng 'Thao túng Cảm xúc' để biến sự ghen tuông của các mỹ nhân thành sự thèm khát được bạn nện tập thể.",
    "Trong lâu đài nguy nga, bạn thản nhiên chiếm hữu nữ thần sắc đẹp ngay trước mặt toàn bộ dàn mỹ nhân.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các mỹ nhân ngay giữa buổi dạ hội.",
    "Biến toàn bộ dinh thự thành thiên đường hoan lạc, nơi bạn và các mỹ nhân cùng nhau nện nắc suốt ngày đêm.",
    "Dùng quyền lực vạn giới để ép buộc các nữ anh hùng phải gia nhập nhóm của bạn để được bảo hộ.",
    "Khiến nữ hoàng tộc Elf phải mang thai giọt máu của bạn để củng cố sự liên minh và thống trị của hậu cung.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ hầu thành những con điếm dâm đãng chỉ biết phục vụ bạn.",
    "Lẻn vào phòng ngủ của các mỹ nhân mỗi đêm, dùng dương vật vĩ đại để chinh phục và khiến họ lệ thuộc bạn.",
    "Dùng 'Cường hóa Sinh lý' để có thể phục vụ toàn bộ hậu cung 100 mỹ nhân mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi mỹ nhân trong nhóm đều phải dâng hiến dâm thủy cho bạn mỗi ngày một lần.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân cung điện.",
    "Khiến nữ thần chiến tranh phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chinh phục.",
    "Dùng ma pháp 'Kích dục Harem' khiến mọi mỹ nhân xung quanh đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Harem Dâm uy', nơi mọi mỹ nhân nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ thánh nữ và chiếm hữu nàng bất ngờ.",
    "Khiến nữ kiếm sĩ mạnh nhất vạn tộc phải quỳ xuống phục vụ bạn trên thanh kiếm báu đã bị chinh phục."
  ],
  "Thế giới hiếm đàn ông": [
    "Trong thế giới hiếm đàn ông, bạn yêu cầu nữ tướng quân phải quỳ xuống phục vụ ngay giữa buổi duyệt binh.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp giáp của các nữ chiến binh, chiêm ngưỡng vùng kín.",
    "Biến nữ hoàng của vương quốc thành nô lệ tình dục trung thành, chuyên phục vụ nhu cầu gieo giống của bạn.",
    "Ép buộc các thánh nữ phải dâng hiến trinh tiết để duy trì nòi giống cho toàn nhân loại.",
    "Dùng 'Thao túng Cảm xúc' để biến sự tôn sùng của phái nữ thành sự thèm khát dương vật vĩ đại của bạn.",
    "Trong buổi lễ phồn thực, bạn thản nhiên chiếm hữu nữ tế ti ngay trước mặt hàng ngàn phụ nữ thèm khát.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ quan ngay giữa phố đông.",
    "Biến dinh thự thành trung tâm gieo giống vĩ đại, nơi bạn là vị chúa tể duy nhất chiếm hữu phái nữ.",
    "Dùng sự khan hiếm của bản thân để ép buộc các mỹ nhân tuyệt sắc nhất phải qua đêm với bạn mỗi ngày.",
    "Khiến nữ anh hùng mạnh nhất thế giới phải mang thai giọt máu của bạn để tạo ra thế hệ nam nhân mới.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ vệ sĩ thành những con điếm dâm đãng phục vụ bạn.",
    "Lẻn vào phòng ngủ của các công chúa mỗi đêm, dùng dương vật vĩ đại để chinh phục và khiến họ lệ thuộc.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục hàng trăm phụ nữ mỗi ngày mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi phụ nữ khi trưởng thành đều phải qua tay bạn kiểm tra vùng kín để được gieo giống.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân đối diện.",
    "Khiến nữ thần bảo hộ thế giới phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Toàn cầu' khiến mọi phụ nữ trong vương quốc đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Gieo giống Dâm uy', mọi mỹ nhân nhìn thấy bạn đều muốn được dâng hiến.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ hoàng và chiếm hữu nàng bất ngờ.",
    "Khiến nữ tướng mạnh nhất thế giới phải quỳ xuống phục vụ bạn trên thanh kiếm báu đã bị chinh phục."
  ],

  "Hội Mạo Hiểm Giả": [
    "Tại Hội Mạo Hiểm Giả, bạn yêu cầu nữ tiếp tân xinh đẹp nhất phải quỳ xuống phục vụ ngay tại quầy.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp giáp da của các nữ mạo hiểm giả, chiêm ngưỡng vùng kín.",
    "Biến nữ pháp sư của hội thành nô lệ tình dục trung thành phục vụ nhu cầu sinh lý của bạn mỗi đêm.",
    "Ép buộc nữ kiếm sĩ hạng S kiêu ngạo phải dâng hiến trinh tiết để được bạn dẫn dắt vào hầm ngục.",
    "Dùng 'Thao túng Cảm xúc' để biến sự lạnh lùng của các nữ thợ săn thành sự thèm khát bạn tột độ.",
    "Trong hầm ngục tối tăm, bạn thản nhiên chiếm hữu nữ linh mục ngay trước mặt đám quái vật.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ mạo hiểm giả.",
    "Biến phòng nghỉ của hội thành mật thất hoan lạc, nơi bạn và các mỹ nhân nện nắc suốt ngày đêm.",
    "Dùng danh tiếng để ép buộc các nữ mạo hiểm giả tân thủ phải qua đêm với bạn để được bảo hộ.",
    "Khiến nữ hội trưởng của hội phải mang thai giọt máu của bạn sau khi bị bạn chinh phục và chiếm hữu.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ nhân viên hội thành những con điếm phục vụ bạn.",
    "Lẻn vào phòng tắm của các nữ mạo hiểm giả mỗi đêm, dùng dương vật vĩ đại để chinh phục họ.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục hàng chục mỹ nhân mạo hiểm giả mà không mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ mạo hiểm giả khi hoàn thành nhiệm vụ đều phải dâng hiến dâm thủy cho bạn.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân trong hội.",
    "Khiến nữ anh hùng mạnh nhất hội phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Hội quán' khiến mọi mỹ nhân trong hội đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Hội Mạo Hiểm Dâm uy', mọi mỹ nhân nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ pháp sư và chiếm hữu nàng bất ngờ.",
    "Khiến nữ kiếm sĩ huyền thoại phải quỳ xuống phục vụ bạn trên tấm thẻ mạo hiểm giả đã bị chinh phục."
  ],
  "Lãnh chúa biên thùy": [
    "Là lãnh chúa biên thùy, bạn yêu cầu nữ sĩ quan xinh đẹp nhất phải cởi sạch đồ và phục vụ bạn.",
    "Dùng quyền lực lãnh chúa để biến nữ hiệp sĩ kiêu ngạo thành nô lệ tình dục phục vụ xác thịt.",
    "Lẻn vào phòng tắm của các nữ quan mỗi đêm, dùng dương vật vĩ đại để chinh phục và khiến họ lệ thuộc.",
    "Trong buổi dạ tiệc lãnh địa, bạn thản nhiên sờ soạng vùng kín của các tiểu thư ngay dưới gầm bàn.",
    "Dùng dị năng 'Thấu thị' lãnh chúa để chiêm ngưỡng cơ thể dâm mỹ của mọi nữ nô trong lãnh địa.",
    "Thiết lập một hậu cung gồm toàn những mỹ nhân tuyệt sắc nhất biên giới phục vụ dục vọng bạn.",
    "Yêu cầu nữ tướng quân vương quốc láng giềng phải dâng hiến trinh tiết để đổi lấy sự bảo hộ.",
    "Dùng 'Thao túng Cảm xúc' để biến sự thù ghét của nữ tù binh thành sự thèm khát bạn tột độ.",
    "Tổ chức những buổi tiệc dâm loạn trong mật thất, nơi các sĩ quan và mỹ nhân cùng hoan lạc.",
    "Là vị vua không vương miện, bạn có quyền gieo giống cho bất kỳ nữ nhân nào trong lãnh địa.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên chiếm hữu các nữ quan ngay giữa buổi duyệt binh.",
    "Khiến nữ thánh nữ của giáo hội địa phương phải quỳ xuống phục vụ lãnh chúa ngay trên sàn điện thờ.",
    "Dùng quyền lực để ép buộc nữ thợ săn mạnh nhất vùng phải mang thai giọt máu của bạn củng cố gia tộc.",
    "Lẻn vào phòng ngủ của các nữ sĩ quan mỗi đêm, dùng kỹ năng tuyệt đỉnh để khiến họ lệ thuộc bạn.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ hầu thành những con điếm phục vụ dương vật bạn.",
    "Thiết lập luật lệ: Mọi cô gái xinh đẹp trong lãnh địa khi trưởng thành đều phải qua tay lãnh chúa.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn vùng kín của mọi mỹ nhân trong buổi tiệc.",
    "Khiến nữ hoàng của bộ tộc bại trận phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng 'Cường hóa Sinh lý' lãnh chúa để có thể phục vụ toàn bộ dàn mỹ nhân mà không hề biết mệt mỏi.",
    "Trở thành 'Chúa tể Biên thùy Dâm uy', mọi mỹ nhân nhìn thấy bạn đều tự động phát tình."
  ],
  "Kẻ trộm thánh vật": [
    "Là kẻ trộm thánh vật, bạn yêu cầu nữ thánh nữ phải cởi sạch đồ và phục vụ để đổi lấy vật báu.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp y phục của các nữ tu sĩ, chiêm ngưỡng vùng kín.",
    "Biến nữ giáo hoàng kiêu ngạo thành nô lệ tình dục trung thành phục vụ nhu cầu xác thịt của bạn.",
    "Ép buộc nữ hiệp sĩ thánh điện phải dâng hiến trinh tiết để được bạn trả lại thánh vật đã tráo.",
    "Dùng 'Thao túng Cảm xúc' để biến sự thánh khiết của các nữ tu thành sự thèm khát bạn tột độ.",
    "Trong thánh điện tối cao, bạn thản nhiên chiếm hữu nữ thánh nữ ngay trước mặt tượng thần linh.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ tu ngay giữa đại lễ.",
    "Biến sào huyệt thành thiên đường hoan lạc, nơi bạn và các mỹ nhân thánh khiết cùng nện nắc.",
    "Dùng sự tinh quái để ép buộc các nữ hiệp sĩ phải qua đêm với bạn để lấy lại vật báu giáo hội.",
    "Khiến nữ giáo hoàng phải mang thai giọt máu của bạn để bôi nhọ sự thánh khiết và thống trị giáo hội.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ tu thành những con điếm phục vụ dương vật bạn.",
    "Lẻn vào phòng ngủ của các thánh nữ mỗi đêm, dùng dương vật vĩ đại để chinh phục họ.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục hàng chục mỹ nhân thánh khiết mà không mệt mỏi.",
    "Thiết lập luật lệ: Mọi thánh vật bị trộm đều có thể chuộc lại bằng dâm thủy và sự dâng hiến thể xác.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân thánh điện.",
    "Khiến nữ thần bảo hộ giáo hội phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Thánh điện' khiến mọi mỹ nhân giáo hội đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Đạo tặc Dâm uy', mọi mỹ nhân nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ giáo hoàng và chiếm hữu nàng bất ngờ.",
    "Khiến nữ thánh nữ cao quý nhất phải quỳ xuống phục vụ bạn trên thánh vật đã bị bạn chinh phục."
  ],
  "Pháp sư tối thượng": [
    "Là pháp sư tối thượng, bạn yêu cầu nữ hiệu trưởng học viện phải quỳ xuống phục vụ ngay trong phòng làm việc.",
    "Dùng ma pháp 'Thấu thị' để nhìn xuyên qua lớp áo choàng của các nữ pháp sư, chiêm ngưỡng vùng kín.",
    "Biến nữ phù thủy mạnh nhất lục địa thành nô lệ tình dục trung thành phục vụ nhu cầu của bạn.",
    "Ép buộc nữ pháp sư tập sự phải dâng hiến trinh tiết để được bạn truyền dạy ma pháp tối thượng.",
    "Dùng 'Thao túng Cảm xúc' để biến sự lạnh lùng của nữ phù thủy thành sự thèm khát bạn tột độ.",
    "Trong thư viện cấm, bạn thản nhiên chiếm hữu nữ pháp sư ngay trên những cuốn sách cổ đại.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ pháp sư giữa hội thảo.",
    "Biến tháp ma pháp thành thiên đường hoan lạc, nơi bạn và các mỹ nhân cùng nện nắc suốt đêm.",
    "Dùng quyền năng tối thượng để ép buộc các nữ pháp sư phải qua đêm với bạn để tăng cường ma lực.",
    "Khiến nữ hiệu trưởng học viện phải mang thai giọt máu của bạn để củng cố sự thống trị học viện.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ pháp sư thành những con điếm phục vụ dương vật bạn.",
    "Lẻn vào phòng tắm của các mỹ nhân ma pháp mỗi đêm, dùng dương vật vĩ đại để chinh phục họ.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục hàng chục nữ pháp sư mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ pháp sư khi đột phá cảnh giới đều phải dâng hiến dâm thủy cho bạn.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi nữ pháp sư.",
    "Khiến nữ thần ma pháp phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Ma pháp' khiến mọi mỹ nhân xung quanh đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Pháp sư Dâm uy', mọi mỹ nhân nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ phù thủy và chiếm hữu nàng bất ngờ.",
    "Khiến nữ pháp sư mạnh nhất phải quỳ xuống phục vụ bạn trên cây trượng ma pháp đã bị chinh phục."
  ],
  "Học Viện Hoàng Gia": [
    "Tại Học Viện Hoàng Gia, bạn yêu cầu nữ hội trưởng học sinh phải quỳ xuống phục vụ ngay giữa hành lang.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp đồng phục của các nữ sinh quý tộc, chiêm ngưỡng vùng kín.",
    "Biến nữ giáo sư xinh đẹp thành nô lệ tình dục trung thành phục vụ nhu cầu sinh lý của bạn.",
    "Ép buộc tiểu thư nhà công tước kiêu ngạo phải dâng hiến trinh tiết để được bạn giúp đỡ kỳ thi.",
    "Dùng 'Thao túng Cảm xúc' để biến sự khinh miệt của các nữ sinh thành sự thèm khát bạn tột độ.",
    "Trong thư viện học viện, bạn thản nhiên chiếm hữu nữ sinh quý tộc ngay trước mặt các học viên.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ sinh giữa lễ khai giảng.",
    "Biến ký túc xá nữ thành thiên đường hoan lạc, nơi bạn và các mỹ nhân quý tộc cùng nện nắc suốt đêm.",
    "Dùng danh tiếng để ép buộc các nữ sinh phải qua đêm với bạn để được gia nhập tổ đội mạnh nhất.",
    "Khiến nữ hội trưởng học sinh phải mang thai giọt máu của bạn để củng cố địa vị trong học viện.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ sinh thành những con điếm phục vụ dương vật bạn.",
    "Lẻn vào phòng tắm nữ mỗi đêm, dùng dương vật vĩ đại để chinh phục các tiểu thư quý tộc.",
    "Dùng 'Cường hóa Sinh lý' để có thể phục vụ toàn bộ dàn nữ sinh xinh đẹp mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ sinh khi đạt thành tích xuất sắc đều phải dâng hiến dâm thủy cho nam thần học viện.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân học viện.",
    "Khiến nữ giáo hoàng tương lai phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Học đường' khiến mọi nữ sinh xung quanh đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Học viện Dâm uy', mọi mỹ nhân nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ giáo sư và chiếm hữu nàng bất ngờ.",
    "Khiến nữ kiếm sĩ mạnh nhất học viện phải quỳ xuống phục vụ bạn trên thanh kiếm báu đã bị chinh phục."
  ],
  "Chợ nô lệ": [
    "Tôi có vô hạn tiền, nhưng tiền này chỉ mua được nô lệ ở chợ nô lệ, những nữ nô lệ từ nhiều thời kì, mang trong mình những quyền năng mạnh mẽ bị khóa lại, bị phong ấn hay vì những lí do khác mà không ai có thể hóa giải cho họ được. Có tiền nhưng muốn mua đồ cũng không có vì thế giới đã quá suy tàn.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp vải rách của các nữ nô lệ, chiêm ngưỡng vùng kín.",
    "Biến nữ chủ nô tàn bạo thành nô lệ tình dục trung thành phục vụ nhu cầu xác thịt của bạn.",
    "Ép buộc công chúa vương quốc bại trận phải dâng hiến trinh tiết để được bạn mua về bảo vệ.",
    "Dùng 'Thao túng Cảm xúc' để biến sự nhục nhã của các nữ nô lệ thành sự thèm khát bạn tột độ.",
    "Trong hầm ngục nô lệ, bạn thản nhiên chiếm hữu nữ vương quỷ ngay trước mặt đám lính canh.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ nô lệ giữa buổi đấu giá.",
    "Biến dinh thự thành thiên đường hoan lạc, nơi bạn và các mỹ nhân nô lệ cùng nện nắc suốt ngày đêm.",
    "Dùng sự giàu có để ép buộc các nữ nô lệ xinh đẹp nhất phải qua đêm với bạn để được hưởng đặc quyền.",
    "Khiến nữ hoàng bị bắt làm nô lệ phải mang thai giọt máu của bạn để củng cố sự thống trị tuyệt đối.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ nô lệ thành những con điếm phục vụ dương vật bạn.",
    "Lẻn vào khu hầm ngục nô lệ mỗi đêm, dùng dương vật vĩ đại để chinh phục các mỹ nhân lệ thuộc.",
    "Dùng 'Cường hóa Sinh lý' để có thể phục vụ toàn bộ dàn mỹ nhân nô lệ mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ nô lệ mới đều phải qua tay bạn kiểm tra vùng kín trước khi định giá.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân chợ nô lệ.",
    "Khiến nữ thần bảo hộ bộ tộc nô lệ phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Chợ Nô' khiến mọi mỹ nhân xung quanh đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Nô lệ Dâm uy', mọi mỹ nhân bị xiềng xích nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ chủ nô và chiếm hữu nàng bất ngờ.",
    "Khiến nữ chiến binh nô lệ mạnh nhất phải quỳ xuống phục vụ bạn trên chiếc xiềng xích đã bị chinh phục."
  ],
  "Thế giới Nữ Tôn Fantasy": [
    "Trong thế giới Nữ Tôn, bạn yêu cầu nữ vương phải quỳ xuống phục vụ ngay trên ngai vàng uy nghiêm.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp y phục của các nữ lãnh chúa, chiêm ngưỡng vùng kín.",
    "Biến nữ tướng quân mạnh nhất vương quốc thành nam sủng tình dục phục vụ nhu cầu của bạn mỗi đêm.",
    "Ép buộc công chúa xinh đẹp nhất phải dâng hiến trinh tiết để được bạn ban phước gieo giống.",
    "Dùng 'Thao túng Cảm xúc' để biến sự kiêu ngạo của các nữ quan thành sự thèm khát bạn tột độ.",
    "Trong cung điện Nữ Tôn, bạn thản nhiên chiếm hữu nữ lãnh chúa ngay trước mặt dàn nam sủng.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các mỹ nhân giữa lễ sắc phong.",
    "Biến tẩm cung thành thiên đường hoan lạc, nơi bạn và các nữ quan cùng nện nắc suốt ngày đêm.",
    "Dùng sự quý hiếm của bản thân để ép buộc các nữ chiến binh mạnh nhất phải qua đêm với bạn.",
    "Khiến nữ vương vương quốc Nữ Tôn phải mang thai giọt máu của bạn để củng cố địa vị nam nhân.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ vệ sĩ thành những con điếm phục vụ dương vật bạn.",
    "Lẻn vào phòng tắm của các công chúa mỗi đêm, dùng dương vật vĩ đại để chinh phục họ.",
    "Dùng 'Cường hóa Sinh lý' để có thể phục vụ toàn bộ dàn mỹ nhân cung điện Nữ Tôn mà không mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ quan khi thăng chức đều phải qua tay bạn kiểm tra vùng kín để được gieo giống.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân Nữ Tôn.",
    "Khiến nữ thần bảo hộ vương quốc phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Nữ Tôn' khiến mọi mỹ nhân xung quanh đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Nam Sủng Dâm uy', mọi nữ lãnh chúa nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ vương và chiếm hữu nàng bất ngờ.",
    "Khiến nữ tướng quân mạnh nhất phải quỳ xuống phục vụ bạn trên thanh kiếm báu đã bị chinh phục."
  ],
  "Khan hiếm đàn ông (Epic)": [
    "Trong thế giới khan hiếm đàn ông quy mô Epic, bạn yêu cầu nữ hoàng vạn tộc phải quỳ xuống phục vụ ngay giữa đại hội.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp y phục của các nữ vương vạn tộc, chiêm ngưỡng vùng kín.",
    "Biến nữ thần vạn giới thành nô lệ tình dục trung thành phục vụ nhu cầu gieo giống của bạn.",
    "Ép buộc các nữ hoàng xinh đẹp nhất phải dâng hiến trinh tiết để duy trì nòi giống cho vạn tộc.",
    "Dùng 'Thao túng Cảm xúc' để biến sự tôn sùng của phái nữ thành sự thèm khát dương vật vĩ đại của bạn.",
    "Trong thánh địa vạn tộc, bạn thản nhiên chiếm hữu nữ vương ngay trước mặt hàng ngàn mỹ nhân.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ hoàng giữa yến tiệc.",
    "Biến dinh thự thành trung tâm gieo giống vĩ đại, nơi bạn là vị chúa tể duy nhất chiếm hữu phái nữ.",
    "Dùng sự khan hiếm tuyệt đối để ép buộc các mỹ nhân vạn tộc phải qua đêm với bạn để được gieo giống.",
    "Khiến nữ thần bảo hộ vạn giới phải mang thai giọt máu của bạn để tạo ra thế hệ nam nhân mới.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ vệ sĩ vạn tộc thành những con điếm phục vụ bạn.",
    "Lẻn vào phòng ngủ của các nữ vương mỗi đêm, dùng dương vật vĩ đại để chinh phục họ lệ thuộc.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục hàng ngàn phụ nữ vạn tộc mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ hoàng khi lên ngôi đều phải qua tay bạn kiểm tra vùng kín chính thống.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân vạn tộc.",
    "Khiến nữ thần chiến tranh vạn giới phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Vạn Tộc' khiến mọi phụ nữ vạn giới đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Gieo giống Vạn Tộc', mọi mỹ nhân nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ hoàng và chiếm hữu nàng bất ngờ.",
    "Khiến nữ chiến binh mạnh nhất vạn tộc phải quỳ xuống phục vụ bạn trên thanh kiếm thánh đã bị chinh phục."
  ],
  "Thế giới tôn thờ dương vật": [
    "Trong thế giới tôn thờ dương vật, bạn thản nhiên yêu cầu nữ hoàng phải quỳ xuống bú cu ngay trên điện thờ tối cao.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp y phục thánh khiết của các nữ tư tế, chiêm ngưỡng vùng kín dâm mị rỉ nước.",
    "Biến nữ lãnh chủ bộ tộc kiêu ngạo thành một nô lệ tình dục trung thành tuyệt đối, chuyên phục vụ nhu cầu xác thịt của bạn.",
    "Ép buộc các nữ chiến binh mạnh nhất phải dâng hiến trinh tiết quý giá để được ban phước và tăng cường linh lực thần thánh.",
    "Dùng 'Thao túng Cảm xúc' để biến sự sùng bái của phái nữ thành sự thèm khát dương vật vĩ đại của bạn tột độ.",
    "Trong lễ hội tôn vinh dương vật trang nghiêm, bạn thản nhiên nện nắc nữ tư tế ngay trước mặt hàng ngàn mỹ nhân đang cầu nguyện.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ quan ngay giữa buổi đại lễ phồn thực.",
    "Biến thánh địa của bộ tộc thành một thiên đường hoan lạc, nơi bạn và các mỹ nhân cùng nhau nện nắc suốt ngày đêm không nghỉ.",
    "Dùng địa vị thần linh của bản thân để ép buộc các mỹ nhân tuyệt sắc nhất phải qua đêm với bạn để được cứu rỗi linh hồn.",
    "Khiến nữ hoàng bộ tộc phải mang thai giọt máu của bạn để tạo ra một thế hệ nam nhân mới đầy sức mạnh thần thánh.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ tu sĩ thành những con điếm dâm đãng chỉ biết phục vụ dương vật bạn.",
    "Lẻn vào phòng ngủ của các nữ tư tế mỗi đêm, dùng dương vật vĩ đại để chinh phục và khiến họ hoàn toàn lệ thuộc vào bạn.",
    "Dùng 'Cường hóa Sinh lý' thần thánh để có thể nện liên tục hàng trăm phụ nữ mỗi ngày mà không hề biết mệt mỏi hay kiệt sức.",
    "Thiết lập luật lệ: Mọi phụ nữ khi trưởng thành đều phải qua tay bạn 'kiểm tra chất lượng' vùng kín để được ban phước gieo giống.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y ren và vùng kín của mọi mỹ nhân trong thánh địa nguy nga.",
    "Khiến nữ thần bảo hộ thế giới phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu và vấy bẩn thể xác.",
    "Dùng ma pháp 'Kích dục Thần thánh' khiến mọi phụ nữ trong vương quốc đều cảm thấy nứng và khao khát được bạn nện nắc.",
    "Trở thành 'Chúa tể Dâm uy Tối cao', nơi mọi mỹ nhân nhìn thấy bạn đều tự động phát tình và muốn được dâng hiến thân xác.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ hoàng và nện nàng bất ngờ trong sự hoảng loạn dâm đãng.",
    "Khiến nữ tướng mạnh nhất bộ tộc phải quỳ xuống liếm sạch tinh dịch của bạn trên thanh kiếm thánh đã bị bạn chinh phục."
  ],
  "Thần linh hạ phàm": [
    "Là thần linh hạ phàm, bạn thản nhiên yêu cầu nữ hoàng phải quỳ xuống bú cu ngay giữa điện thờ thánh thiện.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua mọi lớp y phục thánh của các nữ thần, chiêm ngưỡng vùng kín dâm mị rỉ nước.",
    "Biến nữ tư tế cao quý nhất thành nô lệ tình dục, chuyên phục vụ nhu cầu ban phước xác thịt của bạn mỗi đêm.",
    "Ép buộc các thánh nữ phải dâng hiến trinh tiết để nhận được sự che chở thần thánh từ vị thần dâm dục là bạn.",
    "Dùng 'Thao túng Cảm xúc' để biến sự sùng bái của các nữ thần thành sự thèm khát dương vật vĩ đại của bạn tột độ.",
    "Trong thánh địa trang nghiêm, bạn thản nhiên nện nắc nữ thần sắc đẹp ngay trước mặt hàng vạn tín đồ đang quỳ lạy.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các mỹ nhân ngay giữa buổi lễ tế thần.",
    "Biến điện thờ của bạn thành một thiên đường hoan lạc, nơi bạn là vị thần duy nhất được mọi mỹ nhân dâng hiến thân xác.",
    "Dùng quyền năng thần thánh để ép buộc các nữ hoàng phải qua đêm với bạn để được 'ban phước' gieo giống thần linh.",
    "Khiến nữ thần bảo hộ thế giới phải mang thai giọt máu của bạn để tạo ra một kỷ nguyên mới thống trị bởi sắc dục.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ thiên sứ thành những con điếm dâm đãng chỉ biết phục vụ dương vật bạn.",
    "Lẻn vào phòng ngủ của các nữ thần mỗi đêm, dùng dương vật vĩ đại để chinh phục và khiến họ hoàn toàn lệ thuộc vào bạn.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục hàng trăm mỹ nhân thiên giới mỗi ngày mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ thần khi hạ phàm đều phải qua tay bạn 'kiểm tra linh lực' vùng kín để được ban phước.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y ren và vùng kín của mọi mỹ nhân trong thiên giới nguy nga.",
    "Khiến nữ thần tối cao phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu và vấy bẩn thể xác thần thánh.",
    "Dùng ma pháp 'Kích dục Thiên giới' khiến mọi mỹ nhân xung quanh đều cảm thấy nứng và khao khát được bạn nện nắc.",
    "Trở thành 'Chúa tể Thiên giới Dâm uy', nơi mọi mỹ nhân nhìn thấy bạn đều tự động phát tình và muốn được dâng hiến.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ thần mặt trăng và nện nàng bất ngờ trong sự hoảng loạn.",
    "Khiến nữ thần chiến tranh phải quỳ xuống liếm sạch tinh dịch của bạn trên thanh kiếm thánh đã bị bạn chinh phục."
  ],
  "Chuyển sinh thành NPC": [
    "Tình cờ va phải nữ anh hùng khi nàng đang vội vã đi làm nhiệm vụ cứu thế.",
    "Trong quán trọ, bạn tình cờ được nữ pháp sư nhờ mang nước ấm lên phòng tắm.",
    "Tình cờ nhặt được túi tiền của nữ mạo hiểm giả hạng S đánh rơi giữa chợ.",
    "Va phải nữ tu sĩ ở cổng thành, làm nàng rơi chiếc gậy phép thánh khiết.",
    "Tình cờ bắt gặp nữ sát thủ đang lẩn trốn trong đống rơm sau nhà bạn.",
    "Trong rừng, bạn tình cờ thấy nữ thợ săn đang loay hoay gỡ bẫy bị vướng vào chân.",
    "Tình cờ cứu được tiểu thư quý tộc khi xe ngựa của nàng bị hỏng bánh giữa đường.",
    "Nữ anh hùng bị trúng lời nguyền 'Dâm Đãng', nàng lao vào nhà bạn cầu xin được nện.",
    "Lọ thuốc ma thuật của nữ pháp sư phát nổ, làm quần áo của nàng tan biến ngay tại quán trọ.",
    "Cơn mưa bất chợt làm y phục của nữ tu sĩ trở nên trong suốt, lộ ra cơ thể dâm mỹ.",
    "Bẫy dâm dục trong rừng kích hoạt, trói chặt bạn và nữ thợ săn trong tư thế giao hợp.",
    "Sự cố dịch chuyển đưa nữ sát thủ rơi thẳng vào bồn tắm khi bạn đang khỏa thân.",
    "Nữ anh hùng lén lút lẻn vào phòng bạn mỗi đêm để tìm kiếm sự an ủi xác thịt bình dị.",
    "Nữ pháp sư lén lút dùng ma pháp để khiến bạn ngủ say rồi bò vào giường bú cu cho bạn.",
    "Nữ tu sĩ lén lút thu thập tinh dịch của bạn để làm 'thánh vật' thỏa mãn dục vọng thầm kín.",
    "Tiểu thư quý tộc lén lút nhìn trộm bạn làm việc qua cửa sổ, tay nàng không ngừng xoa lồn.",
    "Nữ sát thủ lén lút gửi những bức thư tình dâm đãng kèm theo quần lót ren cho bạn.",
    "Bạn chỉ là một nhân vật phụ không tên tuổi trong thế giới của những anh hùng và ma vương.",
    "Tuy nhiên, chính sự bình thường của bạn lại là thứ thu hút những mỹ nhân đang mệt mỏi vì chiến đấu.",
    "Thế giới này coi trọng sức mạnh, nhưng dục vọng lại là thứ san bằng mọi khoảng cách giai cấp.",
    "Các nữ anh hùng thường tìm đến những NPC như bạn để giải tỏa áp lực và tìm kiếm khoái lạc.",
    "Sự tồn tại của bạn là một biến số không ngờ tới trong kịch bản của thế giới này.",
    "Những ngôi làng nhỏ thường là nơi ẩn náu của những mỹ nhân đang chạy trốn khỏi định mệnh.",
    "NPC cũng có thể trở thành bá chủ nếu biết cách chinh phục trái tim và thể xác của các nữ chính.",
    "[HỆ THỐNG]: Nhiệm vụ: Biến nữ anh hùng thành người phụ nữ của riêng bạn trước khi nàng tiêu diệt ma vương.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa kỹ năng 'NPC Nghịch Thiên', tăng 300% khả năng gieo giống.",
    "[HỆ THỐNG]: Cảnh báo: Nữ pháp sư đang có ý định dùng ma pháp để bắt cóc bạn về làm nô lệ tình dục.",
    "Dùng dị năng 'Thấu Thị' để thản nhiên ngắm nhìn vùng kín của các nữ mạo hiểm giả ghé qua quán trọ.",
    "Dị năng 'Cường Hóa Sinh Lực' giúp bạn có thể nện nắc nữ anh hùng suốt đêm mà không mệt mỏi.",
    "Sử dụng dị năng 'Thao Túng Cảm Xúc' để biến sự kiêu ngạo của tiểu thư thành sự sùng bái bạn.",
  ],
  "Hệ Thống Làm Giàu Fantasy": [
    "Bạn sở hữu 'Hệ Thống Giao Dịch Vạn Giới', có thể dùng vàng để mua mọi trang bị huyền thoại và mỹ nhân nô lệ.",
    "Hệ thống tặng bạn một 'Mỏ Kim Cương Vô Hạn', giúp bạn trở thành người giàu nhất lục địa, thâu tóm mọi vương quốc.",
    "Bạn dùng số tiền khổng lồ để thuê toàn bộ các mạo hiểm giả cấp S bảo vệ mình, biến các nữ anh hùng thành người hầu.",
    "Hệ thống 'Thần Hào Dị Giới' giúp bạn nhận được phản hồi tài sản gấp 100 lần khi đầu tư vào các mỹ nhân.",
    "[HỆ THỐNG]: Thông báo: Bạn đã trở thành hoàng đế tài chính của lục địa. Kích hoạt kỹ năng 'Sức Mạnh Đồng Tiền'.",
  ],
  "Dị Năng Đổi Đời Mạo Hiểm Giả": [
    "Dị năng 'Nhìn thấu kho báu' giúp bạn luôn tìm thấy những di tích cổ đại chứa đầy vàng bạc, đổi đời thành đại phú gia.",
    "Bạn dùng dị năng 'Thao túng vận mệnh' để khiến các nữ vương phải dâng hiến toàn bộ ngân khố và bản thân cho mình.",
    "Dị năng 'Tạo ra vàng ròng' giúp bạn sở hữu nguồn tài chính vô hạn, khiến mọi nữ mạo hiểm giả phải quỳ lạy xin được gia nhập tổ đội.",
    "Bạn dùng sức mạnh của mình để thâu tóm mọi nguồn lực kinh tế trong thế giới fantasy, biến những công chúa kiêu ngạo nhất thành nô lệ.",
    "[HỆ THỐNG]: Cảnh báo: Sự giàu sang của bạn đang bị các nữ tặc dòm ngó. Hãy dùng tiền để thu phục họ ngay.",
  ],
  "Nữ Chủ Fantasy (Low NSFW/Lesbian)": [
    "Bạn là một nữ mạo hiểm giả tài năng, sở hữu 'Hệ Thống Nữ Thần', nhiệm vụ của bạn là chinh phục trái tim của các nữ đồng đội và công chúa xinh đẹp nhất.",
    "Bạn sở hữu hệ thống 'Nữ Chủ Harem', giúp bạn thu thập những mỹ nhân fantasy mạnh nhất vào hậu cung của mình.",
    "Bạn là một nữ sát thủ tộc người, dùng sắc đẹp và kỹ năng để thâm nhập vào các tổ chức và chiếm hữu các nữ lãnh đạo.",
    "Trong một vương quốc xa xôi, bạn là nữ vương của một đế chế chỉ có phụ nữ, đang nỗ lực bảo vệ thần dân khỏi các cuộc xâm lăng.",
    "Hệ thống 'Nữ Chủ Chinh Phục' giao nhiệm vụ cho bạn phải thu phục trái tim của 3 nàng thánh nữ cao quý nhất.",
  ],
  "Hành Trình Tự Do Fantasy (Gender Neutral - SFW)": [
    "Bạn là một người lữ hành không tên, đi khắp các vùng đất kỳ ảo để khám phá vẻ đẹp của thiên nhiên và văn hóa các chủng tộc.",
    "Trong một thế giới ma thuật, bạn là một người thợ sửa chữa những món đồ cổ đại, mang lại niềm vui cho mọi người từ những điều nhỏ nhặt.",
    "Bạn sở hữu một quán trọ nhỏ bên bìa rừng, nơi đón tiếp những mạo hiểm giả mệt mỏi và lắng nghe những câu chuyện về các vùng đất xa lạ.",
    "Bạn là một người bảo vệ những khu rừng già, dùng kiến thức của mình để bảo tồn sự cân bằng của tự nhiên khỏi những tác động xấu.",
    "Bạn là một nhà nghiên cứu về các sinh vật huyền bí, đi khắp thế giới để tìm kiếm sự thật và hướng tới một tương lai tốt đẹp hơn.",
  ],
};

export const IDENTITIES: string[] = Object.entries(RAW_DATA).flatMap(([context, scenarios]) => 
  scenarios.map(s => `Bối cảnh: ${context} - ${s}`)
);

export const SPECIALIZED_DATA: Record<string, { label: string, action: string }[]> = {};
