
export const RAW_DATA: Record<string, string[]> = {
  "Hệ thống": [
    "Hệ Thống gánh con.",

  ],
  "Minh Chủ Phủ Đệ": [
    "Bạn là một môn khách trong Minh Chủ Phủ Đệ, mang tham vọng lật đổ Minh chủ giả tạo và chiếm hữu toàn bộ nữ quyến của ông ta.",
    "Phủ đệ này là biểu tượng của chính đạo, nhưng bên trong lại chứa đầy những âm mưu đen tối và dục vọng kìm nén của các nữ đệ tử.",
    "Mục tiêu của bạn là chinh phục tiểu thư minh chủ, người nắm giữ vẻ đẹp thánh khiết và quyền thừa kế phủ đệ vĩ đại này.",
    "Trong những hành lang uy nghiêm, bạn đang âm thầm gieo rắc những mầm mống dục vọng để tha hóa toàn bộ giới chính đạo.",
    "Bạn thề sẽ khiến phu nhân minh chủ cao quý phải quỳ xuống bú cu mình ngay trong chính phòng ngủ của chồng bà ta.",
    "Mỗi buổi luyện công đều là cơ hội để bạn tiếp cận và mơn trớn những cơ thể tuyệt mỹ đang khao khát hơi ấm nam nhi.",
    "Phủ đệ này sẽ sớm trở thành một trang trại gieo giống bí mật, nơi bạn là vị chủ nhân thực sự của mọi mỹ nhân chính phái.",
    "Trong lúc luyện tập, bạn vô tình bắt gặp tiểu thư đang khỏa thân tắm trong hồ sen sau phủ, làn da trắng ngần của nàng tỏa sáng.",
    "Bạn nhặt được một cuốn bí kíp song tu bị thất lạc của Minh chủ, bên trong chứa những hình vẽ dâm mị khiến bạn phát cuồng.",
    "Tình cờ nghe thấy tiếng rên rỉ phát ra từ thư phòng, nơi phu nhân minh chủ đang lén lút tự thỏa mãn vì bị chồng bỏ rơi.",
    "Đang đi trong vườn hoa, bạn va phải một nữ đệ tử nội môn, đôi vú căng tròn của nàng ép chặt vào người bạn đầy kích thích.",
    "Bạn tìm thấy một lối đi ngầm dẫn thẳng vào phòng tắm của các nữ quyến, nơi bạn có thể thản nhiên quan sát họ khỏa thân.",
    "Trong buổi đại hội võ lâm, bạn tình cờ bắt gặp ánh mắt thèm khát của một nữ hiệp khách đang nhìn chằm chằm vào háng bạn.",
    "Bạn vô tình chạm vào một cơ quan bí mật, mở ra một căn phòng chứa đầy những dụng cụ dâm dục mà Minh chủ lén lút cất giữ.",
  ],
  "Ảnh Các Mật Thất": [
    "Bạn là một sát thủ cấp cao trong Ảnh Các, mang tham vọng lật đổ thủ lĩnh và biến toàn bộ nữ sát thủ thành sủng vật của mình.",
    "Mật thất này là nơi chứa đựng những bí mật đen tối nhất của giới võ lâm, nơi nhục dục và cái chết luôn đi đôi với nhau.",
    "Mục tiêu của bạn là thu phục nữ thủ lĩnh Ảnh Các, người nắm giữ vẻ đẹp lạnh lùng và quyền năng điều khiển mạng lưới sát thủ.",
    "Trong bóng tối của hầm ngục, bạn đang âm thầm xây dựng một vương quốc dục vọng nơi các nữ sát thủ đều phải quỳ phục.",
    "Bạn thề sẽ khiến mọi nữ gián điệp kiêu ngạo khi bị bắt vào đây đều phải trở thành những nô lệ tình dục dâm đãng nhất.",
    "Mỗi cuộc tra tấn đều là cơ hội để bạn khám phá những điểm nhạy cảm nhất trên cơ thể của các mỹ nhân bại trận.",
    "Ảnh Các sẽ sớm trở thành một trang trại gieo giống đen tối, nơi bạn là vị chúa tể duy nhất được hưởng thụ vạn nữ sát thủ.",
    "Trong lúc làm nhiệm vụ, bạn vô tình bắt gặp một nữ sát thủ đối thủ đang khỏa thân tắm rửa bên dòng suối ngầm trong hang động.",
    "Bạn nhặt được một mảnh vỡ của ma khí cổ đại, khi kích hoạt nó tỏa ra làn khói hồng khiến nữ gián điệp bên cạnh bỗng nhiên phát tình.",
    "Tình cờ thấy nữ thủ lĩnh đang lén lút tự thỏa mãn bằng một thanh đoản kiếm hình dương vật trong mật thất đầy ám khí.",
    "Đang đi trong hành lang tối, bạn va phải một nữ sát thủ đang vội vã, đôi vú săn chắc của nàng ép chặt vào người bạn đầy kích thích.",
    "Bạn tìm thấy một lối đi bí mật dẫn thẳng vào phòng ngủ của các nữ sát thủ, nơi bạn có thể thản nhiên quan sát họ khỏa thân.",
    "Trong buổi hiến tế, bạn tình cờ bắt gặp ánh mắt thèm khát của một nữ sát thủ đang nhìn chằm chằm vào dương vật đang cương cứng của bạn.",
    "Bạn vô tình chạm vào một cơ quan bí mật, mở ra một căn phòng chứa đầy những nữ nô lệ đang bị xích trong tư thế mời gọi.",
  ],
  "Vạn Hoa Cốc": [
    "Bạn là một đệ tử trong Vạn Hoa Cốc, mang tham vọng chiếm hữu toàn bộ các tiên nữ trong thung lũng và trở thành chủ nhân của thánh địa này.",
    "Thung lũng này tràn ngập hương hoa kích dục và những bí mật võ học viễn cổ, nơi nhục dục và tiên khí hòa quyện làm một.",
    "Mục tiêu của bạn là chinh phục nữ sư phụ nghiêm khắc, người nắm giữ vẻ đẹp mặn mà và kỹ năng võ học đỉnh cao của môn phái.",
    "Trong những rừng hoa mộng ảo, bạn đang âm thầm gieo rắc những mầm mống dục vọng để biến các tiên nữ thành dâm phụ.",
    "Bạn thề sẽ khiến tiểu sư muội ngây thơ phải quỳ xuống bú cu mình ngay trên thảm cỏ thơm ngát của thung lũng.",
    "Mỗi buổi luyện công đều là cơ hội để bạn tiếp cận và mơn trớn những cơ thể tuyệt mỹ đang khao khát hơi ấm nam nhi.",
    "Vạn Hoa Cốc sẽ sớm trở thành một thiên đường hoan lạc, nơi bạn là vị vua duy nhất được hưởng thụ vạn tiên nữ.",
    "Trong lúc hái thuốc, bạn vô tình bắt gặp tiểu sư muội đang khỏa thân tắm suối, làn da trắng nõn của nàng tỏa sáng dưới nắng.",
    "Bạn nhặt được một đóa 'Dâm Hoa' quý hiếm, khi ngửi thấy mùi hương của nó, sư tỷ đi cùng bỗng nhiên muốn được bạn chiếm hữu.",
    "Tình cờ thấy nữ sư phụ đang lén lút tự thỏa mãn bằng một nhụy hoa khổng lồ trong tẩm cung đầy hương sắc.",
    "Đang đi trong rừng hoa, bạn va phải một nữ đệ tử nội môn, đôi vú căng tròn của nàng ép chặt vào người bạn đầy kích thích.",
    "Bạn tìm thấy một lối đi bí mật dẫn thẳng vào phòng tắm của các tiên nữ, nơi bạn có thể thản nhiên quan sát họ khỏa thân.",
    "Trong buổi lễ hội hoa, bạn tình cờ bắt gặp ánh mắt thèm khát của một nữ hiệp đang nhìn chằm chằm vào háng bạn.",
    "Bạn vô tình chạm vào một đóa hoa bẫy, khiến nó phun ra làn khói hồng làm tan chảy toàn bộ quần áo của bạn và nữ đối phương.",
  ],
  "U Minh Giáo Địa Ngục": [
    "Bạn là một ma tu trong U Minh Giáo, mang tham vọng lật đổ giáo chủ và biến toàn bộ thánh nữ chính đạo thành nô lệ tình dục của mình.",
    "Địa ngục này là nơi chứa đựng oán khí và dục vọng đen tối, nơi ma tính và nhục dục hòa quyện làm một.",
    "Mục tiêu của bạn là bắt giữ các thánh nữ chính đạo, ném họ vào hầm ngục để biến họ thành những dâm phụ dâm đãng nhất.",
    "Trong bóng tối của giáo phái, bạn đang âm thầm xây dựng một đế chế hoan lạc nơi các nữ hiệp đều phải quỳ phục.",
    "Bạn thề sẽ khiến thánh nữ Nga Mi phải quỳ xuống liếm mút dương vật nhầy nhụa ma dịch của mình trước mặt vạn quân.",
    "Mỗi cuộc tra tấn đều là cơ hội để bạn tha hóa tâm hồn và thể xác của những mỹ nhân thanh cao nhất giang hồ.",
    "U Minh Giáo sẽ sớm trở thành một trang trại gieo giống đen tối, nơi bạn là vị chúa tể duy nhất được hưởng thụ vạn mỹ nhân.",
    "Trong lúc luyện công, bạn vô tình bắt gặp thánh nữ chính đạo bị bắt giam đang khỏa thân tắm rửa để tẩy trần ma khí.",
    "Bạn nhặt được một mảnh vỡ của ma khí cổ đại, khi kích hoạt nó tỏa ra làn khói hồng khiến nữ hộ pháp bên cạnh bỗng nhiên phát tình.",
    "Tình cờ thấy nữ hộ pháp đang lén lút dùng máu của các trinh nữ để dưỡng da, bạn dùng điều này để ép nàng phải phục vụ mình.",
    "Đang đi trong hang động tối, bạn va phải một nữ tiên tử chính đạo đang tìm cách bỏ trốn, đôi vú trắng nõn của nàng đập thẳng vào mặt bạn.",
    "Bạn tìm thấy một lối đi bí mật dẫn vào tẩm cung của Ma Hậu, nơi nàng đang khỏa thân tế lễ trước một tượng thần dâm dục.",
    "Trong buổi hiến tế, bạn tình cờ bắt gặp ánh mắt thèm khát của một nữ ma tu đang nhìn chằm chằm vào dương vật đang cương cứng của bạn.",
    "Bạn vô tình chạm vào một cơ quan bí mật, mở ra một căn phòng chứa đầy những nữ nô lệ chính đạo đang bị xích trong tư thế mời gọi.",
  ],
  "Hoang Miếu Đêm Khuya": [
    "Bạn là một đại ca Cái Bang, mang tham vọng nắm giữ mạng lưới ăn mày toàn cầu và thu thập mỹ nhân giang hồ cho hậu cung của mình.",
    "Ngôi miếu hoang này là nơi trú ẩn của những kẻ dạt vòm, nơi nhục dục và bản năng sinh tồn hòa quyện vào bóng tối đêm khuya.",
    "Mục tiêu của bạn là thu phục nữ bang chủ Cái Bang, người nắm giữ vẻ đẹp hoang dã và quyền năng điều khiển vạn ăn mày.",
    "Trong những đống rơm rạ ẩm ướt, bạn đang âm thầm gieo rắc những mầm mống dục vọng để biến các nữ hiệp thành dâm phụ.",
    "Bạn thề sẽ khiến nàng tiểu thư kiêu ngạo bị lạc vào đây phải quỳ xuống bú cu mình để đổi lấy sự bảo vệ và thức ăn.",
    "Mỗi đêm mưa đều là cơ hội để bạn tiếp cận và mơn trớn những cơ thể tuyệt mỹ đang khao khát hơi ấm nam nhi giữa cái lạnh.",
    "Hoang miếu này sẽ sớm trở thành một thiên đường hoan lạc bí mật, nơi bạn là vị vua duy nhất được hưởng thụ vạn mỹ nhân.",
    "Trong lúc trú mưa, bạn vô tình bắt gặp một nàng tiểu thư đang khỏa thân vắt quần áo bên đống lửa, làn da trắng ngần của nàng tỏa sáng.",
    "Bạn nhặt được một viên 'Dâm Đan' của một đạo sĩ đánh rơi, khi kích hoạt nó tỏa ra mùi hương khiến nữ ăn mày bên cạnh bỗng nhiên phát tình.",
    "Tình cờ nghe thấy tiếng rên rỉ phát ra từ sau tượng phật đổ nát, nơi một nữ bộ đầu đang lén lút tự giải tỏa cơn nứng đêm khuya.",
    "Đang đi trong miếu tối, bạn va phải một nữ hiệp khách đang trốn chạy, đôi vú căng tròn của nàng ép chặt vào người bạn đầy kích thích.",
    "Bạn tìm thấy một lối đi bí mật dẫn xuống hầm ngầm của miếu, nơi chứa đầy những nữ nô lệ đang bị xích trong tư thế mời gọi.",
    "Trong buổi họp bang, bạn tình cờ bắt gặp ánh mắt thèm khát của một nữ ăn mày đang nhìn chằm chằm vào dương vật đang cương cứng của bạn.",
    "Bạn vô tình chạm vào một cơ quan bí mật, mở ra một căn phòng chứa đầy những dụng cụ dâm dục mà kẻ nào đó lén lút cất giữ.",
  ],
  "Thiên Nhai Hải Giác": [
    "Bạn là một y sư lãng tử tại Thiên Nhai Hải Giác, mang tham vọng luyện chế ra thần dược biến mọi phụ nữ thành dâm phụ dưới thân mình.",
    "Tận cùng thế giới này là nơi chứa đựng những loại linh thảo kỳ lạ, nơi nhục dục và biển cả hòa quyện vào những con sóng vỗ về.",
    "Mục tiêu của bạn là chinh phục nữ thần y đối thủ, người nắm giữ vẻ đẹp mặn mà và kỹ năng y thuật đỉnh cao của vùng biển này.",
    "Trong những hang đá ven biển, bạn đang âm thầm xây dựng một hậu cung dược thảo nơi các mỹ nhân đều phải quỳ phục.",
    "Bạn thề sẽ khiến nữ cao thủ kiêu ngạo nhất phải quỳ xuống bú cu mình để đổi lấy liều thuốc chữa trị những căn bệnh thầm kín.",
    "Mỗi liệu trình chữa bệnh đều là cơ hội để bạn tiếp cận và mơn trớn những cơ thể tuyệt mỹ đang khao khát hơi ấm nam nhi.",
    "Vùng biển này sẽ sớm trở thành một thiên đường hoan lạc, nơi bạn là vị vua duy nhất được hưởng thụ vạn mỹ nhân giang hồ.",
    "Trong lúc hái thuốc ven biển, bạn vô tình bắt gặp một nữ cao thủ đang khỏa thân tắm biển, làn da trắng ngần của nàng tỏa sáng.",
    "Bạn nhặt được một viên 'Hải Đan' cổ đại, khi kích hoạt nó tỏa ra mùi hương khiến nữ đệ tử đi cùng bỗng nhiên phát tình.",
    "Tình cờ thấy nữ thần y đang lén lút tự thỏa mãn bằng một cành san hô hình dương vật trong hang đá đầy hương dược liệu.",
    "Đang đi trên bãi biển, bạn va phải một nữ hiệp khách đang bị thương, đôi vú căng tròn của nàng ép chặt vào người bạn đầy kích thích.",
    "Bạn tìm thấy một lối đi bí mật dẫn vào một hang động ngầm chứa đầy những nữ nô lệ đang bị xích trong tư thế mời gọi.",
    "Trong buổi lễ hội biển, bạn tình cờ bắt gặp ánh mắt thèm khát của một nữ hiệp đang nhìn chằm chằm vào dương vật đang cương cứng của bạn.",
    "Bạn vô tình chạm vào một cơ quan bí mật, mở ra một căn phòng chứa đầy những dụng cụ dâm dục mà kẻ nào đó lén lút cất giữ.",
  ],
  "Kiếm Pháp Tông Môn": [
    "Bạn là một thiên tài kiếm thuật trong Kiếm Pháp Tông Môn, mang tham vọng chinh phục toàn bộ các nữ kiếm tu và trở thành tông chủ.",
    "Tông môn này nổi tiếng với những đường kiếm sắc lẹm và những nữ đệ tử kiêu ngạo, nơi nhục dục bị kìm nén dưới kiếm ý lạnh lùng.",
    "Mục tiêu của bạn là thu phục nữ tông chủ thanh cao, người nắm giữ vẻ đẹp sắc sảo và kỹ năng kiếm thuật đỉnh cao của giới võ lâm.",
    "Trong những võ đài uy nghiêm, bạn đang âm thầm gieo rắc những mầm mống dục vọng để biến các nữ kiếm tu thành dâm phụ.",
    "Bạn thề sẽ khiến đại sư tỷ kiêu ngạo phải quỳ xuống bú cu mình ngay trên võ đài trước mặt toàn thể môn phái.",
    "Mỗi buổi luyện kiếm đều là cơ hội để bạn tiếp cận và mơn trớn những cơ thể săn chắc đang khao khát sự thâm nhập tột đỉnh.",
    "Kiếm Pháp Tông Môn sẽ sớm trở thành một thiên đường hoan lạc, nơi bạn là vị vua duy nhất được hưởng thụ vạn nữ kiếm tu.",
    "Trong lúc luyện kiếm, bạn vô tình bắt gặp đại sư tỷ đang khỏa thân tắm suối sau núi, cơ thể săn chắc của nàng tỏa sáng dưới nắng.",
    "Bạn nhặt được một thanh 'Dâm Kiếm' cổ đại, khi kích hoạt nó tỏa ra kiếm ý kích dục khiến nữ đệ tử đi cùng bỗng nhiên phát tình.",
    "Tình cờ thấy nữ tông chủ đang lén lút tự thỏa mãn bằng chuôi kiếm trong mật thất luyện công đầy kiếm khí lạnh lẽo.",
    "Đang đi trong tông môn, bạn va phải một nữ đệ tử nội môn, đôi vú căng tròn của nàng ép chặt vào người bạn đầy kích thích.",
    "Bạn tìm thấy một lối đi bí mật dẫn thẳng vào phòng tắm của các nữ kiếm tu, nơi bạn có thể thản nhiên quan sát họ khỏa thân.",
    "Trong buổi đại hội kiếm thuật, bạn tình cờ bắt gặp ánh mắt thèm khát của một nữ hiệp đang nhìn chằm chằm vào háng bạn.",
    "Bạn vô tình chạm vào một cơ quan bí mật, mở ra một căn phòng chứa đầy những nữ nô lệ đang bị xích trong tư thế mời gọi.",
  ],
  "Tiêu Cục Áp Tải": [
    "Bạn là một tiêu sư trong Tiêu Cục Áp Tải, mang tham vọng chiếm hữu toàn bộ các nữ tiêu sư và khách hàng mỹ nhân trên những chuyến hành trình.",
    "Tiêu cục này thường xuyên vận chuyển những món hàng quý giá và những mỹ nhân tuyệt sắc, nơi nhục dục bùng cháy trên những dặm đường xa.",
    "Mục tiêu của bạn là thu phục nữ tiêu đầu dũng mãnh, người nắm giữ vẻ đẹp hoang dã và kỹ năng áp tải đỉnh cao của giới võ lâm.",
    "Trong những chuyến đi dài ngày, bạn đang âm thầm gieo rắc những mầm mống dục vọng để biến các nữ đồng nghiệp thành dâm phụ.",
    "Bạn thề sẽ khiến nàng tiểu thư khách hàng kiêu ngạo phải quỳ xuống bú cu mình ngay trong xe ngựa giữa rừng sâu.",
    "Mỗi đêm nghỉ chân tại quán trọ đều là cơ hội để bạn tiếp cận và mơn trớn những cơ thể tuyệt mỹ đang khao khát sự bảo vệ.",
    "Tiêu cục này sẽ sớm trở thành một trang trại gieo giống di động, nơi bạn là vị chủ nhân duy nhất được hưởng thụ vạn mỹ nhân.",
    "Trong lúc nghỉ chân bên suối, bạn vô tình bắt gặp nữ tiêu đầu đang khỏa thân tắm rửa, cơ thể săn chắc của nàng tỏa sáng.",
    "Bạn nhặt được một viên 'Dâm Đan' của một tên cướp đánh rơi, khi kích hoạt nó tỏa ra mùi hương khiến nữ khách hàng bỗng nhiên phát tình.",
    "Tình cờ nghe thấy tiếng rên rỉ phát ra từ xe ngựa đêm khuya, nơi nàng tiểu thư đang lén lút tự giải tỏa cơn nứng vì cô đơn.",
    "Đang đi trên đường mòn, bạn va phải một nữ tiêu sư đang cảnh giới, đôi vú căng tròn của nàng ép chặt vào người bạn đầy kích thích.",
    "Bạn tìm thấy một lối đi bí mật dẫn vào khoang chứa hàng bí mật của tiêu cục, nơi chứa đầy những nữ nô lệ đang bị xích.",
    "Trong buổi tiệc mừng công, bạn tình cờ bắt gặp ánh mắt thèm khát của một nữ tiêu sư đang nhìn chằm chằm vào háng bạn.",
    "Bạn vô tình chạm vào một cơ quan bí mật trong xe ngựa, mở ra một căn phòng chứa đầy những dụng cụ dâm dục mà khách hàng cất giữ.",
  ],
  "Hoàng Cung Cấm Vệ": [
    "Bạn là một thống lĩnh cấm vệ quân trong Hoàng Cung, mang tham vọng chiếm hữu toàn bộ hậu cung của hoàng đế và trở thành chủ nhân thực sự.",
    "Hoàng cung này là nơi tập trung những mỹ nhân tuyệt sắc nhất thiên hạ, nơi nhục dục bị kìm nén dưới những quy tắc cung đình nghiêm ngặt.",
    "Mục tiêu của bạn là chinh phục hoàng hậu cao quý, người nắm giữ vẻ đẹp quyền quý và quyền năng điều khiển hậu cung vạn tiên.",
    "Trong những hành lang vàng son, bạn đang âm thầm gieo rắc những mầm mống dục vọng để biến các phi tần thành dâm phụ.",
    "Bạn thề sẽ khiến công chúa kiêu ngạo phải quỳ xuống bú cu mình ngay trong tẩm cung của nàng trước mặt các cung nữ.",
    "Mỗi buổi tuần tra đêm đều là cơ hội để bạn tiếp cận và mơn trớn những cơ thể tuyệt mỹ đang khao khát hơi ấm nam nhi giữa thâm cung.",
    "Hoàng cung này sẽ sớm trở thành một trang trại gieo giống khổng lồ, nơi bạn là vị vua duy nhất được hưởng thụ vạn mỹ nhân.",
    "Trong lúc tuần tra, bạn vô tình bắt gặp công chúa đang khỏa thân tắm trong hồ ngự uyển, làn da trắng ngần của nàng tỏa sáng.",
    "Bạn nhặt được một bức thư tình bí mật của một phi tần gửi cho tình nhân, bạn dùng nó để ép nàng phải phục vụ nhu cầu của mình.",
    "Tình cờ nghe thấy tiếng rên rỉ phát ra từ tẩm cung của hoàng hậu, nơi nàng đang lén lút tự thỏa mãn vì bị hoàng đế bỏ rơi.",
    "Đang đi trong hành lang cung đình, bạn va phải một nữ quan cao cấp, đôi vú căng tròn của nàng ép chặt vào người bạn đầy kích thích.",
    "Bạn tìm thấy một lối đi bí mật dẫn thẳng vào phòng tắm của các phi tần, nơi bạn có thể thản nhiên quan sát họ khỏa thân.",
    "Trong buổi yến tiệc, bạn tình cờ bắt gặp ánh mắt thèm khát của một vị vương phi đang nhìn chằm chằm vào háng bạn.",
    "Bạn vô tình chạm vào một cơ quan bí mật trong tẩm cung, mở ra một căn phòng chứa đầy những dụng cụ dâm dục mà hoàng đế cất giữ.",
  ],
  "Đào Hoa Đảo": [
    "Bạn lạc vào Đào Hoa Đảo, nơi cư ngụ của những nữ hiệp sĩ thông minh và xinh đẹp nhất, mang tham vọng dùng dương vật để phá giải mọi trận pháp của họ.",
    "Hòn đảo này quanh năm hoa đào nở rộ, ẩn chứa những trận pháp kỳ ảo và những khao khát thầm kín bị kìm nén dưới vẻ đẹp thơ mộng.",
    "Mục tiêu của bạn là chinh phục Đào Hoa Đảo Chủ, người nắm giữ vẻ đẹp sắc sảo và quyền năng điều khiển vạn trận pháp trên đảo.",
    "Trong những rừng đào rực rỡ, bạn đang âm thầm săn đuổi những nữ đệ tử mang vẻ đẹp thanh cao và dâm mị.",
    "Bạn thề sẽ khiến mọi mỹ nhân trên đảo đều phải rên rỉ dưới thân mình, biến nơi thơ mộng này thành một thiên đường hoan lạc nóng bỏng.",
    "Mỗi cánh hoa đào rơi đều mang theo một bí mật dục vọng, nơi các tiên nữ đang chờ đợi kẻ mang đến nòng nọc đất liền.",
    "Đào Hoa Đảo sẽ sớm trở thành một hậu cung rực rỡ, nơi tiếng rên rỉ dâm mị làm tan chảy mọi lớp phòng ngự trận pháp.",
    "Trong lúc đi dạo giữa rừng đào, bạn vô tình bắt gặp một nhóm nữ đệ tử đang khỏa thân tắm trong hồ nước nóng lộ thiên giữa rừng hoa.",
    "Bạn nhặt được một viên 'Đào Hoa Châu' có khả năng phát ra luồng nhiệt kích dục khi chạm vào, khiến nữ hiệp đi cùng bỗng nhiên muốn được bạn sưởi ấm.",
    "Tình cờ thấy Đào Hoa Đảo Chủ đang lén lút tự thỏa mãn bằng một cành hoa đào hình dương vật trong tẩm cung đầy hương sắc.",
    "Đang đi trong trận pháp, bạn va phải một nữ trưởng lão đang vội vã, đôi vú căng tròn của nàng ép chặt vào ngực bạn đầy kích thích.",
    "Bạn tìm thấy một hang động bí mật chứa đầy linh dịch kích dục, nơi các mỹ nhân trên đảo thường xuyên đến để giải tỏa cơn nứng thầm kín.",
    "Trong buổi lễ hội hoa đào, bạn tình cờ bắt gặp ánh mắt thèm khát của hàng chục nữ tu đang nhìn chằm chằm vào dương vật đang cương cứng của bạn.",
    "Bạn vô tình chạm vào một cơ quan bí mật, mở ra một căn phòng chứa đầy những nữ nô lệ đang bị xích trong tư thế mời gọi.",
  ],
  "Nga Mi Thánh Sơn": [
    "Bạn lạc vào Nga Mi Thánh Sơn, nơi cư ngụ của những nữ tu thanh cao và thoát tục nhất, mang tham vọng dùng dương vật để phá vỡ giới luật của họ.",
    "Ngọn núi này quanh năm mây phủ, linh khí mang theo sự thanh tịnh và những bí mật dâm mị bị kìm nén dưới những quy tắc nghiêm ngặt.",
    "Mục tiêu của bạn là chinh phục Nga Mi Chưởng Môn, người nắm giữ vẻ đẹp thánh khiết và quyền năng điều khiển vạn pháp Nga Mi.",
    "Trong những ngôi chùa cổ kính rực rỡ, bạn đang âm thầm gieo rắc những mầm mống dục vọng để biến các nữ tu thành dâm phụ.",
    "Bạn thề sẽ khiến mọi mỹ nhân Nga Mi đều phải rên rỉ dưới thân mình, biến thánh sơn thành một thiên đường hoan lạc nhầy nhụa.",
    "Mỗi tiếng chuông chùa đều mang theo hương vị của dục vọng, nơi các tiên nữ đang chờ đợi kẻ mang đến nòng nọc trần gian.",
    "Thánh Sơn sẽ sớm trở thành một trang trại gieo giống khổng lồ, nơi bạn là vị vua duy nhất được hưởng thụ mọi nữ tu.",
    "Trong lúc đi dạo giữa rừng trúc, bạn vô tình bắt gặp một nhóm nữ tu đang khỏa thân tắm rửa để tẩy trần bụi trần bên dòng suối thánh.",
    "Bạn nhặt được một viên 'Xá Lợi' có khả năng phát ra sóng âm kích dục, khiến nữ đệ tử Nga Mi đi cùng bỗng nhiên muốn được bạn nện.",
    "Tình cờ thấy Nga Mi Chưởng Môn đang lén lút dùng một thanh mộc ngư hình dương vật để tự thỏa mãn trong tẩm cung đầy kinh văn.",
    "Đang đi trong hành lang chùa, bạn va phải một nữ quan Nga Mi, đôi vú căng tròn của nàng ép chặt vào người bạn đầy kích thích.",
    "Bạn tìm thấy một hang động ngầm chứa đầy linh dịch kích dục, nơi các mỹ nhân Nga Mi thường xuyên đến để giải tỏa cơn nứng tập thể.",
    "Trong buổi lễ hội phật giáo, bạn tình cờ bắt gặp ánh mắt thèm khát của hàng chục nữ tu đang nhìn chằm chằm vào dương vật đang nổi lên của bạn.",
    "Bạn vô tình chạm vào một cơ quan bí mật, mở ra một căn phòng chứa đầy những nữ nô lệ đang bị xích trong tư thế mời gọi.",
  ],
  "Cái Bang Tổng Đà": [
    "Bạn lạc vào Cái Bang Tổng Đà, nơi cư ngụ của những nữ ăn mày hoang dã và mạnh mẽ nhất, mang tham vọng dùng dương vật để thống trị mạng lưới của họ.",
    "Tổng đà này nằm sâu trong những khu ổ chuột và hang động bí mật, nơi nhục dục và bản năng sinh tồn hòa quyện vào bóng tối.",
    "Mục tiêu của bạn là chinh phục Nữ Bang Chủ Cái Bang, người nắm giữ vẻ đẹp hoang dã và quyền năng điều khiển vạn ăn mày trên thế giới.",
    "Trong những đống rơm rạ ẩm ướt, bạn đang âm thầm gieo rắc những mầm mống dục vọng để biến các nữ ăn mày thành dâm phụ.",
    "Bạn thề sẽ khiến mọi mỹ nhân Cái Bang đều phải rên rỉ dưới thân mình, biến tổng đà thành một thiên đường hoan lạc dã tính.",
    "Mỗi tiếng gậy đập xuống đất đều mang theo hương vị của dục vọng, nơi các nữ hiệp đang chờ đợi kẻ mang đến nòng nọc vương giả.",
    "Tổng Đà sẽ sớm trở thành một trang trại gieo giống khổng lồ, nơi bạn là vị vua duy nhất được hưởng thụ vạn mỹ nhân Cái Bang.",
    "Trong lúc họp bang, bạn vô tình bắt gặp một nhóm nữ ăn mày đang khỏa thân tắm rửa bên đống lửa trại trong hang động bí mật.",
    "Bạn nhặt được một viên 'Dâm Đan' của một đạo sĩ đánh rơi, khi kích hoạt nó tỏa ra mùi hương khiến nữ ăn mày bên cạnh bỗng nhiên phát tình.",
    "Tình cờ nghe thấy tiếng rên rỉ phát ra từ sau tượng phật đổ nát, nơi Nữ Bang Chủ đang lén lút tự giải tỏa cơn nứng đêm khuya.",
    "Đang đi trong tổng đà, bạn va phải một nữ bộ đầu đang cảnh giới, đôi vú căng tròn của nàng ép chặt vào người bạn đầy kích thích.",
    "Bạn tìm thấy một lối đi bí mật dẫn xuống hầm ngầm của tổng đà, nơi chứa đầy những nữ nô lệ đang bị xích trong tư thế mời gọi.",
    "Trong buổi lễ hội Cái Bang, bạn tình cờ bắt gặp ánh mắt thèm khát của một nữ ăn mày đang nhìn chằm chằm vào dương vật đang cương cứng của bạn.",
    "Bạn vô tình chạm vào một cơ quan bí mật, mở ra một căn phòng chứa đầy những dụng cụ dâm dục mà kẻ nào đó lén lút cất giữ.",
  ],
  "Hệ Thống Làm Giàu Giang Hồ": [
    "Bạn sở hữu 'Hệ Thống Tiền Tệ Vạn Năng', có thể dùng vàng bạc để mua mọi bí kíp võ công và mỹ nhân giang hồ.",
    "Hệ thống tặng bạn một 'Tụ Bảo Bồn', mỗi ngày sinh ra hàng vạn lượng vàng, giúp bạn thâu tóm mọi tửu lầu và kỹ viện.",
    "Bạn dùng số tiền vô hạn để thuê toàn bộ các sát thủ hàng đầu bảo vệ mình, biến các nữ hiệp thành người hầu hạ.",
    "Hệ thống 'Thần Hào Võ Lâm' giúp bạn nhận được phản hồi tiền bạc gấp 1000 lần khi tặng quà cho các mỹ nhân.",
    "[HỆ THỐNG]: Thông báo: Bạn đã trở thành minh chủ tiền tệ giang hồ. Kích hoạt kỹ năng 'Vung Tiền Như Rác'.",
  ],
  "Dị Năng Đổi Đời Hiệp Khách": [
    "Dị năng 'Nhìn thấu bảo vật' giúp bạn tìm ra những kho báu của các triều đại trước, đổi đời thành đại phú gia.",
    "Bạn dùng dị năng 'Thao túng nhân tâm' để khiến các bang chủ phải dâng hiến toàn bộ ngân khố và con gái cho mình.",
    "Dị năng 'Tạo ra vàng ròng' giúp bạn sở hữu nguồn tài chính vô hạn, khiến mọi nữ hiệp phải quỳ lạy xin được che chở.",
    "Bạn dùng sức mạnh của mình để thâu tóm mọi nguồn lực kinh tế trong thiên hạ, biến những tiểu thư kiêu ngạo nhất thành nô lệ.",
    "[HỆ THỐNG]: Cảnh báo: Sự giàu sang của bạn đang bị triều đình dòm ngó. Hãy dùng tiền để mua chuộc các nữ quan ngay.",
  ],
  "Nữ Tướng Quân": [
    "Bạn là một phó tướng trẻ tuổi dưới quyền Nữ Tướng Quân Mộc Lan, người đang cải nam trang để thống lĩnh đại quân chống lại giặc ngoại xâm.",
    "Nữ Tướng Quân nổi tiếng với sự lạnh lùng và kỷ luật thép, nhưng bạn tình cờ phát hiện ra bí mật về giới tính của nàng khi nàng đang tắm bên suối.",
    "Trong một trận chiến ác liệt, bạn đã cứu mạng Nữ Tướng Quân, nàng đền đáp bằng một đêm nồng cháy ngay trong lều chỉ huy giữa tiếng trống trận.",
    "Nữ Tướng Quân muốn bạn làm 'vệ sĩ thân cận' hằng đêm để giúp nàng che giấu thân phận và giải tỏa những áp lực nặng nề của chiến tranh.",
    "Bạn sở hữu 'Hệ Thống Thống Soái', giúp bạn nhìn thấu mọi chiến thuật và cả những khao khát thầm kín của vị Nữ Tướng Quân kiêu hãnh.",
    "[HỆ THỐNG]: Nhiệm vụ: Chinh phục trái tim và thể xác của Nữ Tướng Quân. Phần thưởng: Quyền kiểm tra toàn bộ nữ binh trong quân đội.",
  ],
  "Nữ Hiệp Cải Nam Trang": [
    "Bạn là đệ tử của một môn phái lớn, tình cờ phát hiện ra vị 'sư huynh' tài năng nhất thực chất là một tuyệt thế mỹ nhân đang cải nam trang.",
    "Nàng cải nam trang để hành tẩu giang hồ và tìm kiếm kẻ thù giết cha, bạn hứa sẽ giữ bí mật nếu nàng đồng ý 'song tu' cùng bạn mỗi đêm.",
    "Trong một lần cùng nhau đi điều tra mật thất, bạn và 'sư huynh' bị trúng thuốc kích dục, khiến nàng phải cởi bỏ lớp ngụy trang để cầu xin bạn cứu giúp.",
    "Nữ hiệp cải nam trang bị trọng thương và ngất xỉu trong vòng tay bạn, khi cởi áo nàng để băng bó, bạn đã không kìm lòng được trước tòa thiên nhiên tuyệt mỹ.",
    "Bạn dùng dị năng 'Thấu Thị' để thản nhiên ngắm nhìn cơ thể ngọc ngà của nàng ẩn sau lớp y phục nam nhân thô kệch.",
    "[HỆ THỐNG]: Thông báo: Bạn đã phát hiện ra một 'Mỹ Nhân Ẩn Thân'. Kích hoạt nhiệm vụ: 'Lột Xác Mỹ Nhân'.",
  ],
  "Nữ Đế Tranh Hùng": [
    "Bạn là một thái giám giả (hoặc một nam sủng bí mật) của Nữ Đế, người đang nắm giữ quyền lực tối cao và khao khát thống nhất thiên hạ.",
    "Nữ Đế nổi tiếng với sự tàn nhẫn và uy nghiêm, nhưng khi màn đêm buông xuống, nàng lại trở thành một dâm phụ khao khát dương vật của bạn.",
    "Bạn dùng trí tuệ và sức mạnh của mình để giúp Nữ Đế dẹp loạn, đổi lại nàng ban cho bạn quyền được 'thị tẩm' mọi phi tần và cung nữ trong cung.",
    "Nữ Đế muốn bạn gieo giống để tạo ra một người thừa kế mang dòng máu mạnh mẽ nhất, nàng sẵn sàng quỳ xuống banh lồn để đón nhận tinh dịch của bạn.",
    "Dị năng 'Uy Áp Hoàng Đế' giúp bạn khuất phục hoàn toàn ý chí của Nữ Đế, biến nàng thành một nô lệ tình dục trung thành trên long sàng.",
    "[HỆ THỐNG]: Nhiệm vụ: Trở thành 'Thái Thượng Hoàng' bóng tối. Phần thưởng: Mở khóa kỹ năng 'Thao Túng Triều Đình'.",
  ],
  "Phim Ngắn Cổ Trang Trung Quốc": [
    "Bạn trọng sinh trở lại làm một vị hoàng tử bị ruồng bỏ, dùng kiến thức kiếp trước để tiêu diệt các đối thủ và biến các vương phi, công chúa của họ thành nô lệ tình dục.",
    "Bạn là một bác sĩ hiện đại xuyên không về làm một 'Thái Giám Giả' trong cung, dùng kỹ năng y thuật và 'dương vật' thật để chinh phục toàn bộ hậu cung của hoàng đế.",
    "Bối cảnh 'Nữ Chính Báo Thù' nơi bạn vào vai một sát thủ bí mật giúp đỡ nàng tiểu thư bị gia đình ruồng bỏ trở thành hoàng hậu, đổi lại nàng phải dâng hiến cơ thể cho bạn mỗi đêm.",
    "Bạn là một 'Vương Gia' lạnh lùng sở hữu hệ thống, nhiệm vụ của bạn là thu thập các nữ tướng và nữ hiệp nổi tiếng nhất thiên hạ vào 'Bản Đồ Mỹ Nhân' của mình.",
    "Bạn xuyên không vào thân xác của một tên lính canh ngục, nơi đang giam giữ những nữ tù nhân chính trị cao quý, bạn quyết định dùng quyền lực của mình để 'tha hóa' họ.",
    "Bối cảnh 'Thần Y Hạ Sơn' nơi bạn mang theo hôn ước với 7 vị tiểu thư quyền quý, bắt đầu hành trình thu phục từng người một bằng kỹ năng châm cứu dâm mị.",
    "Bạn là một 'Ma Giáo Giáo Chủ' trọng sinh, quyết tâm làm lại cuộc đời bằng cách bắt giữ các thánh nữ chính đạo và biến họ thành những dâm phụ phục vụ mình.",
    "Bạn là một tên nô tài thấp kém trong cung, nhưng lại sở hữu 'dương vật' vĩ đại khiến Nữ Đế và các phi tần phải lén lút tìm đến mỗi đêm.",
    "Bạn là một sơn tặc bắt được phu nhân của vị tướng quân đang bỏ trốn, bạn quyết định biến nàng thành áp trại phu nhân của mình.",
    "Bạn là một cao thủ ẩn dật được thuê để bảo vệ công chúa đi cầu thân, trong hành trình gian khổ, bạn đã chinh phục được trái tim và thể xác của nàng.",
    "Bạn giúp một vị phi tần bị thất sủng trả thù hoàng đế bằng cách biến nàng thành một dâm phụ chỉ biết phục vụ bạn ngay trong cung cấm.",
    "Bạn là một 'Thư Sinh' yếu ớt đi thi, nhưng thực chất là truyền nhân của 'Kiếm Thánh', dùng kiếm pháp vô song để cứu giúp các nữ hiệp khách gặp nạn.",
    "Bạn là một 'Thái Giám' trẻ tuổi trong cung, tình cờ phát hiện ra bí mật động trời của Thái Hậu trẻ đẹp và dùng nó để biến bà thành người phụ nữ của riêng mình.",
    "Bối cảnh 'Công Chúa Lạc Loài' nơi bạn cứu được một cô gái nghèo, sau đó phát hiện nàng là công chúa của tiền triều đang bị truy sát, bạn quyết định giúp nàng khôi phục giang sơn và chiếm hữu nàng.",
    "Bạn là một 'Lính Biên Thùy' dũng cảm, tình cờ bắt được nữ gián điệp của địch quốc và dùng 'nhục hình' dâm mị để khai thác thông tin từ nàng.",
    "[HỆ THỐNG]: Nhiệm vụ: Giúp đỡ Nữ Đế đăng cơ và trở thành 'Chủ Nhân' thực sự của nàng. Phần thưởng: Kỹ năng 'Ngự Nữ Vô Hạn'.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa 'Hậu Cung Cung Đình'. Mọi mỹ nhân trong cung đều có thể bị thị tẩm.",
  ],
  "Xuyên Không Võ Hiệp": [
    "Bạn xuyên không vào một cuốn tiểu thuyết võ hiệp và trở thành một tên phản diện bị mọi người khinh ghét, bạn phải dùng kiến thức về cốt truyện để sống sót và thu phục các nữ chính.",
    "Bạn xuyên không cùng 'Hệ Thống Tàng Kinh Các', sở hữu mọi bí kíp võ công trong thiên hạ và dùng chúng để chinh phục các nữ hiệp khách kiêu ngạo.",
    "Bạn là con trai của một tông chủ võ lâm xuyên không từ hiện đại, dùng phương pháp quản lý hiện đại để phát triển tông môn và xây dựng một hậu cung hùng mạnh.",
    "Bạn xuyên không về thời cổ đại và sở hữu 'Hệ Thống Võ Thần', mỗi khi đánh bại một đối thủ, bạn sẽ nhận được sự phục tùng của các mỹ nhân thuộc phe đó.",
    "Bạn sở hữu 'Hệ Thống Nhặt Thuộc Tính', chỉ cần đi sau các cao thủ đang giao chiến, bạn có thể nhặt được các thuộc tính như 'Võ Công', 'Tu Vi', 'Mị Lực' và 'Dâm Tính' của họ.",
    "Bạn xuyên không thành Chưởng môn của một môn phái phế vật sắp bị xóa sổ, nhưng có 'Hệ Thống Xây Dựng Tông Môn' giúp bạn biến các nữ đệ tử thành những tuyệt thế cao thủ và người hầu hạ riêng.",
    "Bạn sở hữu 'Hệ Thống Vạn Giới Đấu Giá', có thể mang những vật phẩm hiện đại hoặc thần cấp ra đấu giá để đổi lấy sự phục vụ của các nữ hiệp khách và tiên tử.",
    "Bạn xuyên không thành một tên dâm tặc khét tiếng vừa bị phế võ công, nhưng sở hữu 'Hệ Thống Song Tu Vô Hạn', chỉ cần giao hoan với mỹ nhân là võ công sẽ tự động phục hồi và tăng tiến.",
    "Bạn xuyên không thành một thanh kiếm thần có linh hồn, được một nữ hiệp khách xinh đẹp mang theo bên mình, bạn có thể giao tiếp và 'hướng dẫn' nàng tu luyện những tư thế nhạy cảm.",
    "Bạn xuyên không thành một tên phản diện trong tiểu thuyết võ hiệp, sở hữu 'Hệ Thống Nghịch Thiên Cải Mệnh', nhiệm vụ của bạn là cướp đi cơ duyên và mỹ nhân của nhân vật chính.",
    "Bạn sở hữu 'Hệ Thống Vạn Giới Võ Học', có thể học được mọi công pháp từ các thế giới khác nhau để trở thành đệ nhất cao thủ và xây dựng hậu cung võ lâm.",
    "Bạn xuyên không thành một tên tiểu tử nghèo khổ, tình cờ nhặt được 'Hệ Thống Nhặt Thuộc Tính', có thể nhặt được sức mạnh và kỹ năng từ những xác chết của các cao thủ.",
    "Bạn xuyên không thành một tên phế vật trong một môn phái lớn, sở hữu 'Hệ Thống Rút Thưởng Võ Học', mỗi lần rút thưởng bạn sẽ nhận được một công pháp dâm mị khiến các nữ hiệp phải tự nguyện dâng hiến.",
    "Bạn sở hữu 'Hệ Thống Tông Môn Vô Địch', có thể biến một ngôi miếu hoang thành thánh địa võ lâm, nơi các nữ hiệp khách thiên hạ đều khao khát được gia nhập để được bạn 'chỉ điểm' tu luyện.",
    "Bạn xuyên không thành một con yêu thú có linh trí, sở hữu 'Hệ Thống Hóa Hình', nhiệm vụ của bạn là bắt giữ các nữ tu sĩ để giúp mình thăng cấp và hóa thành nhân hình hoàn mỹ.",
    "Bạn sở hữu 'Hệ Thống Kiếm Thần', có thể lĩnh hội mọi kiếm ý chỉ bằng một cái nhìn, khiến các nữ kiếm khách thiên hạ phải bái phục và khao khát được bạn chỉ dạy 'kiếm pháp song tu'.",
    "Bạn xuyên không thành một tên phản diện trong thế giới võ hiệp, sở hữu 'Hệ Thống Plunder Khí Vận', chuyên đi cướp đoạt vận may và mỹ nhân của các 'con cưng của trời'.",
    "Bạn sở hữu 'Hệ Thống Chưởng Môn Vô Địch', nhiệm vụ của bạn là xây dựng tông môn mạnh nhất bằng cách thu nhận những nữ đệ tử có tư chất 'cực âm' để cùng nhau tu luyện công pháp đỉnh cao.",
    "[HỆ THỐNG]: Nhiệm vụ: Trở thành 'Võ Lâm Minh Chủ' và thống nhất giang sơn mỹ nhân.",
  ],
  "Nữ Hiệp Giang Hồ (Low NSFW/Lesbian)": [
    "Bạn là một nữ hiệp khách lãng du, sở hữu 'Hệ Thống Nữ Hiệp', nhiệm vụ của bạn là chinh phục trái tim của các nữ cao thủ và mỹ nhân giang hồ.",
    "Trong một môn phái toàn nữ, bạn là đại sư tỷ lạnh lùng, dùng kiếm thuật và mị lực để khiến các sư muội phải ngưỡng mộ và dâng hiến tình cảm.",
    "Bạn xuyên không thành một nữ ma đầu bị truy sát, sau khi khôi phục công lực, bạn bắt đầu hành trình thu phục các nữ hiệp chính đạo làm nô tỳ cho mình.",
    "Dị năng 'Mị lực nữ giới' khiến mọi phụ nữ trong giang hồ đều cảm thấy bị thu hút bởi bạn, sẵn sàng cùng bạn hành tẩu và song tu.",
    "Bạn là một nữ y sư tài năng, dùng những phương thuốc kỳ diệu để kiểm soát tâm trí và thể xác của các nữ cường giả võ lâm.",
    "Trong một hang động cổ xưa, bạn và nàng đối thủ truyền kiếp bị trúng xuân dược, cả hai buộc phải cùng nhau 'giải độc' và nảy sinh tình cảm sâu đậm.",
    "Bạn sở hữu 'Hệ Thống Song Tu Nữ Giới', giúp bạn và các bạn đời nữ cùng nhau thăng tiến công lực thông qua những màn ân ái nồng cháy.",
    "Là một nữ vương của một bang phái bí ẩn, bạn khao khát chiếm hữu nàng thánh nữ của phái Nga Mi, biến nàng thành người tình duy nhất của mình.",
    "Bạn dùng sức mạnh của mình để phá vỡ những quy tắc cổ hủ của võ lâm, thiết lập một trật tự mới nơi phụ nữ thống trị và yêu thương lẫn nhau.",
    "Hệ thống 'Nữ Chủ Chinh Phục' giao nhiệm vụ cho bạn phải thu phục trái tim của 5 nàng hoa khôi ở các môn phái lớn nhất.",
  ],
  "Hành Trình Tự Do Giang Hồ (Gender Neutral - SFW)": [
    "Bạn là một người kể chuyện rong, đi khắp các tửu quán để lắng nghe và chia sẻ những truyền thuyết về các anh hùng hào kiệt.",
    "Trong một giang hồ đầy ân oán, bạn là một người thợ rèn vũ khí, mang lại sự cân bằng bằng cách tạo ra những thanh kiếm bảo vệ chính nghĩa.",
    "Bạn sở hữu một quán trà nhỏ bên đường mòn, nơi đón tiếp những lữ khách mệt mỏi và lắng nghe những tâm tư thầm kín của họ.",
    "Bạn là một người bảo vệ những ngôi làng nhỏ khỏi bọn thảo khấu, dùng võ nghệ của mình để mang lại sự bình yên cho dân lành.",
    "Bạn là một nhà nghiên cứu về các bí kíp võ công cổ đại, đi khắp thế gian để tìm kiếm sự thật và hướng tới một võ lâm thái bình.",
  ],
};

export const IDENTITIES: string[] = Object.entries(RAW_DATA).flatMap(([context, scenarios]) => 
  scenarios.map(s => `Bối cảnh: ${context} - ${s}`)
);

export const SPECIALIZED_DATA: Record<string, { label: string, action: string }[]> = {};
